import type { RewrittenArticle } from "./types";

export const alanTuring: RewrittenArticle = {
  slug: "alan-turing",
  title: "Turing: the man who defined computation before there were computers",
  sourceTitle: "Alan Turing",
  dek: "He invented the machine in 1936 as a thought experiment, and it turned out the thought experiment was buildable.",
  standfirst:
    "Turing's most important paper was not about building anything. It was an attempt to settle a question in mathematical logic, and to settle it he had to define precisely what it means to follow a procedure. The definition he produced described a machine nobody had built, and every computer since has been an instance of it.",
  readingMinutes: 8,
  html: `
<h2 id="A_question_about_the_limits_of_mathematics">A question about the limits of mathematics</h2>
<p>The problem Turing set out to solve in 1936 came from David Hilbert, who had asked whether there exists a definite procedure that can determine, for any mathematical statement, whether it is provable. It was the last survivor of a programme aiming to place all of mathematics on complete, decidable foundations — a programme Gödel had already damaged in 1931 by showing that any sufficiently powerful formal system contains true statements it cannot prove.</p>
<p>Answering Hilbert required something nobody had supplied: a rigorous definition of "definite procedure". Turing's approach was to imagine the most stripped-down mechanical process capable of carrying out any calculation a human clerk could. He arrived at a device with an infinite paper tape divided into squares, a head that reads and writes one symbol at a time, a finite table of rules, and an internal state. That is the entire specification.</p>
<p>The claim — now called the Church–Turing thesis, since Alonzo Church reached an equivalent result independently by a very different route — is that this trivially simple machine can compute anything computable at all. It is not a theorem and cannot be proved, because it connects a formal definition to an informal intuition. Ninety years of attempts to find a counterexample have failed.</p>

<h2 id="The_universal_machine">The universal machine</h2>
<p>The paper's second idea is the one that built the industry. Turing observed that a machine's rule table can be written on the tape as data, and that a single machine can be constructed to read that description and behave accordingly.</p>
<p>This is the universal Turing machine, and it is the concept of software. Before it, calculating devices were built to do one thing, and doing something else meant building another device or rewiring this one. Turing showed that hardware and instructions need not be distinct: one general machine plus a description does the work of every special machine. The stored-program computer, the operating system, the app on your phone are all consequences of a footnote in a logic paper.</p>
<p>He also proved something negative and permanent. The halting problem asks for a procedure that determines whether an arbitrary program will eventually stop or run forever. Turing showed no such procedure can exist — assume one does, and you can build a program that halts exactly when it does not. This settled Hilbert's question in the negative and established that some questions are not merely difficult but formally beyond any algorithm, a boundary that still constrains what software verification can promise.</p>

<h2 id="Bletchley_Park">Bletchley Park</h2>
<p>Turing joined Britain's codebreaking operation the day after war was declared. The Enigma machine used by German forces encrypted each letter through a set of rotors that advanced with every keystroke, so the same letter enciphered differently each time, and the settings changed daily. The number of possible configurations ran to the order of a hundred million million million.</p>
<p>Polish cryptanalysts had made critical progress before the war and shared it. Turing, with Gordon Welchman, designed the bombe — an electromechanical machine that did not search the key space but eliminated it. The insight was to attack the cipher's own guarantee: Enigma never enciphered a letter as itself. Combined with cribs, guesses at likely plaintext such as weather reports and formulaic sign-offs, that constraint let the bombe reject the overwhelming majority of settings mechanically and leave a handful for humans.</p>
<p>Turing then broke the harder naval Enigma, used by the U-boats strangling Atlantic convoys, and developed a statistical method for weighing evidence that anticipated later work in sequential analysis. Historians' estimates of the war's shortening vary, commonly citing a year or more. The work stayed classified for decades, so the people who did it could not be credited while it might have mattered to them.</p>

<h2 id="Can_machines_think">Can machines think</h2>
<p>After the war Turing worked on actual computer designs and then turned to the question of whether they could be said to think. His 1950 paper opens by declaring the question itself too ill-defined to answer and replacing it with a test: an interrogator exchanges written messages with a human and a machine, and tries to tell which is which. If they cannot reliably do so, Turing argued, refusing to call the machine intelligent is a prejudice rather than a position.</p>
<p>The paper is more careful than its reputation. Turing anticipates and answers most of the objections still raised — that machines only do what they are told, that they lack consciousness, that they cannot be original — and concedes that the consciousness objection cannot be refuted, only that it applies equally to other people, whose inner experience we also infer from behaviour. He also predicted machine learning would be the practical route, suggesting it would be easier to build a child's mind and educate it than to program an adult's.</p>
<p>His final research went somewhere unexpected. In 1952 he published on morphogenesis, showing mathematically how two chemicals diffusing and reacting can spontaneously break symmetry and generate stable patterns — stripes, spots, regular spacing. It was a proposal for how an undifferentiated embryo could develop structure without a blueprint, and it was decades ahead of the biology. Turing patterns are now an established part of developmental biology, confirmed in systems from fish pigmentation to the spacing of hair follicles.</p>

<h2 id="Prosecution">Prosecution</h2>
<p>In 1952 Turing reported a burglary at his home. In the course of the investigation he described his relationship with a man, and was charged with gross indecency under the same 1885 law used against Oscar Wilde. He did not contest the facts.</p>
<p>Offered prison or probation conditional on hormone treatment, he accepted the treatment — synthetic oestrogen, administered for a year, which caused physical changes and which he discussed with characteristic detachment. The conviction cost him his security clearance and ended the government work, at a point when a man who had broken Enigma was suddenly a risk rather than an asset.</p>
<p>He died in 1954, aged 41, of cyanide poisoning. The inquest recorded suicide; a partly eaten apple beside the bed was never tested. Some, including his mother, believed it was an accident from his home chemistry experiments. The evidence does not settle it.</p>
<p>An official apology came in 2009, a royal pardon in 2013, and a 2017 law extending pardons to the tens of thousands of other men convicted under the same statute — most of whom had broken no ciphers and are owed the same apology. Turing appears on the fifty-pound note. The gestures are worth something and are not a substitute for what was taken: the field he founded lost him at 41, and there is no way to know what the next twenty years would have held.</p>
`,
};
