import type { RewrittenArticle } from "./types";

export const aqueducts: RewrittenArticle = {
  slug: "aqueducts",
  title: "Aqueducts: the famous arches were the exception",
  sourceTitle: "Aqueduct (water supply)",
  dek: "Most of a Roman aqueduct ran underground at a slope too gentle to see. The engineering was in the surveying, and the water never stopped flowing.",
  standfirst:
    "The image of an aqueduct is a row of stone arches striding across a valley. Those arches existed, and some still stand, but they were the expensive exception — built only where the ground fell away and the channel had to be held up. The rest of the system ran quietly underground, descending a few centimetres per hundred metres over distances of tens of kilometres. Moving water by gravity alone is a problem of surveying more than of building, and the ancient solutions to it are still in service in parts of the world.",
  readingMinutes: 7,
  published: "2026-10-02",
  html: `
<h2 id="Gravity">Moving water with nothing but a slope</h2>
<p>Before mechanical pumping, the only way to move large quantities of water a long distance was to let it run downhill. That sounds simple and is not. The channel must fall continuously from source to destination; too steep and the water scours the channel and arrives too fast, too shallow and it stagnates or stops. Over many kilometres of uneven terrain, keeping that gradient steady requires measuring small differences in height across long distances with real accuracy.</p>
<p>The aqueduct that supplied the Roman city of Nîmes, in southern France, is the classic illustration. It runs for roughly fifty kilometres and loses only about twelve metres of height over its whole length — an average fall of around twenty-five centimetres per kilometre, a slope invisible to the eye. Its most famous structure, the three-tiered Pont du Gard, carries the channel across the Gardon river nearly fifty metres up, and exists only because the route required it.</p>
<p>Where a valley was too deep to bridge, Roman engineers sometimes used inverted siphons: sealed pipes, often of lead, that carried water down one side of the valley and up the other under pressure, relying on the source end being slightly higher. Several of the aqueducts supplying Lyon used them.</p>

<h2 id="Rome">The waters of Rome</h2>
<p>The city of Rome was eventually served by eleven major aqueducts, built over about five centuries starting with the Aqua Appia in 312 BC. Almost all of their combined length ran underground or at ground level, which protected the water from heat, contamination and enemies; the arcades visible around the city today are the final approaches, where channels were raised to deliver water at enough height to distribute it.</p>
<p>Much of what is known about how the system was run comes from Sextus Julius Frontinus, appointed water commissioner in AD 97, whose treatise on the aqueducts records their sources, lengths and capacities. It also records his complaints: illegal taps by private landowners along the routes, officials taking bribes to let them continue, and a gap between the water entering the system and the water officially delivered that he attributed largely to theft.</p>
<p>The Roman system ran continuously. There were no valves to turn off the supply; water flowed day and night into public fountains, baths and the houses of those with a licensed connection, and the overflow went to flush the sewers. Estimates of the total quantity delivered vary widely because they depend on assumptions about how full the channels ran, but even conservative figures imply a supply per person that many cities did not match again until the twentieth century.</p>
<p>The aqueducts also left a scientific record. Roman water was hard, and the calcium carbonate it deposited on channel walls built up in layers, sometimes seasonal, that archaeologists now read to estimate how long particular aqueducts were in use and how well they were maintained. The same deposits help explain why the lead pipes used for distribution were less dangerous than they sound: the mineral crust coated the inside of the pipes and limited contact between water and lead. Lead exposure in Rome was real, but the popular claim that it brought down the empire is not supported by the evidence.</p>

<h2 id="Qanats">The tunnels that went to the water</h2>
<p>Older and in some ways more ingenious than the Roman system is the qanat, developed in Persia in the first millennium BC and spread across the Middle East, North Africa and Central Asia. A qanat begins at a mother well dug into an aquifer at the foot of a mountain, and from there a gently sloping tunnel is driven out to the fields or settlement below, with vertical shafts every few dozen metres for excavation, ventilation and maintenance.</p>
<p>From the air, a qanat looks like a line of craters across the desert. Underground, it delivers groundwater by gravity with almost no evaporation, which matters enormously in a hot, dry climate. Thousands remain in use in Iran, some of them centuries old, though many have been abandoned as motorised pumps lowered the water tables they depended on.</p>
<p>Earlier still, the Assyrian king Sennacherib brought water to Nineveh in the early seventh century BC through a system of canals that included a stone aqueduct bridge at Jerwan, remains of which survive in northern Iraq.</p>

<h2 id="Modern">Taking water from somewhere else</h2>
<p>Industrial cities revived the long-distance aqueduct on a far larger scale. New York built a series of systems reaching ever further into upstate watersheds, the later ones tapping the Catskill and Delaware catchments more than a hundred kilometres away. The water still arrives largely by gravity, and the protected catchments are clean enough that most of the city's supply has historically needed disinfection but not full filtration — a deliberate trade of land protection for treatment plants.</p>
<p>Los Angeles took a more contentious route. The aqueduct completed in 1913 under William Mulholland brought water from the Owens Valley, around three hundred and seventy kilometres to the north, after the city quietly bought up land and water rights there. Owens Lake was largely dried out by the diversions, the valley's farming economy collapsed, and local opposition in the 1920s included repeated dynamiting of the aqueduct. The conflict became shorthand for urban water politics, and court-ordered efforts to control the dust blowing off the dry lake bed have continued for decades.</p>
<p>Gravity has its limits. California's State Water Project, carrying water from the wet north to the dry south, must lift it over the Tehachapi Mountains, and the pumping plant that does so raises water nearly six hundred metres in a single stage — one of the highest lifts of its kind in the world, and a reminder of how much energy is spent when water cannot simply be allowed to run downhill.</p>
`,
};
