import type { RewrittenArticle } from "./types";

export const atomicClocks: RewrittenArticle = {
  slug: "atomic-clocks",
  title: "Atomic clocks: precise enough that raising one by a foot changes its rate",
  sourceTitle: "Atomic clock",
  dek: "The best clocks now measure gravitational time dilation across the height of a table. This stopped being a physics demonstration and became a surveying problem.",
  standfirst:
    "An atomic clock does not measure time so much as count a natural constant: the frequency at which a particular electron transition absorbs radiation, which is identical in every atom of that isotope everywhere. That property is what makes the second reproducible in a way no pendulum or planet could be. Modern optical clocks are so stable that general relativity is no longer a correction to be applied but an effect visible between two clocks in the same room.",
  readingMinutes: 7,
  html: `
<h2 id="Principle">Counting an atom instead of a swing</h2>
<p>Every clock consists of an oscillator and a counter. The quality of the clock is set by how reproducible the oscillator's frequency is — how much it drifts with temperature, pressure, age and manufacture.</p>
<p>A pendulum's period depends on its length and the local gravity, both of which vary. A quartz crystal's frequency depends on how it was cut and ages measurably. An atom's transition frequency depends on nothing: the energy gap between two states of caesium-133 is a property of the atom, and one caesium atom is exactly like another anywhere in the universe.</p>
<p>The clock works by using that gap as a reference. Microwave radiation from a quartz oscillator is directed at a population of atoms; if the frequency is exactly right, atoms change state, and the number that do is measured and fed back to steer the oscillator. The atoms do not produce the signal — they judge it.</p>
<p>The practical difficulty is that atoms move, and a moving atom sees a Doppler-shifted frequency. The first accurate caesium standard, built by Louis Essen and Jack Parry at the National Physical Laboratory in 1955, used a beam of atoms passing through two separated microwave regions, a trick devised by Norman Ramsey that makes the measurement sensitive to the average over the flight time and sharpens the resonance considerably.</p>
<p>Slowing the atoms down is the other approach, and it produced the fountain clock: laser cooling holds a cloud of caesium at a few millionths of a degree above absolute zero, the cloud is tossed upward, and it passes through a single microwave cavity twice, once rising and once falling. The longer interrogation time gives a narrower resonance. Caesium fountains are the primary standards that define the second today and keep time to within about one second in three hundred million years.</p>

<h2 id="Redefinition">The second stops being astronomical</h2>
<p>In 1967 the General Conference on Weights and Measures redefined the second as 9,192,631,770 periods of the caesium transition. The number is not round because it was chosen to match the second then in use, defined from the Earth's orbital motion, so that no measurement in the world would change.</p>
<p>This was the first base unit to be defined by a quantum property rather than an artefact or an astronomical phenomenon, and it set the pattern for the rest. The metre followed in 1983, defined by fixing the speed of light, which makes length a derived quantity measured with clocks. The 2019 revision of the SI defined the kilogram, ampere, kelvin and mole in terms of fixed constants, and every one of those definitions depends on the second, because the second is by a wide margin the most accurately realisable unit there is.</p>
<p>The consequence is that timekeeping now underwrites metrology generally. If the second is realised more accurately, several other units improve with it.</p>

<h2 id="Optical">Optical clocks and the next redefinition</h2>
<p>Caesium's transition is a microwave one, at about nine gigahertz. Optical transitions run at hundreds of terahertz — some tens of thousands of times faster — and a faster oscillator divides time more finely, in the same way that a ruler with finer graduations measures length better.</p>
<p>The obstacle for decades was counting oscillations that fast, which no electronics can do. The solution was the optical frequency comb, developed by John Hall and Theodor Hänsch around 2000 and awarded a share of the 2005 Nobel Prize: a laser producing a precisely spaced series of frequencies acts as a gearbox between optical and microwave regions, so an optical oscillation can be counted with ordinary electronics.</p>
<p>Optical clocks based on trapped ions of aluminium or ytterbium, or on neutral strontium atoms held in a lattice of laser light, now reach uncertainties on the order of one part in ten to the eighteenth or better. That corresponds to neither gaining nor losing a second over a period comparable to the age of the universe.</p>
<p>The second is expected to be redefined in terms of an optical transition, with a target around 2030. The main obstacle is not building the clocks but agreeing which transition and demonstrating that clocks in different laboratories, using different atoms, agree at the required level once compared over intercontinental links — which is itself a hard problem, since the comparison must not be limited by the fibre or satellite link between them.</p>

<h2 id="Relativity">Gravity as a measurement problem</h2>
<p>General relativity requires that clocks deeper in a gravitational field run slower. Near the Earth's surface the effect is about one part in ten to the sixteenth per metre of height.</p>
<p>At that scale, a clock accurate to one part in ten to the eighteenth resolves a height difference of a centimetre. This has been demonstrated directly — clocks separated vertically by small distances in a laboratory, and more recently different regions of a single trapped atom cloud, show measurably different rates.</p>
<p>The immediate consequence is that a clock's location must be specified before its reading means anything, and the international time scale is defined at a reference geopotential with every contributing clock corrected for its altitude. Timekeeping and geodesy have merged: since a clock's rate reports the gravitational potential where it sits, a sufficiently good clock is a gravimeter, and relativistic geodesy proposes using transportable optical clocks to measure the shape of the Earth's gravity field directly, which is difficult to do well by any other method.</p>
<p>Satellite navigation is where these effects became ordinary engineering. GPS satellites carry atomic clocks in orbit, where they run faster than ground clocks because gravity is weaker, by roughly 45 microseconds a day, and slower because of their orbital speed, by roughly 7 microseconds a day. The net is about 38 microseconds a day, which at the speed of light amounts to positional errors accumulating at something like ten kilometres a day if uncorrected. The satellites' oscillators are deliberately offset before launch to compensate.</p>

<h2 id="Uses">What the accuracy is actually for</h2>
<p>Almost nobody needs to know the time to a nanosecond. A great many systems need to agree with each other to a nanosecond, which is a different requirement.</p>
<p>Mobile telephone networks require base stations to be synchronised for handover and for the division of the radio spectrum between them. Electrical grids use synchronised phasor measurements to detect instability across a continent, which requires a common time reference at the microsecond level. Financial regulation in several jurisdictions mandates timestamping of trades to a specified accuracy, so that the order of events across venues can be reconstructed. Data centres use tightly bounded clock uncertainty to order distributed transactions without coordination, an approach made prominent by Google's Spanner.</p>
<p>Radio astronomy makes the most extreme demand. Very long baseline interferometry combines signals from telescopes on different continents to synthesise an aperture the size of the Earth, and doing so requires each station to record with a local frequency standard stable enough that the signals can be correlated afterwards. The image of a black hole shadow produced by the Event Horizon Telescope depended on hydrogen masers at each site.</p>
<p>The vulnerability in all of this is that most of these systems get their time from GPS, and the GPS signal at the ground is extremely weak and trivially jammed or spoofed. This has become a recognised infrastructure risk, and the responses — terrestrial backup time signals, fibre-based dissemination from national laboratories, and local holdover clocks good enough to ride out an outage — amount to rebuilding the ability to keep time without looking at the sky, which is roughly where the story started.</p>
`,
};
