import type { RewrittenArticle } from "./types";

export const bridges: RewrittenArticle = {
  slug: "bridges",
  title: "Bridges: every type is a different answer to where the tension goes",
  sourceTitle: "Bridge",
  dek: "Beam, arch, truss, suspension and cable-stayed are not styles. They are five arrangements for handling the fact that spanning a gap always puts something in tension.",
  standfirst:
    "A bridge holds a load in the air over a gap, and doing so always produces both compression and tension somewhere. The bridge types are distinguished by where each is placed and which material carries it — which is why arches dominated when only stone was available, why iron and steel produced trusses and suspension bridges within a few decades of becoming cheap, and why the failures that matter have almost all involved a force the designers had not thought to include.",
  readingMinutes: 7,
  html: `
<h2 id="Five_types">The five arrangements</h2>
<p>A <strong>beam</strong> carries load by bending: the top of the deck is compressed, the bottom stretched. It is the simplest and least efficient form, because most of the material sits near the neutral axis in the middle doing nothing, and its span is limited by the fact that a longer beam must be deeper, which makes it heavier, which requires it to be deeper still. Almost every short bridge in the world is a beam, because at short spans efficiency does not matter and simplicity does.</p>
<p>An <strong>arch</strong> converts the load into compression along a curve and pushes outward at its feet, so it requires abutments capable of resisting that thrust — which is why arches suit rocky gorges and suit soft riverbanks badly. It was the only long-span option for as long as stone was the only material.</p>
<p>A <strong>truss</strong> is a beam turned into a lattice, with material concentrated where the forces actually are. Each member carries pure tension or pure compression along its length, and the triangulated arrangement is what guarantees that. It became viable when iron made tension members cheap, and it is why nineteenth-century railway bridges look the way they do.</p>
<p>A <strong>suspension</strong> bridge hangs the deck from cables that carry the entire load in tension, transferring it to towers in compression and to anchorages at each end that must resist an enormous horizontal pull. It is the most efficient long-span form because steel cable in tension is close to the best structural material available, and every strand of a cable works at its full strength — unlike a compression member, which can buckle.</p>
<p>A <strong>cable-stayed</strong> bridge runs cables directly from tower to deck, with no main cable and no anchorage. It carries the horizontal component into the deck itself, which must therefore resist compression, and it is stiffer than a suspension bridge, cheaper in the medium span range, and now the default for spans from a few hundred metres to around a kilometre.</p>

<h2 id="Cable">Why the suspension cable hangs where it does</h2>
<p>The main cable of a suspension bridge takes the shape dictated by the load hanging from it. Under its own weight alone it would form a catenary; under a deck of uniform weight per horizontal metre, which is the actual condition, it forms a parabola.</p>
<p>This matters because the cable has no bending stiffness — it cannot resist a shape it is not given by the loads. A concentrated load at one point pulls the cable out of shape locally, and the deck's own stiffness is what distributes such loads along the cable so this does not happen. The deck in a suspension bridge is not merely the road; it is the element that makes the cable's geometry stable.</p>
<p>The cables are spun in place rather than delivered. A wheel carries a wire across and back thousands of times, laying up parallel strands that are then compacted and wrapped, a method developed by John Roebling and used essentially unchanged since. Parallel wires are used rather than twisted rope because twisting reduces effective strength.</p>
<p>The anchorages are the unappreciated part. The horizontal pull at each end of the main cable is enormous, and it is resisted either by a mass of concrete or by anchoring into competent rock. On a major crossing the anchorage blocks are among the largest single elements of the works, and they are the reason a suspension bridge is expensive at short spans and economical at long ones — the anchorage cost is nearly fixed regardless of span.</p>

<h2 id="Tacoma">The wind problem, and what Tacoma actually was</h2>
<p>Tacoma Narrows collapsed on 7 November 1940, four months after opening, in a wind of around 65 kilometres an hour — far below what the bridge was designed to withstand as a static force.</p>
<p>The explanation given in a great many textbooks, that this was resonance with the frequency of vortex shedding, is wrong, and the error has been pointed out repeatedly since at least the 1990s. The failure mode was aeroelastic flutter, which is a self-excited oscillation: the deck's twisting motion changes the angle at which the wind meets it, which generates a force that feeds more energy into the twisting. The system extracts energy from a steady wind and the amplitude grows without any external oscillation matching a natural frequency. It is the same phenomenon that limits aircraft wing design.</p>
<p>The bridge was vulnerable because it was extraordinarily slender — a shallow solid plate girder deck, chosen for economy and appearance, with very low torsional stiffness and a shape that behaved like an aerofoil rather than letting air through.</p>
<p>The consequences reshaped the field. Wind tunnel testing of deck sections became standard practice for long-span bridges. Decks were given open trusses or, later, streamlined box sections that shed wind cleanly, an approach pioneered on the Severn Bridge in 1966 and now near-universal. And bridge engineering acquired a permanent awareness that a structure can be destroyed by a force it generates itself.</p>
<p>The Millennium Bridge in London made the same category of mistake in a different variable. On opening in 2000 it swayed laterally under pedestrian load, because a slight sideways motion causes walkers to adjust their gait in step with it, which reinforces the motion — synchronous lateral excitation, a feedback loop between the structure and the people on it, which had not been part of standard design codes. It closed for nearly two years and reopened with dampers fitted.</p>

<h2 id="Failure">How bridges fail</h2>
<p>The pattern in major bridge failures is consistent: a new form is developed, it succeeds, it is extrapolated beyond the range in which its assumptions were tested, and it fails.</p>
<p>The Tay Bridge collapsed in a gale in December 1879 with a train on it, killing everyone aboard. The inquiry found the design had made inadequate allowance for wind loading, along with poor-quality castings and inadequate maintenance. British wind loading standards for bridges date from that inquiry.</p>
<p>The Quebec Bridge collapsed during construction in 1907, killing 75 workers, after the actual weight of the cantilever exceeded the design assumptions and warnings about deforming compression members were not acted on decisively. It collapsed a second time in 1916 during the lifting of a replacement span. The Iron Ring worn by Canadian engineering graduates is associated with the disaster in professional tradition.</p>
<p>Modern failures are more often maintenance failures than design failures. Fatigue cracking from repeated loading, corrosion of embedded steel, and scour — the erosion of riverbed material around piers by flowing water, which is the leading cause of bridge failure in several countries — accumulate invisibly. The Genoa bridge collapse of 2018 and the Minneapolis collapse of 2007 both turned on conditions that had been present and documented for years.</p>
<p>The structural concept underlying inspection regimes is redundancy. A fracture-critical structure is one in which the failure of a single element causes collapse of the whole, and older truss and two-girder designs are frequently in this category, whereas a multi-girder deck can shed load to its neighbours. Design has moved toward redundancy specifically so that undetected deterioration in one member is survivable.</p>

<h2 id="Span">What sets the maximum</h2>
<p>The theoretical limit on a suspension span is set by the cable's own weight. A cable long enough eventually cannot carry itself, and the limit depends on the strength-to-weight ratio of the material — for high-strength steel wire it lies in the several-kilometre range, well beyond anything built.</p>
<p>The practical limits arrive far sooner and are economic and aerodynamic. Cost rises steeply with span, the deck must be made stiff and streamlined enough to remain stable in wind, and the towers become extremely tall. The longest spans in service are a little under two kilometres, achieved by the Akashi Kaikyō Bridge in 1998 and surpassed by the Çanakkale 1915 Bridge in 2022.</p>
<p>The interesting recent development is that the economic crossover points have moved. Cable-stayed bridges have taken over spans that would once have required suspension, because they need no anchorage and can be built by cantilevering outward from each tower without falsework in the water. That construction method — building the structure symmetrically outward so it balances itself at every stage — is often the deciding factor over deep or busy water, which is a reminder that a bridge must be stable not only when finished but at every moment while it is being built.</p>
`,
};
