import type { RewrittenArticle } from "./types";

export const challenger: RewrittenArticle = {
  slug: "challenger",
  title: "Challenger: the launch the engineers tried to stop",
  sourceTitle: "Space Shuttle Challenger disaster",
  dek: "The night before, the engineers who knew the booster seals best said it was too cold to fly. How their warning was overruled became the most studied decision in engineering.",
  standfirst:
    "On 28 January 1986 the space shuttle Challenger broke apart 73 seconds after launch, killing all seven people on board, in front of a television audience that included schoolchildren watching a teacher go to space. The physical cause was found within weeks: a rubber seal that had stiffened in the cold. The harder question was why an organisation full of capable engineers had launched in conditions some of them had warned, in writing and out loud, could kill the crew.",
  readingMinutes: 8,
  published: "2026-10-06",
  html: `
<h2 id="The_flight">Seventy-three seconds</h2>
<p>Mission STS-51-L was the shuttle programme's twenty-fifth flight and Challenger's tenth. Its crew were Dick Scobee, the commander; Michael Smith, the pilot; mission specialists Judith Resnik, Ellison Onizuka and Ronald McNair; Gregory Jarvis, an engineer from Hughes Aircraft; and Christa McAuliffe, a high-school teacher from New Hampshire chosen from more than eleven thousand applicants to be the first teacher in space. Because of her, many classrooms across the United States were watching.</p>
<p>The launch had been postponed several times. On the morning of 28 January, after a night of hard frost in Florida, the air temperature at launch was about 2°C — many degrees colder than any previous shuttle launch. Ice hung from the launch tower.</p>
<p>Less than a second after ignition, cameras recorded puffs of dark smoke from a joint near the bottom of the right-hand solid rocket booster. The leak appears to have been plugged temporarily by aluminium oxide from the burning propellant. About fifty-eight seconds into the flight, as the shuttle passed through strong high-altitude winds, a flame appeared at the same joint and played against the huge external fuel tank and the strut holding the booster to it. At 73 seconds the tank failed and the vehicle was torn apart by aerodynamic forces at an altitude of about fourteen kilometres.</p>
<p>It is often described as an explosion; strictly, the escaping propellants burned in a fireball as the vehicle broke up. The crew cabin survived the break-up largely intact and fell for more than two minutes before striking the ocean. Several of the crew's emergency air packs had been switched on, which suggests that at least some of them were alive and conscious for part of the fall.</p>

<h2 id="The_joint">A seal that needed to be warm</h2>
<p>The solid rocket boosters were built by the contractor Morton Thiokol in Utah in segments, shipped by rail and stacked at the launch site. The joints between segments were sealed by two rubber O-rings, each about seven millimetres thick and more than eleven metres around. At ignition the pressure inside the booster made the joint flex slightly open, and the O-rings had to spring into the gap fast enough to seal it. Cold rubber is stiff, and springs back slowly.</p>
<p>The problem was not new. Inspection of boosters recovered after earlier flights had found O-rings partly burned through by hot gas — erosion — and, on some flights, soot that had blown past the primary ring. The worst case had followed a launch in January 1985 at what had then been the coldest temperature on record. In July 1985 a Thiokol engineer, Roger Boisjoly, wrote a memo warning his managers that if the problem was not solved, the result could be "a catastrophe of the highest order — loss of human life". A task force was set up. The flights continued.</p>
<p>Each time a flight returned with damage but without disaster, the damage was folded into what counted as acceptable. Erosion was compared with the depth that would cause failure and declared within a safety margin, although the joint had never been designed to erode at all.</p>

<h2 id="The_teleconference">The night before</h2>
<p>On the evening of 27 January, with record cold forecast, Thiokol engineers joined a teleconference with NASA's Marshall Space Flight Center, which managed the boosters. They recommended against launching at temperatures below 12°C, the coldest at which a shuttle had previously flown. NASA's managers pushed back hard. The engineers' data were incomplete, and they could not prove that the joint would fail. One Marshall manager, Lawrence Mulloy, asked whether Thiokol expected NASA to wait until April.</p>
<p>Thiokol asked for a recess. Off the line, its senior managers discussed the recommendation among themselves. The engineers repeated their objections, and were overruled. According to testimony to the investigating commission, the company's general manager told its vice-president of engineering to "take off your engineering hat and put on your management hat". When the call resumed, Thiokol withdrew its objection and recommended launch. The concerns were not passed up to the senior NASA officials who made the final decision.</p>
<p>What had changed in that conversation was the burden of proof. Ordinarily, engineers had to show that a vehicle was safe to fly. That night, they were being asked to prove that it was unsafe — and with the data they had, they could not.</p>

<h2 id="The_commission">"Nature cannot be fooled"</h2>
<p>President Reagan appointed a commission chaired by William Rogers, a former secretary of state, whose members included Neil Armstrong, the astronaut Sally Ride and the physicist Richard Feynman. At a televised hearing Feynman dropped a piece of O-ring material, squeezed in a small clamp, into a glass of iced water, and showed that it did not spring back. The demonstration took seconds and made the physics plain to anyone watching. It later emerged that the line of inquiry had been steered his way by an Air Force general on the commission, Donald Kutyna, who had in turn been passed the relevant information by Ride.</p>
<p>The commission's report, in June 1986, found the decision to launch "flawed" and criticised NASA's management culture as well as the joint. Feynman insisted on adding his own appendix. He had found that estimates of the probability of losing a shuttle ranged from about one in a hundred among working engineers to one in a hundred thousand among senior management, and he concluded: "For a successful technology, reality must take precedence over public relations, for nature cannot be fooled."</p>

<h2 id="Normalisation">Normalisation of deviance</h2>
<p>The most influential account of the decision came a decade later from a sociologist, Diane Vaughan. In <em>The Challenger Launch Decision</em> she argued that the popular story — managers bowing to schedule pressure and overruling engineers — was true but incomplete. The people involved were not amoral; most followed the rules. The danger had grown through a long series of small, reasonable-seeming decisions, each of which accepted a little more damage on the grounds that the last flight had survived it. She called this the normalisation of deviance: the gradual process by which an anomaly becomes the expected thing, and then the acceptable one.</p>
<p>The concept has spread far beyond spaceflight, into medicine, aviation and industrial safety, because the pattern is general. Systems rarely fail on the first warning. They fail after the warnings have stopped seeming like warnings.</p>

<h2 id="Aftermath">Then it happened again</h2>
<p>The shuttle was grounded for thirty-two months while the booster joints were redesigned, with a third O-ring, a tighter interlocking joint and heaters. Flights resumed in September 1988, and commercial satellites were moved off the shuttle onto expendable rockets.</p>
<p>In February 2003 the shuttle Columbia broke up on re-entry, killing its seven crew. The physical cause was different: a piece of insulating foam that had struck the wing during launch. Foam strikes had been seen on earlier flights and had gradually come to be treated as a maintenance issue. The Columbia Accident Investigation Board, which brought Vaughan in to advise, concluded that the organisational causes of the Challenger accident had never been fixed. Over its whole life the shuttle flew 135 missions and lost two vehicles — a failure rate close to the engineers' estimate, not the managers'.</p>
`,
};
