import type { RewrittenArticle } from "./types";

export const chernobyl: RewrittenArticle = {
  slug: "chernobyl",
  title: "Chernobyl: the night the emergency button made things worse",
  sourceTitle: "Chernobyl disaster",
  dek: "A delayed safety test, a reactor with a flaw its operators had not been told about, and a state that kept quiet for days. The first official account blamed the operators; a later one blamed the reactor.",
  standfirst:
    "In the early hours of 26 April 1986, reactor number 4 at the Chernobyl nuclear power plant in Soviet Ukraine destroyed itself during a test of its own safety systems. The explosion and the graphite fire that followed spread radioactive material across much of Europe. Four decades on, the sequence of events is well understood. What took longer was agreeing whose failure it was — and the answer changed the way the nuclear industry talks about safety.",
  readingMinutes: 8,
  published: "2026-10-06",
  html: `
<h2 id="The_reactor">An unusual kind of reactor</h2>
<p>The Chernobyl plant stood beside the new town of Pripyat in northern Ukraine, about a hundred kilometres north of Kyiv. Its four reactors were of a Soviet type called the RBMK: large, graphite-moderated and cooled by water flowing through more than a thousand separate pressure tubes. The design descended from reactors built to produce plutonium for weapons. It was relatively cheap to build, could be refuelled without shutting down, and had no containment building of the kind standard in the West.</p>
<p>It also had a property that matters for everything that follows. In an RBMK, the cooling water absorbs some of the neutrons that sustain the chain reaction. If the water boils into steam, it absorbs fewer, so the reaction speeds up, which makes more steam. Physicists call this a positive void coefficient. At normal full power other effects dominated and the reactor was stable. At low power, it could become unstable.</p>

<h2 id="The_test">A test that kept being postponed</h2>
<p>The test was meant to answer a safety question. If the plant lost its outside electricity, diesel generators would take the better part of a minute to start the pumps that kept water flowing through the core. Could the still-spinning turbine generate enough power to run the pumps in the gap? The test had been tried at the plant before without a satisfactory result.</p>
<p>It was scheduled for the afternoon of 25 April, with the reactor at reduced power. The regional grid controller asked for the plant to keep supplying electricity, and the test was postponed into the night, to be carried out by a shift that had not been prepared for it. During the reduction in power the output fell much further than intended, to almost nothing, and the core began to fill with xenon, a fission product that absorbs neutrons and suppresses the reaction. To get power back up, the operators withdrew most of the control rods. They reached only a fraction of the planned test power, with far fewer rods in the core than the operating rules allowed.</p>

<h2 id="The_explosion">Forty seconds</h2>
<p>The test began at 1.23 am. As the turbine ran down, the pumps it was feeding slowed, less water flowed through the core, and more of it boiled. Power began to rise. About thirty-six seconds in, someone pressed the button marked AZ-5, which drives every control rod into the core and should shut it down.</p>
<p>The RBMK's control rods had a design flaw. Each rod carried a graphite section at its tip, and when a fully withdrawn rod began to drop, that graphite first pushed water out of the bottom of the channel. For a few seconds, in the lower part of the core, inserting the rods increased the reaction instead of stopping it. The rods also moved slowly, taking around eighteen seconds to go all the way in. In a core already in an unstable state, that brief surge was enough. Power spiked to many times its maximum, fuel shattered, and a steam explosion blew the massive upper shield of the reactor out of place. A second explosion followed seconds later. Burning graphite and fragments of the core were thrown out of the building, and the exposed graphite burned for about ten days.</p>
<p>The flaw was not unknown. A similar effect had been observed at another RBMK plant, Ignalina in Lithuania, in 1983, and the designers were aware of it. The information had not reached operating crews in a form that told them what it meant.</p>

<h2 id="Response">Silence, then evacuation</h2>
<p>Firefighters put out the fires on the roofs of the reactor building that night without knowing what they were standing on; most of the dosimeters at the plant could not read high enough to show the true levels. Two workers died at the plant. Of 134 people later diagnosed with acute radiation sickness, 28 died within months, many of them firefighters and plant staff.</p>
<p>Pripyat, a town of about 49,000, was evacuated about thirty-six hours after the explosion. Residents were told to pack for three days; they never returned. A thirty-kilometre exclusion zone was established, and over the following years more than 300,000 people were resettled from contaminated areas of Ukraine, Belarus and Russia.</p>
<p>The Soviet government said nothing until 28 April, when workers arriving at the Forsmark nuclear plant in Sweden, more than a thousand kilometres away, set off radiation alarms. The Swedes traced the source to the Soviet Union, and that evening a short statement on Soviet television acknowledged an accident. Mikhail Gorbachev later wrote that Chernobyl was a turning point for his policy of openness, and suggested it did more than his own reforms to bring about the end of the Soviet Union.</p>

<h2 id="Blame">Two reports, two culprits</h2>
<p>In August 1986 a Soviet delegation led by the chemist Valery Legasov presented a detailed account to the International Atomic Energy Agency in Vienna. The IAEA's safety advisory group, in its report known as INSAG-1, accepted the core of it: the operators had broken rules and disabled safeguards. The plant's director, chief engineer and the deputy chief engineer who supervised the test were sentenced to ten years in labour camps.</p>
<p>In 1992 the same group published INSAG-7, which revised that judgement substantially. Several of the "violations" turned out not to have been prohibited by the rules in force, or to have been rules whose importance the operators could not have known. The design flaws in the reactor and its control rods were given far more weight. And the report blamed the absence of what INSAG-1 had called a "safety culture" — a term that report introduced — not only at the plant but across the Soviet nuclear establishment. The phrase is now standard in every high-hazard industry.</p>

<h2 id="Health">The toll, and why it is disputed</h2>
<p>Some parts of the health picture are firm. Besides the early deaths, more than six thousand cases of thyroid cancer were diagnosed among people who were children or adolescents in the affected regions in 1986, largely from drinking milk contaminated with radioactive iodine. Most were treated successfully. The longer-term toll from cancers caused by lower doses is much less certain, because those cancers cannot be told apart from the far larger number that would have occurred anyway. Estimates depend on the model used for small doses, and range from about four thousand eventual deaths among the most exposed populations, in a 2005 assessment led by the IAEA and the World Health Organization, to considerably more in studies covering wider areas. The same assessment found that the disruption, relocation and fear caused by the accident were among its largest public-health effects.</p>

<h2 id="Afterlife">The zone</h2>
<p>A concrete and steel shelter was built over the ruined reactor by November 1986, and in 2016 a vast arched structure, the New Safe Confinement, was slid over it. The plant's other three reactors went on generating electricity; the last of them was shut down in 2000. RBMKs elsewhere were modified with faster control rods and other changes, and some still operate in Russia.</p>
<p>Without people, the exclusion zone has filled with animals. Census data show populations of elk, deer, wild boar and wolves comparable to or higher than in nature reserves in the region, which says less about radiation being harmless than about how hard humans are on wildlife. The zone has also been drawn into war: Russian troops occupied the site in the first weeks of the 2022 invasion of Ukraine, and in February 2025 a drone struck the New Safe Confinement, damaging its outer shell.</p>
`,
};
