import type { RewrittenArticle } from "./types";

export const chess: RewrittenArticle = {
  slug: "chess",
  title: "Chess: the modern game is about 500 years old, and it was invented for speed",
  sourceTitle: "Chess",
  dek: "Around 1475 someone gave the queen the run of the board. The older game had been slow enough to bore its own players; the new one produced opening theory, blunders and a draw problem.",
  standfirst:
    "Chess is usually described as ancient, and the board and the pieces are. The game actually played today is not: it dates from a rule change in late fifteenth-century southern Europe that transformed the weakest piece into the strongest and cut the length of a game dramatically. Almost everything characteristic of chess — memorised openings, sharp tactics, the tension between attack and the drawn endgame — follows from that one revision.",
  readingMinutes: 8,
  html: `
<h2 id="The_old_game">The game before the queen</h2>
<p>The ancestor is <em>chaturanga</em>, played in India by roughly the sixth century, which travelled west as Persian <em>shatranj</em> and reached Europe through the Islamic world and Iberia. The board, the eight-by-eight grid, the pawns, the knight's leap and the rook's line are all inherited essentially unchanged.</p>
<p>Two pieces were different, and they were the ones that set the pace. The <em>firzan</em>, ancestor of the queen, moved a single square diagonally. The <em>alfil</em>, ancestor of the bishop, jumped exactly two squares diagonally — which confined each one to eight squares of the board for the entire game, a sixteenth of the surface.</p>
<p>The consequence was a slow game. With no long-range piece other than the rook, positions took a long time to develop contact, and manuals of the period devote much of their attention to <em>mansubat</em>, composed endgame problems, because that is where the interesting material was. Games were frequently decided by reducing an opponent to a bare king rather than by checkmate.</p>
<p>Medieval Europe also inherited a piece its culture had no use for. The <em>firzan</em> was a vizier, a male counsellor; European players renamed it queen, kept its feeble move for several centuries, and eventually did something about the mismatch.</p>

<h2 id="Mad_queen">The rule change</h2>
<p>In the last decades of the fifteenth century, in Spain and Italy, the queen acquired the combined moves of rook and bishop, and the bishop acquired its unlimited diagonal. Pawns gained the two-square first move, with en passant added so the new rule could not be used to slip a pawn past an opposing one, and castling took its modern shape over the following century.</p>
<p>Contemporaries noticed. The new game was called the chess of the lady, in a Spanish poem of about 1475 that is the earliest clear description, and in Italy it was called <em>alla rabiosa</em> — mad, or rabid, chess — because of how fast it now was.</p>
<p>The speed is the point. A single piece could cross the board in one move and attack in two directions, which meant a mistake in the first ten moves could lose the game outright. That is what created the opening as an object of study: under the older rules there was little to memorise, because nothing decisive could happen early.</p>
<p>Lucena's book of 1497 and Damiano's of 1512 are the first printed treatments of the new game, and Ruy López de Segura's of 1561 names an opening still played constantly at the top level. The line of transmission from those books to a modern game is unbroken; the line back from them to <em>shatranj</em> is not.</p>
<p>Why the change happened in that place and period is unsettled, and the coincidence with Isabella of Castile's reign is much remarked on and hard to establish. What is clear is that a game had its central piece rewritten by players who wanted more action, and that the revision spread across Europe within about fifty years because it was better.</p>

<h2 id="The_draw">The problem with a game played well</h2>
<p>Chess has an awkward structural feature: with accurate play by both sides it very often ends in a draw, and the better the players the more often this happens.</p>
<p>At the top of the professional game the draw rate at classical time controls sits well above half, and in some elite events it has run far higher. This is not cowardice. It reflects the fact that White's advantage is real but small, that defensive technique has improved faster than attacking technique, and that computer-assisted preparation lets players steer into positions they already know are safe.</p>
<p>The game is not solved in the mathematical sense and almost certainly cannot be — the number of legal positions is somewhere around 10 to the power of 44, unreachable by any conceivable exhaustive search. But it is solved from the back: complete tablebases exist for every position with seven or fewer pieces, and they contain forced wins running to hundreds of moves that no human would find and no human would recognise as progress while it was happening.</p>
<p>The responses to the draw problem have been format changes rather than rule changes. Shorter time controls produce more decisive games because they produce more mistakes. Armageddon tiebreaks assign unequal time and give Black draw odds. Scoring that awards three points for a win has been trialled. Fischer random, or chess960, shuffles the back rank into one of 960 starting arrangements and thereby deletes opening preparation entirely; it has a following and a world championship, and it has not displaced the standard game.</p>

<h2 id="Engines">What happened when the machines arrived</h2>
<p>Deep Blue beat Garry Kasparov over six games in 1997, and the popular reading — that chess was finished as a human pursuit — turned out to be exactly wrong.</p>
<p>Deep Blue worked by brute force plus a hand-tuned evaluation function written with grandmaster help: search enormous numbers of positions, score the leaves, back the values up. Its successors running on ordinary hardware surpassed it within a decade, and the strongest conventional engine, Stockfish, was far beyond any human long before the next shift arrived.</p>
<p>That shift was AlphaZero in 2017, which learned from self-play knowing nothing but the rules, using a neural network to evaluate positions and a guided search rather than exhaustive enumeration. Its games startled strong players: it surrendered material for long-term positional pressure in ways engines had been specifically tuned not to, and it revived opening ideas human theory had discarded. The neural evaluation approach was then absorbed into the traditional engines, and the strongest programs today are hybrids of the two methods.</p>
<p>The effect on human chess has been rising standards rather than collapsing interest. Players train against engines from childhood, understand positions earlier generations found obscure, and reach master strength younger. What died was a particular kind of authority — analysis published by a grandmaster can now be checked by anyone in seconds — and what grew was the audience, because a broadcast game can carry a live evaluation bar that a novice can read.</p>
<p>The unambiguous casualty is trust. A phone in a pocket plays better than the world champion, which makes cheating in over-the-board play both trivially possible and extremely hard to prove, and the sport has spent recent years arguing about detection methods, metal detectors, broadcast delays and accusations that cannot be settled. Online play has the same problem at vastly greater scale, and the major sites detect it statistically, by comparing a player's moves against engine choices — which means the accusation is probabilistic and the accused has nothing concrete to answer.</p>

<h2 id="Why_it_persists">Why the game survives being understood</h2>
<p>It is worth asking why a game a machine plays perfectly well is still played by hundreds of millions of people, when the same never held for competitive mental arithmetic.</p>
<p>Part of the answer is that chess was never really about finding the best move. It is about finding a good move under a clock, against someone who is also trying, while tired, having prepared the wrong thing. The engine settles what the truth is and leaves the entire competitive substance untouched.</p>
<p>Part of it is that the game's difficulty is well matched to human working memory. The branching factor is around thirty-five; deep calculation is possible for a handful of moves and impossible beyond that, and the gap is filled with pattern recognition. This is why the classic experiments found that masters remember real positions far better than novices and remember randomly scattered pieces no better at all. What they have is not memory but a vocabulary of structures, estimated in the tens of thousands, acquired over roughly a decade.</p>
<p>And part of it is that the 1475 revision did its job. A game in which a piece can cross the board in one move is a game where a lapse of attention is punished immediately, which is unpleasant, and which is precisely the property that makes it hold.</p>
`,
};
