import type { RewrittenArticle } from "./types";

export const circadianRhythms: RewrittenArticle = {
  slug: "circadian-rhythms",
  title: "Circadian rhythms: the body runs a clock that keeps the wrong time on purpose",
  sourceTitle: "Circadian rhythm",
  dek: "Isolated from daylight, humans settle into a day slightly longer than 24 hours. Morning light drags it back every day, which is why the reset matters more than the clock.",
  standfirst:
    "Almost every organism on the planet carries an internal oscillator with a period of roughly a day, built from a loop of genes that switch themselves off and take about twenty-four hours to do it. In humans the free-running period is a little over twenty-four hours, so the clock must be corrected daily, and it is corrected by light through a photoreceptor system separate from the one used for vision. The health consequences of getting that correction wrong are large and, in shift workers, well documented.",
  readingMinutes: 7,
  html: `
<h2 id="Free_running">The experiment of living underground</h2>
<p>The question of whether daily rhythms are driven by the environment or generated internally was settled by removing the environment.</p>
<p>The plant version came first, in 1729, when Jean-Jacques d'Ortous de Mairan noticed that a mimosa plant kept in constant darkness continued to open and close its leaves on a daily cycle. The rhythm was not a response to light; it persisted without it.</p>
<p>The human version is more famous. Michel Siffre spent two months in a glacial cave in 1962 with no clock and no daylight, and emerged convinced that considerably less time had passed than actually had. Subsequent isolation studies, notably the German bunker experiments run by Jürgen Aschoff, established the pattern: without time cues, humans free-run on a cycle averaging slightly over twenty-four hours, so the sleep-wake cycle drifts later day by day.</p>
<p>Early estimates of that period were inflated, because subjects in the older studies were allowed to control their own lighting and their evening lamp use pushed the clock later. Forced-desynchrony protocols, which distribute light exposure evenly across an imposed schedule the clock cannot follow, put the intrinsic human period at close to 24.2 hours, with individual variation of a few tenths.</p>
<p>Twelve minutes a day sounds trivial and is not. Uncorrected it amounts to an hour and a half a week, and the entire architecture of light-based entrainment exists to cancel it.</p>

<h2 id="Molecular">A clock made of a feedback loop</h2>
<p>The mechanism is a transcription-translation feedback loop, and its outline is the same from flies to mammals.</p>
<p>A pair of activator proteins bind the DNA and switch on a set of clock genes. Those genes' products accumulate in the cytoplasm, are modified and delayed, and eventually enter the nucleus, where they shut down their own activators. Production stops, the existing proteins are degraded, the inhibition lifts, and the cycle restarts. The period is set by the delays — how fast the proteins accumulate, how heavily they are tagged for degradation, how long transport takes.</p>
<p>The genetics were worked out largely in fruit flies. Seymour Benzer and Ronald Konopka identified mutants in 1971 with short, long and absent rhythms, all mapping to a single gene they called <em>period</em>. Jeffrey Hall, Michael Rosbash and Michael Young cloned it and established the feedback loop, work recognised with the Nobel Prize in 2017.</p>
<p>The rate-limiting step in mammals is largely phosphorylation, which determines how long the inhibitor survives. This is why mutations in the relevant kinase or its targets shift a person's timing wholesale: familial advanced sleep phase syndrome, in which people fall asleep in the early evening and wake around four, was traced to exactly such a mutation, and it is inherited straightforwardly.</p>
<p>The clock is not confined to the brain. Nearly every tissue runs its own oscillator, and a substantial fraction of the genome is expressed rhythmically in at least one tissue. The master clock in the suprachiasmatic nucleus of the hypothalamus — a structure of some tens of thousands of neurons — is a conductor rather than the source, keeping peripheral clocks in phase with each other and with the outside.</p>

<h2 id="Light">The photoreceptor nobody expected</h2>
<p>Entrainment happens through light, and the discovery of how is one of the better recent surprises in sensory biology.</p>
<p>Mice engineered to lack both rods and cones — completely blind by any visual measure — still entrained normally to a light-dark cycle. Something in the eye was detecting light and it was not the visual photoreceptors.</p>
<p>The answer was a small population of retinal ganglion cells containing melanopsin, which are directly photosensitive. They respond sluggishly, integrate over long periods, and are most sensitive to short-wavelength blue light around 480 nanometres. They project not to the visual cortex but to the suprachiasmatic nucleus and to regions controlling pupil size and alertness. Some people who are cortically blind retain normal entrainment through this pathway, and totally blind people who have lost their eyes generally do not, drifting free at their intrinsic period.</p>
<p>The response depends heavily on timing. Light in the early morning advances the clock, making the next day earlier; light in the late evening delays it. There is a region in the middle of the day where light has relatively little phase effect. This is summarised in a phase-response curve, and it is the practical basis of everything from light-box treatment for seasonal affective disorder to advice about jet lag.</p>
<p>The evening-light problem follows directly. Indoor lighting and screens supply illumination at exactly the point in the curve where it pushes the clock later, at intensities well below daylight but well above what the system evolved to see after sunset. The measured effect on melatonin onset is real; the size of the effect from a phone at ordinary brightness is more modest than popular coverage suggests, and the larger factor is generally total evening light exposure and the fact that the alternative activity was sleep.</p>

<h2 id="Chronotype">Larks, owls, and the schedule problem</h2>
<p>Individuals differ substantially in their timing, and chronotype is substantially heritable, with variants in clock genes accounting for part of it.</p>
<p>It also shifts predictably with age. Chronotype moves later through adolescence, peaks in the late teens, and moves earlier thereafter — a pattern found across cultures and also in other mammals, which argues for a biological rather than cultural cause. Teenagers going to bed late are, on average, doing what their physiology directs.</p>
<p>This collides with school start times, and the collision has been measured. Studies of districts that delayed secondary school start times report increased sleep duration, improved attendance and, in several analyses, reduced crash rates among teenage drivers. It is one of the clearer policy findings in the field and it propagates slowly, because the constraint is bus scheduling rather than evidence.</p>
<p>The general term for the mismatch between biological and social timing is social jet lag, measured as the difference between a person's mid-sleep on free days and on work days. It is substantial in a large fraction of the population and is associated with poorer metabolic and mental health outcomes, though disentangling cause from correlation is difficult.</p>

<h2 id="Consequences">Shift work, and the cost of eating at night</h2>
<p>The strongest evidence for the clock's importance comes from people whose schedules break it permanently.</p>
<p>Long-term night shift work is associated with elevated rates of cardiovascular disease, metabolic syndrome and type 2 diabetes, and the International Agency for Research on Cancer classifies shift work involving circadian disruption as probably carcinogenic to humans. The classification is based on limited human evidence, mainly breast cancer studies, plus stronger animal evidence, and it has been reviewed and retained.</p>
<p>The mechanism most cleanly demonstrated concerns metabolism. Glucose tolerance varies across the day: the same meal produces a substantially larger glucose excursion at night than in the morning, because insulin sensitivity and pancreatic responsiveness are themselves rhythmic. Laboratory studies that misalign the behavioural cycle from the circadian one produce measurable insulin resistance and raised blood pressure within days, in healthy young subjects.</p>
<p>The same principle appears in medicine as chronotherapy. Drug metabolism, blood pressure, immune activity and cell division all vary across the day, and dosing time affects both efficacy and toxicity for a number of agents. The clearest established example is that vaccination timing modestly affects antibody response; the broader programme of timing chemotherapy to circadian phase has shown promise and has proved difficult to implement, partly because individual phase must be measured rather than assumed.</p>
<p>The practical summary is unglamorous and well supported: the reset is what matters. Bright light in the morning, dim light in the evening, and a consistent schedule do more for circadian health than anything taken in a capsule, and the reason is simply that a 24.2-hour clock needs correcting every single day.</p>
`,
};
