import type { RewrittenArticle } from "./types";

export const cognitiveBias: RewrittenArticle = {
  slug: "cognitive-bias",
  title: "Cognitive bias: the errors are systematic, which is what makes them interesting",
  sourceTitle: "Cognitive bias",
  dek: "Random mistakes cancel out. These do not — everyone makes the same ones in the same direction, including the people who study them.",
  standfirst:
    "If human judgment simply failed at random there would be nothing to study; errors would scatter and average out. What Kahneman and Tversky demonstrated is that judgment fails in predictable directions, that the deviations are large, and that they persist after they are explained to you. The reason is that the shortcuts producing them are usually the right shortcuts, and the failures are the price of a system that mostly works.",
  readingMinutes: 8,
  html: `
<h2 id="Heuristics">Shortcuts that usually work</h2>
<p>The framing that made the field productive was not that people are irrational. It was that people use heuristics — fast rules that substitute an easy question for a hard one — and that these are efficient and occasionally catastrophic in identifiable ways.</p>
<p>The <strong>availability</strong> heuristic estimates frequency by how easily examples come to mind. This is a decent proxy in a world where common things are encountered more often, and it fails badly when retrieval is driven by something other than frequency. People overestimate deaths from plane crashes, shark attacks and terrorism, and underestimate deaths from diabetes and stroke, in proportion to how vividly each is reported. The bias is not stupidity; it is a sensible rule applied to a media environment it did not evolve in.</p>
<p>The <strong>representativeness</strong> heuristic judges probability by resemblance to a stereotype, ignoring how common the categories are. Told about a shy, tidy man who likes order, people judge him more likely a librarian than a salesman — although salesmen outnumber librarians so heavily that the base rate swamps the resemblance. Base rate neglect is the single most consequential reasoning error in medicine, where a highly accurate test for a rare condition still yields mostly false positives, and where practising clinicians get the question wrong at rates that have been measured repeatedly.</p>
<p><strong>Anchoring</strong> is the most robust and the least explicable. An arbitrary number presented before an estimate drags the estimate toward it, even when the number is transparently irrelevant and even when subjects are warned. In the original demonstration, a wheel of fortune was spun in front of participants before they estimated the percentage of African countries in the UN, and the wheel's number moved their answers substantially. It has been shown with judges and sentencing recommendations, using dice.</p>

<h2 id="Prospect_theory">Losses and gains are not symmetric</h2>
<p>The most economically consequential finding is that people do not evaluate outcomes in absolute terms but as changes from a reference point, and that losses hurt roughly twice as much as equivalent gains please.</p>
<p>This produces a specific and reproducible pattern: risk aversion when choosing among gains, and risk seeking when choosing among losses. Offered a certain gain or a gamble with the same expected value, most take the certain gain. Offered a certain loss or a gamble with the same expected loss, most take the gamble. The two preferences are inconsistent, and which one appears depends only on how the identical situation is described.</p>
<p>The classic demonstration is a public health scenario presented two ways. A programme that saves 200 of 600 people is chosen over a gamble with the same expectation; a programme in which 400 of 600 die is rejected in favour of the identical gamble. The numbers are the same. The framing does all the work, and it works on physicians as reliably as on undergraduates.</p>
<p>The <strong>endowment effect</strong> follows directly. People demand substantially more to give up an object than they would have paid to acquire it, because losing it is coded as a loss. Give half a room mugs and the mug owners' asking prices come in at roughly double what the non-owners will pay. This has practical consequences for negotiation, for default options, and for why free trials convert.</p>
<p><strong>Sunk cost</strong> is a related failure: continuing an unpromising project because of what has already been spent, although only future costs and benefits are decision-relevant. The mechanism is that abandonment converts an ambiguous situation into a definite loss.</p>

<h2 id="Confirmation">The one that does the most damage</h2>
<p>Confirmation bias is the tendency to seek, notice, and remember information consistent with what you already believe, and to subject contrary information to far harsher scrutiny.</p>
<p>Wason's selection task showed the pattern in its purest form: given a rule to test, the overwhelming majority of people look for cases that would confirm it and fail to check the case that could falsify it. The failure rate on the abstract version is around ninety per cent, and it drops sharply when the same logical problem is framed as detecting a cheat — which suggests the machinery is tuned for social reasoning rather than for logic.</p>
<p>The more troubling version is asymmetric scrutiny. Presented with studies supporting and opposing their position, people on both sides rate the supporting study as better conducted and pick apart the methodology of the other. Both sides then report being more confident than before. Identical evidence moves opposed groups further apart.</p>
<p>The reason this is the most damaging bias is that it is self-sealing: it operates on the evidence you would use to correct it.</p>
<p>Motivated reasoning is the same phenomenon with the driver named — reasoning toward a conclusion one wants while feeling as though one is reasoning from evidence. Numeracy does not protect against it. On politically loaded data-interpretation tasks, more numerate participants show <em>larger</em> partisan gaps, because the skill is deployed in service of the desired answer.</p>

<h2 id="Overconfidence">Knowing less than you think</h2>
<p>People asked for ranges they are ninety per cent confident contain the true value produce ranges containing it perhaps half the time. This has been measured across professions and is remarkably consistent.</p>
<p><strong>Hindsight bias</strong> makes it worse by concealing the record. Once an outcome is known, prior estimates are misremembered as having been closer to it, so the experience of being surprised is edited out and the lesson is not learned. The only reliable defence is writing predictions down before the event, which is why forecasting research insists on it and why so few institutions do it.</p>
<p>The <strong>Dunning–Kruger</strong> pattern — that the least competent overestimate themselves most — is real but is the most over-extended finding in the field. The original data show that nearly everyone's self-assessment regresses toward average, that top performers underestimate themselves, and that part of the effect is a statistical artefact of the measurement. It is not a licence to diagnose strangers.</p>
<p>The <strong>planning fallacy</strong> is the most reliably useful. Projects take longer than predicted, essentially always, and forecasters do not correct even after decades of the same experience, because each new project is imagined as a specific sequence of steps that could go right. The fix, reference class forecasting, is to ignore the inside story and ask how long comparable projects actually took. It works, and it is resisted, because the outside view feels like it ignores what is special about this case.</p>

<h2 id="Debiasing">Can you fix it</h2>
<p>Mostly not by knowing about it. Anchoring, framing and hindsight effects persist in subjects who have just had them explained. Awareness produces the bias blind spot instead — a well-documented tendency to recognise these errors in others while believing one's own judgment is unaffected.</p>
<p>What does work is structural, and the pattern is consistent: change the procedure, not the person.</p>
<p>Checklists remove the judgment from steps that do not need it. Blind assessment removes the information that would bias it. Structured interviews with fixed questions and pre-set scoring outperform unstructured ones substantially, because unstructured interviews mostly measure the interviewer's first impression. Pre-registration removes the flexibility that motivated reasoning exploits. Reference class forecasting replaces intuition with a base rate. The premortem — imagining the project has failed and writing the explanation — surfaces objections that group dynamics otherwise suppress.</p>
<p>Simple statistical models routinely outperform expert clinical judgment on prediction tasks, a finding established in the 1950s, replicated exhaustively, and still resented. Experts given the model's output and permission to override it perform worse than the model alone.</p>

<h2 id="Caveats">Two cautions</h2>
<p>The field has been touched by the replication crisis, unavoidably, since it is largely an experimental psychology of small effects. Social priming has collapsed almost entirely. Ego depletion did not survive. Several textbook results are now regarded as unreliable, and the honest position is that the core judgment-and-decision findings — anchoring, framing, loss aversion, base rate neglect — have held up well under replication while a periphery of more spectacular results has not.</p>
<p>The second caution is about the framing itself. Gerd Gigerenzer's long-standing objection is that calling these errors presupposes that formal probability is the right standard for a mind operating under time pressure with incomplete information, and that many heuristics are in fact well adapted — sometimes outperforming complex models in real environments. He has also shown that several classic errors largely disappear when problems are stated in natural frequencies rather than probabilities: tell a doctor that 10 out of every 1,000 women have the disease rather than that the prevalence is one per cent, and the reasoning improves dramatically.</p>
<p>That is a useful corrective and it does not dissolve the field. It relocates part of the problem from the mind to the format of the question, which is a more actionable place for it to be.</p>
`,
};
