import type { RewrittenArticle } from "./types";

export const consciousness: RewrittenArticle = {
  slug: "consciousness",
  title: "Consciousness: the one fact you cannot doubt and cannot explain",
  sourceTitle: "Consciousness",
  dek: "Science can say which brain activity accompanies experience. It has no account of why any of it is experienced at all.",
  standfirst:
    "Every other scientific problem is about something observable from the outside. Consciousness is the exception: the data are available to exactly one observer, cannot be shared, and cannot be checked. That is not a temporary shortage of instruments. It is a structural feature of the thing being studied, and it is why the field's central question has not moved in three hundred years.",
  readingMinutes: 8,
  html: `
<h2 id="Two_problems,_not_one">Two problems, not one</h2>
<p>The most useful distinction in the field was drawn by David Chalmers in 1995, and it separates work that is difficult from work that may be impossible.</p>
<p>The <strong>easy problems</strong> are easy only by comparison. How does the brain integrate information from different senses? How does it direct attention, control behaviour, report on its own states, distinguish waking from sleep? These are enormously hard research programmes, but nobody doubts what a solution would look like: a mechanism, described in terms of neurons and computation, that performs the function.</p>
<p>The <strong>hard problem</strong> is why any of that is accompanied by experience. Why is there something it is like to see red, rather than the visual system simply processing wavelength data and issuing behaviour? A complete functional account of the brain would explain every observable thing you do, including your insistence that you are conscious — and would apparently leave the experience itself untouched, as an addition the explanation did not require.</p>
<p>Some philosophers regard the hard problem as a confusion that will dissolve once the easy problems are solved, in the way that the mystery of life dissolved once biochemistry explained metabolism and reproduction. Others regard it as the only real question. The disagreement is not about evidence; both camps have the same facts.</p>

<h2 id="What_it_is_like">What it is like</h2>
<p>Thomas Nagel sharpened the issue in 1974 by asking what it is like to be a bat. Bats navigate by echolocation, a sense we do not have, and Nagel's point was not that we cannot imagine it but something stronger: even complete knowledge of bat neurophysiology would not tell us how the world seems from inside a bat. Objective description appears to leave something out, and what it leaves out is the only thing we were asking about.</p>
<p>Frank Jackson made the same case with a thought experiment about Mary, a scientist who has lived her whole life in a black-and-white room and knows every physical fact about colour vision — every wavelength, every neuron, every process. She is released and sees a red tomato. Does she learn anything? The intuition that she does suggests physical facts do not exhaust the facts. The counter-argument is that she gains an ability rather than a fact, or a new way of representing something she already knew. The debate has run for forty years without resolution, which is itself informative.</p>

<h2 id="What_the_brain_actually_does">What the brain actually does</h2>
<p>Set the philosophy aside and neuroscience has made real progress on the easy problems, which turn out to be less easy and more surprising than expected.</p>
<p>The search for neural correlates of consciousness — the minimum brain activity sufficient for a given experience — has narrowed considerably. Consciousness does not live in one place; it appears to require widespread, coordinated activity across the cortex rather than any single region. Damage to the brainstem or to certain thalamic structures abolishes it entirely, while enormous cortical damage can leave it altered but present. The cerebellum contains most of the brain's neurons and appears to contribute nothing to experience, which usefully rules out the idea that consciousness is simply what a lot of neurons produce.</p>
<p>Two families of theory dominate. <strong>Global workspace</strong> accounts hold that most processing is unconscious and specialised, and that consciousness is what happens when information is broadcast widely enough to become available to many systems at once — memory, language, planning. <strong>Integrated information theory</strong> proposes that consciousness is a mathematical property of a system's causal structure, quantifiable in principle, and present wherever information is integrated in the right way. The first is easier to test and says less about why experience occurs; the second addresses the hard problem directly and implies consciousness is far more widespread than intuition allows, which many take as a reductio.</p>

<h2 id="How_much_of_you_is_not_conscious">How much of you is not conscious</h2>
<p>The most disorienting findings concern how little of mental life is available to introspection.</p>
<p>Split-brain patients, whose hemispheres have been surgically disconnected to control epilepsy, can respond to information presented to the right hemisphere while the left hemisphere — which controls speech — sincerely denies seeing anything, and then confabulates a reason for the behaviour. Blindsight patients with damage to visual cortex report seeing nothing yet locate objects far above chance, guessing accurately at things they insist they cannot see.</p>
<p>Healthy brains do the same thing more quietly. Choice blindness experiments swap the option a subject selected and find that most people fail to notice and proceed to explain, in detail, why they preferred the option they rejected. Benjamin Libet's much-argued experiments found brain activity preceding the reported moment of deciding to move — a result whose implications for free will are disputed on almost every methodological ground, but which at minimum shows that the felt timing of decisions is not reliable.</p>
<p>The picture that emerges is that the conscious self is not the system's control centre but something closer to its press office: informed after the fact, and reliably able to produce an account whether or not it has the information.</p>

<h2 id="Where_it_starts_and_stops">Where it starts and stops</h2>
<p>The practical stakes are considerable, because the question of who is conscious determines who is owed moral consideration.</p>
<p>In medicine, distinguishing a vegetative state from minimal awareness is a life-and-death judgement made largely on behaviour — and imaging studies have found patients diagnosed as vegetative who could modulate their brain activity on command, imagining playing tennis when asked, in effect answering questions with no ability to move. Some proportion of people believed unconscious are not.</p>
<p>In animals the question is harder and less often asked honestly. Mammals and birds show most of the markers we take as evidence in humans. Octopuses have a nervous system built on an entirely separate evolutionary path, distributed largely into their arms, and behave in ways that make attributing experience to them difficult to avoid and impossible to verify. Insects are genuinely open. There is no test, and the absence of one has generally been resolved in whichever direction was convenient.</p>
<p>Machines make the problem acute. A system that produces fluent reports about its inner states is, by construction, doing the one thing we treat as evidence of an inner life — which means our only method fails precisely when it is most needed. The uncomfortable conclusion is that we do not have a way of detecting consciousness at all. We have a way of recognising things that resemble us, and we have been extending the courtesy on that basis for as long as the question has existed.</p>
`,
};
