import type { RewrittenArticle } from "./types";

export const domes: RewrittenArticle = {
  slug: "domes",
  title: "Domes: rotating an arch invents a new force, and it splits the building at the base",
  sourceTitle: "Dome",
  dek: "A dome is not simply an arch spun around. The spinning creates hoop stresses, which hold the top together and tear the bottom apart.",
  standfirst:
    "The usual description of a dome as an arch rotated about its axis is half right and misses the interesting half. Because the material forms continuous rings as well as vertical arcs, a dome carries force in two directions at once. Near the crown the rings are squeezed and the structure is exceptionally stable; below roughly the halfway point the rings are stretched, and masonry cannot be stretched. Every great masonry dome is an answer to that problem, and the answers are visible from outside if you know what to look for.",
  readingMinutes: 7,
  html: `
<h2 id="Hoop">The force that only exists because it is round</h2>
<p>Consider a slice of a dome running from crown to base — that is an arch, and it behaves like one. Now consider a horizontal ring cut through the dome at some height. That ring is a structural element in its own right, and its behaviour changes with height.</p>
<p>Near the top, the rings are in compression: the surface is curving inward in both directions, and the rings squeeze together. This is why a masonry dome can have a hole at its apex without collapsing — the oculus of the Pantheon is not a weakness but sits in the region where the material is being pressed inward from all sides, and where a compression ring can be formed around the opening.</p>
<p>Below about fifty degrees from the crown, the geometry reverses. The rings must expand to accommodate the load spreading outward, and expansion means tension.</p>
<p>Masonry has almost no tensile strength, so what actually happens is that the dome cracks. Meridional cracks — running vertically from the base upward — are the normal, expected condition of essentially every large masonry dome, and once they have formed the dome is no longer a shell. It has become a set of independent arch segments leaning on each other, each pushing outward at its foot.</p>
<p>The Pantheon has these cracks. St Peter's had them, and the resulting eighteenth-century investigation is a landmark: the mathematicians Le Seur, Jacquier and Boscovich analysed the dome in 1743 using the emerging principles of statics, concluded it needed additional restraint, and iron chains were added. It is arguably the first time a major structure was diagnosed by calculation rather than by judgement, and the architects of the day were affronted by the intrusion.</p>

<h2 id="Chains">Tying the bottom together</h2>
<p>The direct answer to hoop tension is to supply something that can take it. Iron or steel chains embedded at the base of a dome hold the ring closed and absorb the outward push.</p>
<p>Brunelleschi built tension rings into the dome of Florence Cathedral from the outset, using sandstone blocks joined with iron cramps and timber rings, though how much of the restraint they actually provide has been debated by modern analysts. Chains were added to the Pantheon's supporting rotunda in later centuries, to St Peter's in 1743, and to numerous Ottoman domes.</p>
<p>The alternative is mass. Load the base of the dome heavily enough and the combined force of dome thrust and dead weight points steeply downward, staying within the supporting masonry. This is why so many domes sit under a thick drum, an attic storey, or a ring of stone that appears to be decoration and functions as ballast. The stepped rings around the base of the Pantheon's dome, visible from outside and invisible from inside, are precisely this.</p>
<p>A third route is buttressing: half-domes, apses and heavy piers arranged around the base to catch the thrust. Hagia Sophia does this with semi-domes on two sides, and the arrangement is instructive because it did not initially work. The original dome, completed in 537, was shallower and pushed harder; it partially collapsed after earthquakes in 558, and the replacement was built steeper and higher, which reduced the thrust. Further partial collapses and repairs followed over the centuries, and the structure visible today is a composite of several campaigns with buttresses added over more than a millennium.</p>

<h2 id="Pantheon">Making the material lighter as it rises</h2>
<p>The Pantheon's dome, completed around 126 AD, remains the largest unreinforced concrete dome in the world, and it has stood for nineteen centuries because its builders solved the weight problem rather than the tension problem.</p>
<p>Roman concrete was mixed with different aggregates at different heights. The lower structure uses dense material — travertine and tuff — and the aggregate becomes progressively lighter with height, ending in pumice near the crown. The dome's density at the top is substantially below that at the base, which reduces both the load and the thrust exactly where reduction is most valuable.</p>
<p>The thickness tapers too, from several metres at the springing to well under a metre at the oculus, and the coffering carved into the underside removes further material from a region where it contributes little, while providing a lattice of thicker ribs. The coffers are usually read as ornament and are a weight-saving device that happens to look good.</p>
<p>The oculus, nearly nine metres across and open to the sky, means the dome has no crown at all. This is structurally sound for the reason given above, and it also removes the heaviest, least useful material from the top of the structure.</p>
<p>Recent materials research has added a mechanism for the concrete's longevity: lime clasts in Roman concrete appear to enable self-healing, dissolving and recrystallising to seal cracks when water penetrates. That is a durability finding rather than a structural one, and it addresses the separate question of why the material has not degraded.</p>

<h2 id="Brunelleschi">Building without falsework</h2>
<p>Florence Cathedral was left with an octagonal opening some forty-two metres across, awaiting a dome nobody knew how to build. The conventional method required timber centring spanning the whole void, and no sufficient timber structure was thought feasible at that span and height.</p>
<p>Filippo Brunelleschi won the 1418 competition with a proposal to build it without centring, and the details of how he did it are still argued over, since he documented little, apparently deliberately.</p>
<p>The essential elements are known. The dome is double-shelled — an inner structural shell and a lighter outer one, connected by ribs — which reduces weight and provides stiffness far more efficiently than a single thick shell, besides creating the walkway between them. It is built on a pointed profile rather than a hemisphere, which reduces hoop tension because the surface curves more sharply and directs thrust more steeply downward. And the brickwork is laid in a herringbone pattern, in which courses of bricks set on edge at intervals interlock the horizontal courses, which is generally understood to have kept each incomplete ring stable while the mortar cured.</p>
<p>The underlying principle is that each completed horizontal ring is self-supporting in compression, so the dome can be built ring by ring, each one closing before the next begins, with no support from below. It works only because the rings are in compression, which is only true above a certain steepness — so the geometry and the construction method are the same decision.</p>
<p>Brunelleschi also designed the hoisting machinery, including a reversible-gear ox-driven hoist, and received one of the earliest known patents for a transport barge. The dome was completed in 1436 and remains the largest masonry dome ever built.</p>

<h2 id="Modern">Shells, geodesics and what changed</h2>
<p>Reinforced concrete removes the tension constraint, and thin concrete shells in the twentieth century achieved spans with a thickness proportionally less than an eggshell's. Félix Candela's hyperbolic paraboloid roofs in Mexico and Heinz Isler's shells in Switzerland, several of them designed by hanging fabric and freezing or inverting the result, are direct descendants of Hooke's chain applied in two dimensions.</p>
<p>Shells fell out of favour not because they were inefficient but because they were labour-intensive: the formwork is complex and curved, and in economies where labour costs more than material the savings vanish. The efficiency argument was won and the accounting argument was lost.</p>
<p>The geodesic dome, popularised by Buckminster Fuller from the late 1940s, works on a different principle entirely — a triangulated network of struts in which loads are carried axially through the members rather than through a continuous surface. It is exceptionally efficient in material and structurally sound, and its historical difficulty was waterproofing, since a surface made of many triangular facets has a great many joints, all of which are potential leaks.</p>
<p>The modern long-span roof is generally neither a shell nor a dome but a steel space frame or a cable-supported membrane, because tension is now the cheap way to carry load, and the whole logic that produced the dome — that the material must never be pulled — no longer applies.</p>
`,
};
