import type { RewrittenArticle } from "./types";

export const germTheory: RewrittenArticle = {
  slug: "germ-theory",
  title: "Germ theory: the man with the evidence was driven out of the profession",
  sourceTitle: "Germ theory of disease",
  dek: "Semmelweis cut deaths from one in six to one in fifty and was dismissed, ridiculed, and died in an asylum.",
  standfirst:
    "Germ theory is the single most consequential idea in the history of medicine, and its adoption is a case study in how evidence fails to persuade. The decisive demonstration came in 1847 from a physician who could show a tenfold reduction in mortality and could not explain the mechanism. He was rejected — partly because his explanation was incomplete, and substantially because his finding accused his colleagues of killing their patients.",
  readingMinutes: 8,
  html: `
<h2 id="Miasma">What it replaced</h2>
<p>The dominant theory held that disease arose from miasma — bad air, generated by rotting organic matter, recognisable by its smell.</p>
<p>It is easy to mock and it was not stupid. It fitted a great deal of the evidence available. Disease genuinely was concentrated in filthy, crowded, foul-smelling districts. Marshes genuinely did produce fever, and the name malaria records the theory. Cleaning up a stinking area genuinely did reduce illness.</p>
<p>Miasma theory also produced real public health achievements: the sanitary movement drained swamps, removed refuse, built sewers, and improved ventilation, and those measures saved a great many lives for reasons the theory got wrong.</p>
<p>The competing idea — that disease was caused by living organisms too small to see — was old. Fracastoro proposed transmissible seeds of disease in 1546. Leeuwenhoek saw microorganisms in the 1670s. The gap was that nobody could connect a specific organism to a specific disease, and correlation with filth was equally well explained by the smell.</p>

<h2 id="Semmelweis">The obstetric wards</h2>
<p>Ignaz Semmelweis worked at the Vienna General Hospital, which ran two maternity clinics. The first was staffed by physicians and medical students; the second by midwives. Women were admitted on alternating days.</p>
<p>Maternal mortality from puerperal fever in the first clinic ran around 10 per cent and in some months far higher. In the second it was around 4 per cent. The difference was public knowledge — women begged to be admitted to the midwives' clinic, and some gave birth in the street rather than enter the first, which Semmelweis noted had better outcomes than the ward itself.</p>
<p>He eliminated explanations systematically. Overcrowding, climate and diet were identical. Position during delivery differed and changing it did nothing. Religious practices in the ward were altered with no effect.</p>
<p>The answer came from a death. His colleague Jakob Kolletschka was cut with a student's scalpel during an autopsy and died of an illness whose pathology matched puerperal fever exactly.</p>
<p>The physicians and students performed autopsies each morning and then examined labouring women, with a rinse in plain water between. The midwives did no autopsies. Semmelweis concluded that something he called cadaverous particles was being carried on the hands.</p>
<p>He instituted handwashing in chlorinated lime — chosen because it removed the smell of the dissecting room, which is a miasmatic reason producing a correct procedure. Mortality in the first clinic fell to around 1 to 2 per cent within months, matching and at times bettering the midwives.</p>

<h2 id="Rejection">Why it was rejected</h2>
<p>The result did not persuade. Semmelweis's contract was not renewed, he left Vienna, and his protocol lapsed after his departure. He spent years writing increasingly furious open letters accusing obstetricians of being murderers, was committed to an asylum in 1865, and died there at 47 — from an infected wound sustained in a beating by the guards, which is an ending too neat to be invented.</p>
<p>The reasons for the rejection are worth separating, because the story is often told as pure obstinacy and it was not only that.</p>
<p>He had no mechanism. Cadaverous particles explained nothing about what the particles were or how they acted, and the profession was entitled to want more than a correlation.</p>
<p>He published badly and late. His book appeared fourteen years after the finding, was disorganised, and its tone by then was openly abusive.</p>
<p>His results did not always replicate cleanly, partly because others implemented the protocol inconsistently.</p>
<p>And the finding was an accusation. Accepting it meant accepting that respected physicians had killed thousands of women with their own hands. Oliver Wendell Holmes had reached a similar conclusion in Boston in 1843 and met comparable resistance, including a colleague's response that he preferred to attribute the deaths to providence rather than to physicians.</p>
<p>The reflex now has a name — the Semmelweis reflex, for the rejection of evidence that contradicts an established position — though it is invoked far more often by people whose evidence is not remotely as good as his.</p>

<h2 id="Pasteur">Pasteur supplies the mechanism</h2>
<p>What germ theory needed was proof that microorganisms cause specific processes, and Louis Pasteur provided it from an unexpected direction: the wine and beer industry.</p>
<p>Fermentation was widely held to be a purely chemical decomposition. Pasteur showed in the 1850s that it is carried out by living yeast, and that spoilage is caused by contaminating organisms. Heating to a controlled temperature kills them without ruining the product, which is pasteurisation.</p>
<p>He then attacked spontaneous generation — the belief that microorganisms arise from non-living matter — with the swan-neck flask experiment of 1859. Broth was boiled in a flask with a long S-shaped neck open to the air. Air could enter freely; dust could not, being trapped in the bend. The broth stayed sterile indefinitely. Tip the flask so the broth touched the dust in the neck, and it spoiled within days.</p>
<p>This was decisive because it controlled for the standard objection that boiling destroyed some vital principle in the air. The air was there; only the particles were excluded.</p>
<p>Some of the original flasks remain sterile in Paris more than 160 years later.</p>

<h2 id="Koch">Koch makes it rigorous</h2>
<p>Robert Koch turned germ theory from a general claim into a method for proving causation in individual diseases.</p>
<p>He identified the anthrax bacillus in 1876, tracing its full life cycle including the spores that allowed it to persist in soil for years, which explained why fields stayed dangerous long after infected animals were gone.</p>
<p>His postulates set out what must be shown to attribute a disease to an organism: it must be found in all cases of the disease and not in healthy individuals; it must be isolated and grown in pure culture; the cultured organism must cause the disease when introduced into a healthy host; and it must be recoverable from that host.</p>
<p>He also built the practical laboratory methods the field ran on for a century — solid growth media using agar, suggested by Angelina Hesse from her kitchen, allowing pure colonies to be separated; staining techniques; and photomicrography as evidence.</p>
<p>He identified the tuberculosis bacillus in 1882 and the cholera vibrio in 1883, ending the argument decisively for those two diseases.</p>
<p>The postulates have known limits and Koch knew several of them. Some organisms cannot be cultured. Some cause disease in only a fraction of those infected — asymptomatic carriage of cholera and typhoid was a direct problem for the first postulate. Viruses were not culturable at all by his methods. The criteria remain the template for causal argument in infectious disease, applied with judgment rather than literally.</p>

<h2 id="Lister">Into the operating theatre</h2>
<p>Joseph Lister read Pasteur and drew the surgical conclusion: if wound infection is caused by organisms entering from outside, then killing them at the wound should prevent it.</p>
<p>From 1865 he used carbolic acid on instruments, hands, dressings and the wound itself, and sprayed it into the air of the theatre. Mortality after amputation in his ward fell from around 45 per cent to about 15.</p>
<p>Resistance was substantial and lasted years. Surgeons of the period took visible pride in blood-stiffened operating coats, and the ritual complexity of Lister's method was resented.</p>
<p>Antisepsis — killing organisms in the wound — was eventually superseded by asepsis, which prevents them arriving at all: sterilised instruments, gloves, masks, gowns and a controlled field. Carbolic spray was abandoned as harmful to surgeons and unnecessary.</p>
<p>Surgical gloves entered use for a reason unrelated to infection. William Halsted had them made because a nurse in his theatre, whom he later married, was developing dermatitis from the antiseptics. Their infection-control value was recognised afterwards.</p>
<p>Together with anaesthesia, this is what made surgery a treatment rather than a last resort — and the underlying idea, that invisible living things cause disease and can be excluded, remains the most life-saving proposition anyone in medicine has ever advanced.</p>
`,
};
