import type { RewrittenArticle } from "./types";

export const goGame: RewrittenArticle = {
  slug: "go-game",
  title: "Go: almost no rules, and it defeated computers for twenty years after chess fell",
  sourceTitle: "Go (game)",
  dek: "Place a stone, surround your opponent's, do not repeat a position. That is nearly all of it, and the game it produces resisted every technique that worked on chess.",
  standfirst:
    "Go is the clearest case of enormous complexity generated by trivial rules. It has no piece types, no movement, no captures in the chess sense, and a beginner can be taught it in five minutes. It also has a branching factor an order of magnitude beyond chess and, crucially, positions whose value cannot be estimated by counting anything — which is why the methods that beat Kasparov in 1997 were useless against a strong human Go player for the next two decades.",
  readingMinutes: 8,
  html: `
<h2 id="The_rules">The whole of the rules</h2>
<p>Players alternately place a stone of their colour on an intersection of a nineteen-by-nineteen grid. Stones do not move. A group of connected stones with no adjacent empty intersection is captured and removed. A move may not recreate a previous whole-board position. At the end, the player controlling more of the board wins.</p>
<p>That is the game. The detail worth pausing on is the empty adjacent point, called a liberty: a group lives as long as it has one, so the entire game is a negotiation over breathing room rather than over material.</p>
<p>Two consequences follow that make the game feel unlike chess. The board starts empty and fills up, so the position becomes more constrained as the game proceeds rather than less. And a stone placed on move five is usually still there on move two hundred and fifty, meaning every decision is permanent and the position accumulates rather than resets.</p>
<p>The scoring rules differ between traditions — Japanese rules count territory plus prisoners, Chinese rules count territory plus stones on the board — and they produce the same result in almost all games, differing by a point or so in ways that only matter at professional level. The existence of two incompatible scoring systems that nearly always agree is itself a decent indication of how the game's structure works.</p>
<p>Because the first player has an advantage, Black gives White a compensation of several points, called komi, typically six and a half or seven and a half depending on the ruleset. The half-point exists to prevent draws.</p>

<h2 id="Handicap">The handicap system, which is the game's best feature</h2>
<p>Go has a mechanism that most competitive games lack and would benefit from: a graduated handicap that lets players of very different strength play a genuinely interesting game against each other.</p>
<p>The weaker player begins with extra stones on the board, from two up to nine, placed on marked points. Each stone is worth roughly one rank of strength, and ranks are defined by exactly this relation — a player two ranks stronger is one who wins about half the games when giving two stones.</p>
<p>This is a rating system in which the units are physical objects rather than numbers, and it means a teacher and a novice can play a real game in which both are fully extended. In chess the equivalent, giving material odds, was common in the nineteenth century and has largely died out; in Go the handicap game is a normal way to play and carries no stigma.</p>
<p>The rank ladder runs from around 30 kyu for a beginner up to 1 kyu, then 1 dan upward for amateurs, with a separate and much steeper professional dan scale. The distance between a strong amateur and a professional is several stones, which is a large gap expressed in a way anyone can verify at the board.</p>

<h2 id="Why_computers">Why it broke the computers</h2>
<p>Chess programs worked by searching a tree of moves and evaluating the leaves. Both halves of that break down in Go.</p>
<p>The search is bigger. A chess position offers around thirty-five legal moves; an early Go position offers around two hundred and fifty, and games run two or three times longer. The tree is not merely larger, it is larger by an amount that no hardware improvement addresses.</p>
<p>The evaluation is the real problem. A chess position can be assessed reasonably well by counting material with positional adjustments — a rook is worth about five pawns, and that heuristic carries you a long way. In Go every stone is identical and none is ever worth more than another, so there is nothing to count. Whether a group is alive, whether an area is territory, whether a wall faces the right direction: these are properties of the whole configuration, and no one succeeded in writing them down as a function.</p>
<p>Progress came in two steps. Monte Carlo tree search, from around 2006, replaced the evaluation function with statistics: from a given position, play thousands of random games to the end, and use the win rate as the estimate. This is a strange idea that works, because you do not need to know why a position is good if you can measure how often it wins. It lifted programs from weak amateur to strong amateur and then stalled.</p>
<p>The second step was AlphaGo in 2015 and 2016, which added neural networks trained first on human games and then on self-play: one network to suggest plausible moves, narrowing the search, and one to evaluate positions directly, replacing much of the random playout. It beat the European champion Fan Hui, then Lee Sedol four games to one in Seoul in March 2016, which was a decade or more ahead of the field's expectations. Its successor learned from self-play alone, with no human games at all, and was stronger still.</p>

<h2 id="Move_37">The move nobody understood</h2>
<p>In the second game against Lee Sedol, AlphaGo played a shoulder hit on the fifth line — move 37 — which commentators initially took for a mistake, because established theory holds that such a move on the fifth line gives away too much. Its influence turned out to decide the game about fifty moves later.</p>
<p>The programme's own estimate was that a human would have played it with probability around one in ten thousand. That figure is the interesting part: the system was not simply calculating better, it was drawing on a body of judgement that had no human precedent, developed by playing itself millions of times without reference to a tradition.</p>
<p>Lee Sedol's move 78 in the fourth game, a wedge that AlphaGo had assessed as near-impossible and that caused its evaluation to collapse, is the other half of the story, and remains the only game a top human has won against a fully developed system of that class.</p>
<p>What followed in the human game is the part usually left out. Professional Go absorbed the machine's ideas rather than retreating from them: opening theory built up over centuries was substantially revised within a few years, moves previously considered inferior were rehabilitated, and measured playing strength across the professional population rose. The 3-3 invasion early in a game, long regarded as premature, became standard because the machines kept playing it and winning.</p>
<p>Lee Sedol retired from professional play in 2019, saying that with an entity that could not be defeated at the top, he could no longer be the best even if he became the strongest human. That is a coherent position, and the rest of the professional field did not take it.</p>

<h2 id="Adversarial">A recent and instructive embarrassment</h2>
<p>A postscript from 2022 and 2023 is worth recording, because it complicates the story of superhuman play.</p>
<p>Researchers trained an adversarial program specifically to exploit KataGo, a leading open-source engine. It did not beat the engine by playing better Go; it found a strange, specific strategy — encircling a large loose group in a way that the engine misjudged as alive — and won a large majority of games with it. Amateur humans, given the recipe, could then beat top engines using it too.</p>
<p>The result did not show that the engines are weak. It showed that a system trained to a superhuman average can hold pockets of misunderstanding, that these are not visible from ordinary play, and that they can be found deliberately by another system searching for them. That is a general lesson about learned systems rather than a fact about Go, and Go is where it happened to be demonstrated cleanly, because Go has an unambiguous scoring function to search against.</p>
`,
};
