import type { RewrittenArticle } from "./types";

export const hindenburg: RewrittenArticle = {
  slug: "hindenburg",
  title: "The Hindenburg: the half-minute that ended passenger airships",
  sourceTitle: "Hindenburg disaster",
  dek: "It burned in about thirty seconds in front of newsreel cameras. Most of the people on board survived. The airship as a way to travel did not.",
  standfirst:
    "The Hindenburg was the largest aircraft ever flown and, for one season, the most glamorous way to cross the Atlantic. It was destroyed on 6 May 1937 while landing in New Jersey, and the film of its burning is among the most famous pieces of footage of the twentieth century. The disaster is usually said to have killed the airship. It is closer to the truth to say that it ended an industry that was already losing.",
  readingMinutes: 7,
  published: "2026-10-06",
  html: `
<h2 id="What_it_was">A hotel held up by hydrogen</h2>
<p>LZ 129 Hindenburg was built by the Luftschiffbau Zeppelin company and first flew in March 1936. It was 245 metres long — more than three times the length of a modern jumbo jet. Like every Zeppelin it was a rigid airship: a skeleton of aluminium-alloy girders covered in doped fabric, with the lifting gas held in separate cells inside. Passengers had cabins, a dining room, a lounge with a piano, promenades with slanted windows looking down on the sea, and a pressurised smoking room kept at higher pressure than the rest of the ship so that hydrogen could not leak in.</p>
<p>That hydrogen was the ship's central compromise. It had been designed to use helium, which does not burn. But the world's only large supply of helium was in the United States, which since the Helium Control Act of 1927 had restricted its export, and the German company could not obtain it. The Hindenburg flew on about 200,000 cubic metres of hydrogen instead. Zeppelin crews had long experience with hydrogen and treated it with great care; the company's passenger airships had carried tens of thousands of people without a passenger fatality.</p>
<p>In 1936 the Hindenburg made seventeen round trips across the Atlantic, to the United States and to Brazil, crossing in two to three days — about half the time taken by most liners. It also served the Nazi government, which paid for part of its operation: it flew with swastikas on its tail fins and circled the Berlin Olympic stadium during the opening ceremony. Hugo Eckener, the head of the Zeppelin company, was openly unenthusiastic about the regime and was sidelined for it.</p>

<h2 id="Lakehurst">Lakehurst, 6 May 1937</h2>
<p>The first North American flight of the 1937 season arrived late at the Naval Air Station in Lakehurst, New Jersey, having waited out thunderstorms. At about 7.25 pm, as the ship hovered with its mooring lines dropped to the ground crew, flames appeared near the tail. Within roughly half a minute the fire had run the length of the hull and the burning frame had settled to the ground.</p>
<p>There were 97 people on board. Thirty-five of them died, along with one man of the ground crew. Sixty-two survived — more than half — many of them by jumping from windows as the ship sank toward the ground, or by walking out of the wreck once it had settled. Where people happened to be standing decided a great deal. Passengers at the promenade windows were close to the ground and an exit; crew deep in the tail or high in the hull had neither.</p>
<p>The landing was being filmed by several newsreel crews, and a radio reporter, Herbert Morrison, was recording a description on disc for a Chicago station. His voice breaking — "Oh, the humanity!" — was broadcast the following day, and the newsreels reached cinemas within days. Earlier disasters had been photographed. This one was seen and heard in motion by a mass audience almost as it happened.</p>

<h2 id="Cause">What set it alight</h2>
<p>The American and German investigations agreed on the broad outline: hydrogen had leaked into the space between the gas cells and the outer cover near the tail, and something ignited it. The most likely spark was electrostatic. The ship had flown through stormy, highly charged air; when its wet mooring lines touched the ground, the metal frame was earthed, but the fabric cover, which conducted poorly, may not have been, leaving a voltage difference between skin and frame. Some witnesses reported a glow on the ship's back shortly before the fire, which would fit. What caused the leak is less certain; one suggestion is that a bracing wire snapped during a sharp turn on the approach and tore a gas cell.</p>
<p>Sabotage was suspected from the start — the ship was a symbol of the Nazi state — and investigated by both governments. No evidence for it was ever found.</p>
<p>In 1997 Addison Bain, a retired NASA hydrogen specialist, argued that the fire began in the cover itself, whose doping compound contained iron oxide and aluminium powder, and that hydrogen played only a secondary role. The idea attracted attention because it partly rehabilitated hydrogen. Other researchers disputed it, arguing that the cover would have burned far too slowly to explain how fast the ship was consumed, and that the hydrogen was essential to the speed of the fire. The electrostatic-ignition-of-hydrogen account remains the mainstream one.</p>

<h2 id="Why_it_ended">Why the airship did not recover</h2>
<p>The Hindenburg was not the deadliest airship disaster. The British R101 crashed in France in 1930, killing 48, which ended Britain's airship programme. The US Navy's helium-filled Akron came down in the Atlantic in 1933 with the loss of 73 men. Airships had always been vulnerable to weather: huge, slow and light, they were pushed around by winds that an aeroplane would fly through.</p>
<p>They were also expensive. Each one needed a vast hangar and a ground crew of a hundred or more to land it, carried relatively few paying passengers, and had to be built almost by hand. Meanwhile aeroplanes were improving fast. By 1939 Pan American's flying boats were carrying passengers across the Atlantic, and within a few years of the Second World War landplanes were doing it routinely in less than a day.</p>
<p>The fire removed any remaining case for hydrogen-filled passenger airships, and politics removed helium. The United States considered selling helium for the Hindenburg's sister ship, LZ 130, but refused after Germany annexed Austria in 1938. LZ 130 flew test and propaganda flights, and an electronic-surveillance flight along the British coast, but never carried fare-paying passengers. In 1940 it and the old Graf Zeppelin were broken up on Hermann Göring's orders and their metal given to the aircraft industry.</p>

<h2 id="Legacy">An image larger than the event</h2>
<p>The footage outlived the industry. It became shorthand for sudden catastrophe, for technological hubris, and — less fairly — for hydrogen itself; engineers working on hydrogen fuel still talk about the "Hindenburg syndrome" in public attitudes. The comparison is not straightforward. Hydrogen is light and burns upward, and much of what injured people that evening was the falling structure and burning diesel fuel and fabric. None of that makes a hydrogen-filled envelope safe, but it does mean the film shows something more complicated than a gas exploding.</p>
<p>Airships never vanished entirely. Helium-filled blimps and semi-rigid craft are used for advertising, surveillance and sightseeing, and designers periodically propose cargo airships for places without roads. None has yet come close to the scale of the Hindenburg, which, with its sister ship, remains the largest object ever to fly.</p>
`,
};
