import type { RewrittenArticle } from "./types";

export const immuneSystem: RewrittenArticle = {
  slug: "immune-system",
  title: "The immune system: the hard problem is not attacking, it is knowing when to stop",
  sourceTitle: "Immune system",
  dek: "Building a receptor for a pathogen that has not evolved yet requires generating receptors at random — which means also generating the ones that attack you.",
  standfirst:
    "An immune system has to recognise threats it has never encountered, including ones that did not exist when the organism was born. The vertebrate solution is to manufacture receptors by shuffling gene segments at random, producing a repertoire large enough to bind almost anything. The unavoidable consequence is that many of those receptors bind the body itself, and most of the system's machinery is devoted to deleting, suppressing and restraining them.",
  readingMinutes: 8,
  html: `
<h2 id="Two_systems">Two systems doing different jobs</h2>
<p>The innate immune system is old, shared in some form across most multicellular life, and works from a fixed set of recognition tools. Its receptors detect molecular patterns common to whole classes of pathogen and absent from the host — bacterial cell wall components, flagellin, double-stranded RNA — and it responds within minutes. Macrophages and neutrophils engulf material, the complement cascade punctures membranes and tags targets, and inflammation opens the local vasculature to bring more of everything in.</p>
<p>Its limitation is that it cannot improve. The same receptors respond identically to the thousandth infection as to the first.</p>
<p>The adaptive system, found in jawed vertebrates, is slow — a first response takes days — and it does two things the innate system cannot: it recognises specific molecular shapes rather than general classes, and it remembers. B cells make antibodies that bind free pathogens and mark them; T cells inspect the fragments that cells display on their surface, which is how anything hiding inside a cell is detected at all.</p>
<p>The relationship between the two is not a relay but a control system. Innate cells decide whether there is a threat and what kind, and they instruct the adaptive response accordingly, which is why an adaptive response to an antigen presented without any danger signal is usually tolerance rather than attack — the principle every vaccine adjuvant exploits.</p>

<h2 id="Diversity">Generating receptors for the unknown</h2>
<p>The central puzzle of adaptive immunity is arithmetic. The genome contains on the order of twenty thousand protein-coding genes, and the number of distinct antigen receptors needed is far larger than that.</p>
<p>The solution, worked out by Susumu Tonegawa in the 1970s, is that receptor genes are not inherited whole. They are assembled in each developing lymphocyte by cutting and rejoining gene segments — variable, diversity and joining — chosen from arrays of alternatives, with additional nucleotides inserted and deleted at the junctions. The recombination is carried out by enzymes that appear to derive from a domesticated transposon, which is to say the vertebrate immune system was built on captured mobile genetic elements.</p>
<p>The combinatorics produce a theoretical repertoire far beyond the number of lymphocytes a body contains. Each cell ends up with one receptor specificity, and the population as a whole covers enough of the space of possible shapes that essentially any molecule will bind something.</p>
<p>Selection then does the rest. When a receptor binds, that cell divides, so the response is built by amplifying whichever cells happened to fit — clonal selection, proposed by Burnet in the 1950s. B cells go further: during a response their receptor genes mutate at an enormously elevated rate in a process called somatic hypermutation, and cells whose mutations bind better are preferentially kept. This is evolution by variation and selection running inside a lymph node over days, and it is why antibodies late in an infection are far better than the ones that started it.</p>

<h2 id="Tolerance">Deleting the ones that attack you</h2>
<p>Random receptors mean self-reactive receptors, and the system's response is systematic destruction of its own products.</p>
<p>Developing T cells go to the thymus and face two tests. They must bind the body's own presenting molecules weakly — cells that cannot are useless and die by neglect, which is the fate of the large majority. Then they must not bind self-antigens strongly, and those that do are killed or diverted into regulatory roles. The overall attrition is severe: only a small percentage of thymocytes leave the thymus alive.</p>
<p>This requires the thymus to display antigens from tissues that are nowhere near it. It does, through a transcription factor called AIRE that drives promiscuous expression of thousands of tissue-specific genes in thymic cells, so a developing T cell encounters insulin and retinal proteins in an organ behind the sternum. People with AIRE mutations develop a syndrome of multi-organ autoimmunity, which is the demonstration that this odd arrangement is load-bearing.</p>
<p>Central tolerance is incomplete, so there is a second layer. Regulatory T cells actively suppress responses to self, and their loss causes fatal generalised autoimmunity. Peripheral mechanisms render self-reactive cells unresponsive rather than killing them.</p>
<p>Autoimmune disease is what happens when these layers fail, and the striking epidemiological fact is that roughly four in five patients across autoimmune conditions are women — a disparity that is still not fully explained, with X-linked gene dosage, sex hormones and pregnancy-related adaptations all implicated.</p>

<h2 id="Memory">Why the second time is different</h2>
<p>After an infection is cleared most of the expanded clones die, and a small population persists as memory cells. They are more numerous than the original naive cells specific for that antigen, they have lower activation thresholds, and they are pre-positioned in tissues.</p>
<p>The practical consequence is that a second exposure is met in hours rather than days, by antibodies already refined by hypermutation, which is generally enough to prevent illness rather than merely resolve it.</p>
<p>Vaccination is the deliberate exploitation of this: present the antigen with enough danger signalling to trigger a real response, without the pathogen. Everything else in vaccine design — adjuvants, attenuation, mRNA delivery, boosting intervals — is engineering around that single principle.</p>
<p>Memory is not uniform. Measles produces lifelong protection; influenza does not, partly because the virus changes and partly because antibody responses to respiratory infections at the mucosal surface wane faster. Measles also does something specific and vicious: it infects memory cells themselves and erases prior immunity, so children recover from measles with a depleted memory repertoire and elevated susceptibility to other infections for years afterwards, an effect documented in the mortality statistics long before the mechanism was found.</p>

<h2 id="Restraint">When the response is the disease</h2>
<p>A large share of immune-mediated harm comes not from pathogens but from the response to them.</p>
<p>Inflammation is destructive by design — the tools that kill bacteria damage tissue indiscriminately — and the system relies on the response being local and brief. When it is neither, the result is sepsis, in which systemic inflammation causes vascular collapse and organ failure, or the cytokine storms that dominate severe outcomes in some viral infections. In severe COVID-19 the most effective interventions turned out to be immunosuppressive, which is a plain statement of where the damage was coming from.</p>
<p>The same logic runs through allergy, where the machinery evolved against parasitic worms responds to pollen or peanut protein, and through the hygiene hypothesis and its successors, which propose that reduced early microbial exposure leaves the regulatory arm undertrained. The evidence favours a more specific version — early exposure to diverse commensal microbes matters, cleanliness as such is not the variable — and the observation that allergy and autoimmunity have risen together in wealthy countries over decades remains one of the better arguments that something about the regulatory side of the system is environmentally set.</p>
<p>Cancer immunology closes the circle. Tumours are largely self, and the same restraint mechanisms that prevent autoimmunity protect them. Checkpoint inhibitors work by disabling those brakes — releasing T cells that were being held back — and their characteristic side effects are autoimmune, because that is exactly what the drug is doing. The trade is explicit, and it is the clearest available evidence that the system's default posture is restraint rather than attack.</p>
`,
};
