import type { RewrittenArticle } from "./types";

export const internationalLaw: RewrittenArticle = {
  slug: "international-law",
  title: "International law: rules without a police force, obeyed most of the time anyway",
  sourceTitle: "International law",
  dek: "The standard objection is that it cannot be law because nothing enforces it. The standard reply is to look at how much of it is complied with.",
  standfirst:
    "There is no world legislature, no compulsory court, and no police force. By the definition of law most people carry around — commands backed by sanctions from a sovereign — international law fails immediately and should be dismissed as etiquette. The awkward fact for that view is that the overwhelming majority of international obligations are complied with routinely and unremarkably, and that states which break them spend enormous effort arguing that they have not.",
  readingMinutes: 8,
  html: `
<h2 id="Where_the_rules_come_from">Where the rules come from</h2>
<p>With no legislature, the sources of obligation have to be assembled from what states actually do and say. Four are conventionally recognised.</p>
<p><strong>Treaties</strong> are the clearest: written agreements binding on the states that consent to them, and on nobody else. Most of international law is treaty law, and most treaty law is entirely mundane — postal unions, aviation safety, telecommunications spectrum, shipping standards. The dull treaties have close to perfect compliance because states want the coordination they provide.</p>
<p><strong>Custom</strong> is stranger and does bind states that never signed anything. It requires two elements: consistent state practice, and evidence that states follow the practice out of a sense of legal obligation rather than convenience. The second element has an obvious circularity — a practice becomes law when states believe it already is — and international lawyers have argued about it for a century without resolving it. It nonetheless does real work, since the rules on diplomatic immunity and much of the law of war began as custom.</p>
<p><strong>General principles</strong> common to legal systems fill gaps: that nobody may benefit from their own wrong, that a matter finally decided stays decided.</p>
<p><strong>Judicial decisions and scholarship</strong> are formally only evidence of the law rather than sources of it, which is a distinction observed more in the citation than in the practice.</p>
<p>A state that persistently objects to an emerging custom from the outset is generally not bound by it, which is the escape hatch that makes custom tolerable to sovereigns and which is invoked far less often than one might expect.</p>

<h2 id="Westphalia">The sovereignty story, and why it is half wrong</h2>
<p>The conventional account dates the system to the Peace of Westphalia in 1648, which ended the Thirty Years' War and is credited with establishing sovereign equality and non-interference in internal affairs.</p>
<p>Historians have been dismantling this for some time. The treaties themselves say little about sovereignty in the modern sense, they left the Holy Roman Empire's tangled internal arrangements substantially intact, and the tidy narrative was largely constructed in the nineteenth century by people who needed an origin story. What is true is that a European order of formally equal territorial states did eventually emerge, and that its rules were written by and for those states.</p>
<p>That last point is the one usually skipped. The law of nations as it developed applied among European states and did not apply to their dealings with everyone else, where doctrines of discovery, terra nullius and civilisational standing did the opposite work — furnishing legal cover for acquisition. International law's universality dates from decolonisation, which is recent, and the newly independent states inherited a body of rules they had no part in making. The persistent charge that the system encodes the interests of its authors is not a fringe position; it is a substantial scholarly tradition and it is difficult to answer historically.</p>

<h2 id="Force">The rule against force, and its two exceptions</h2>
<p>The single most consequential provision in international law is the UN Charter's prohibition on the threat or use of force against the territorial integrity or political independence of any state. It was a genuine break: before 1945, war was a lawful instrument of policy, and conquest transferred good title.</p>
<p>Two exceptions are written into the Charter. Self-defence against an armed attack, until the Security Council acts. And force authorised by the Security Council itself.</p>
<p>Almost every serious dispute since has been an argument about the edges of those two. Does self-defence extend to imminent attacks, and how imminent? To attacks by non-state groups operating from a state unwilling or unable to control them? Does a Council resolution authorising force in one context revive years later? Humanitarian intervention without authorisation has no clear basis in the text, which is why the doctrine of a responsibility to protect was developed — and why its most prominent invocation, in Libya in 2011, was followed by a collapse in Council appetite for repeating it.</p>
<p>The Security Council's veto is the structural flaw and was entirely deliberate. Five states hold a permanent veto, which means the enforcement machinery is unavailable whenever a great power or its client is involved. This is not a malfunction: the alternative in 1945 was that those states would not join, and the founders judged an organisation containing them and paralysed in certain cases better than one that excluded them. Whether that judgment still holds is the standing argument about reform.</p>

<h2 id="Why_states_comply">Why states comply</h2>
<p>Louis Henkin's observation — that almost all nations observe almost all principles of international law and almost all of their obligations almost all of the time — remains the best one-sentence summary, and the explanations are more interesting than the enforcement question suggests.</p>
<p>Most obligations are reciprocal, and breaking them invites the same treatment. A state that ignores diplomatic immunity finds its own diplomats exposed. This works well for bilateral, repeated interactions and poorly for obligations owed to everyone at once, such as human rights, where nobody in particular is injured by a breach and nobody in particular is placed to respond.</p>
<p>Reputation matters, because states negotiate constantly and one known to disregard commitments obtains worse terms in everything that follows.</p>
<p>Domestic incorporation may be the strongest mechanism and is the least discussed. Treaty obligations become national statutes, national agencies administer them, national courts apply them, and domestic constituencies form around them. At that point compliance stops being a foreign policy decision and becomes ordinary administration. This is why the boring treaties work so well and why the dramatic ones do not.</p>
<p>And breaches are argued rather than asserted. A state using force almost always claims self-defence, however implausibly. The effort spent constructing the argument is itself evidence that the rule constrains — nobody bothers justifying conduct against a standard they regard as fictional.</p>

<h2 id="Courts">The courts, and what they can reach</h2>
<p>The International Court of Justice decides disputes between states, and only where both have accepted its jurisdiction — by treaty clause, by special agreement, or by a standing declaration that many states have hedged with reservations. When a great power loses, compliance is a matter of choice; the United States withdrew from the Court's compulsory jurisdiction after losing the Nicaragua case in 1986.</p>
<p>The International Criminal Court is a different instrument, prosecuting individuals rather than states for genocide, crimes against humanity, war crimes and aggression. Its founding premise, established at Nuremberg, is that crimes are committed by people and not abstract entities, and that official position is not a defence.</p>
<p>Its structural difficulty is jurisdictional. It reaches conduct on the territory of member states or by their nationals, and several of the most powerful states are not members. The resulting caseload skewed heavily toward Africa in its first two decades, which produced a legitimacy crisis and threats of mass withdrawal, and the criticism was not answered by pointing out that several of those cases were self-referred.</p>
<p>Regional systems have been notably more effective, and the European Court of Human Rights is the clearest case: individuals may petition it directly, judgments are complied with at a high rate, and national laws have been changed in response across a wide range of subjects. It works because it sits inside a dense institutional order with membership benefits worth protecting — which is a description of the conditions under which international law bites, and equally a description of how rare those conditions are.</p>
`,
};
