import type { RewrittenArticle } from "./types";

export const jazz: RewrittenArticle = {
  slug: "jazz",
  title: "Jazz: an argument you can dance to",
  sourceTitle: "Jazz",
  dek: "Built in New Orleans out of three continents' music, and defined ever since by musicians refusing to repeat themselves.",
  standfirst:
    "No definition of jazz has ever held. Improvisation is central until you reach the arranged big bands; swing is essential until it isn't; the blues underpins everything until the modal players thin it out. What actually persists is a posture — that a piece of music is a proposal, and the performer's job is to answer it.",
  readingMinutes: 8,
  html: `
<h2 id="A_city_that_could_not_have_been_designed_better">A city that could not have been designed better</h2>
<p>Jazz emerged in New Orleans around the turn of the twentieth century because almost nowhere else in America combined the right ingredients. The city had been French and then Spanish before it was American, leaving a Catholic Creole culture with a tradition of formal music education that Black musicians could access. It had Congo Square, where enslaved people had been permitted to gather and drum on Sundays — a rare surviving thread of West African rhythmic practice in North America. It had a port, and with it Caribbean music carrying the Cuban <em>habanera</em> rhythm that Jelly Roll Morton called the "Spanish tinge". It had brass bands, funeral processions, dance halls, and a surplus of military instruments after the Civil War.</p>
<p>What came out of that collision was genuinely new but not mysterious. Ragtime supplied syncopation and a written piano tradition. The blues supplied a harmonic form, the flattened notes that Western notation cannot represent, and a vocal approach to instruments — the growls, bends and cries that make a trumpet sound like a voice complaining. European harmony supplied the chords, and marching bands supplied the instrumentation. The specific innovation was collective improvisation: cornet carrying the melody, clarinet weaving above it, trombone sliding underneath, all three inventing simultaneously without colliding.</p>
<p>Segregation was the unacknowledged engine. Black musicians barred from orchestras, and Creole musicians pushed by tightening racial laws out of their formerly protected status and into the same bands, ended up in the same rooms with two different musical educations. Jazz is partly the sound of that forced meeting.</p>

<h2 id="Recording_and_the_journey_north">Recording and the journey north</h2>
<p>The first jazz record, in 1917, was made by a white group, the Original Dixieland Jass Band, and sold enormously. That pattern — Black innovation, white commercial reward — recurs so consistently through the music's history that it is less an irony than a structural feature.</p>
<p>The music travelled with the Great Migration, as hundreds of thousands of Black Southerners moved north for work. Chicago got King Oliver's Creole Jazz Band, and with it a young second cornetist named Louis Armstrong. New York got Harlem, the Cotton Club, and an economy of dance halls.</p>
<p>Armstrong's Hot Five and Hot Seven recordings in the late 1920s changed the music's shape permanently. He shifted the emphasis from collective improvisation to the individual soloist, playing lines of a rhythmic sophistication nobody had recorded before — phrases that float behind the beat and catch up, a sense of swing that other musicians immediately copied and are still copying. He also, on a session where he reportedly dropped the lyric sheet, popularised scat singing. Almost everything that follows in jazz solos is downstream of what he demonstrated was possible.</p>

<h2 id="Swing_and_the_moment_jazz_was_pop_music">Swing, and the moment jazz was pop music</h2>
<p>By the 1930s the small groups had grown into big bands and jazz had become America's popular dance music — the only period in its history when it was. Arrangement mattered as much as improvisation: sections of brass and reeds answering each other in written call-and-response, with soloists stepping out over the top.</p>
<p>Duke Ellington is the era's most durable figure and its least typical. He wrote for the specific players in his orchestra rather than for instruments in the abstract, producing music that was inseparable from the individuals performing it, and he sustained the practice across five decades and thousands of compositions. Count Basie's Kansas City band pushed the opposite way, toward a light, blues-drenched rhythm section and space for soloists to stretch.</p>
<p>Benny Goodman's band brought swing to a mass white audience, and — significantly — Goodman integrated his groups publicly at a time when that was commercially risky. Meanwhile Billie Holiday was demonstrating what a jazz singer could be: a phraser rather than a belter, dragging behind the beat, and in 1939 recording "Strange Fruit", an anti-lynching song her label refused to touch.</p>

<h2 id="Bebop_breaks_the_contract">Bebop breaks the contract</h2>
<p>In the early 1940s, at after-hours sessions in Harlem clubs, a group of younger musicians began playing at tempos and harmonic densities that made the music undanceable — arguably on purpose. Charlie Parker, Dizzy Gillespie, Thelonious Monk and Kenny Clarke built bebop out of the same standards everyone knew, then substituted chords, ran the harmony through extended intervals, moved the timekeeping from the bass drum to the ride cymbal, and played melodic lines fast enough to exclude anyone who had not done the work.</p>
<p>The break was social as much as musical. Bebop asserted that jazz was art music demanding attention, not entertainment for a dance floor, and that Black musicians would define its terms. Audiences shrank. The music's prestige rose. Every subsequent argument about jazz's relationship to its audience starts here.</p>

<h2 id="The_decade_of_forks">The decade of forks</h2>
<p>The 1950s and early 1960s produced more distinct directions than any comparable stretch. Cool jazz pulled the temperature down, favouring restraint and unusual instrumentation — the Miles Davis nonet, then the West Coast players. Hard bop pushed back toward gospel and blues with Art Blakey and Horace Silver. Modal jazz, arriving with Davis's <em>Kind of Blue</em> in 1959, replaced fast-moving chord progressions with scales held for long stretches, giving soloists space to develop melody instead of navigating changes; it remains the best-selling jazz album ever made.</p>
<p>John Coltrane moved through several of these and then past them, from the dense harmonic exercises of <em>Giant Steps</em> to the modal expansiveness of <em>A Love Supreme</em> to a late free playing that many of his own admirers could not follow. Ornette Coleman's <em>The Shape of Jazz to Come</em>, also 1959, dispensed with fixed chord progressions entirely, which some musicians regarded as liberation and others as vandalism.</p>
<p>Then Davis changed direction again. <em>Bitches Brew</em> in 1970 brought in electric instruments, rock rhythms and studio editing, opening the fusion era and a long argument about whether amplification constituted betrayal.</p>

<h2 id="What_it_left_behind">What it left behind</h2>
<p>Jazz stopped being popular music decades ago and became something else — a repertoire, an academic discipline, and a set of techniques that leaked into nearly everything. Its harmonic vocabulary is standard in film scoring and musical theatre; its rhythmic approach runs through R&B, funk and hip-hop, which has sampled it heavily enough to have brought it back to a young audience by an unexpected route.</p>
<p>The institutional turn has costs. Jazz education has produced generations of technically formidable players and a persistent worry that a music built on rule-breaking is now taught as a set of rules. Wynton Marsalis's argument for a defined canon and Miles Davis's refusal to look backward represent a tension that has never resolved and probably should not.</p>
<p>The living version is elsewhere anyway — in London and Johannesburg and São Paulo, mixed with West African rhythm, electronic production and local traditions, made mostly by musicians who take the label loosely. Which is about right for a music whose one consistent principle has been that the version you inherited is a starting point.</p>
`,
};
