import type { RewrittenArticle } from "./types";

export const mycorrhizalNetworks: RewrittenArticle = {
  slug: "mycorrhizal-networks",
  title: "Mycorrhizae: most plants do not gather their own nutrients, and never have",
  sourceTitle: "Mycorrhiza",
  dek: "Around nine in ten land plants trade sugar to a fungus for phosphorus. The partnership is 400 million years old and probably made land plants possible.",
  standfirst:
    "A root is bad at extracting phosphorus, because phosphate moves through soil very slowly and a root quickly exhausts the volume immediately around it. Fungal hyphae are far thinner, extend much further for the same investment, and are good at exactly this. The resulting trade — plant carbon for fungal minerals — is present in the earliest fossils of land plants, and the popular story built on top of it in recent years has run some way ahead of the evidence.",
  readingMinutes: 7,
  html: `
<h2 id="Trade">Why a root needs help</h2>
<p>Phosphate ions bind tightly to soil particles and diffuse extremely slowly. A root absorbing phosphorus creates a depletion zone around itself within days, and after that it is limited not by its uptake capacity but by how fast phosphate arrives — which is barely at all.</p>
<p>The only remedy is to reach further, and reaching further with roots is expensive. A root is thick, costly to build in carbon, and cannot be produced in the quantity required.</p>
<p>Hyphae are one or two orders of magnitude thinner. For the same carbon, a fungus produces vastly more absorptive length and can penetrate pores too small for a root hair. The plant supplies sugars and lipids from photosynthesis; the fungus supplies phosphorus, nitrogen and water, and the exchange happens at specialised interfaces where the two organisms' membranes come into close contact.</p>
<p>The proportions involved are substantial. Plants commonly direct on the order of a tenth to a fifth of their photosynthetic output to fungal partners, and mycorrhizal fungi supply a large share of the phosphorus a plant acquires. This is not a marginal supplement; for most species it is the main route.</p>
<p>Two forms dominate. Arbuscular mycorrhizae, formed by fungi of the Glomeromycota, penetrate root cells and form finely branched structures inside them, and are found in the great majority of plant families. Ectomycorrhizae sheathe the root without entering cells and are formed by many familiar mushroom-producing fungi; they are characteristic of temperate and boreal trees — pines, oaks, birches — and most edible wild mushrooms are the fruiting bodies of tree partners, which is why they cannot be farmed the way button mushrooms are.</p>

<h2 id="Ancient">Older than roots</h2>
<p>The association appears in the earliest well-preserved land plant fossils. The Rhynie chert of Scotland, around 400 million years old, contains plants with fungal structures closely resembling modern arbuscular mycorrhizae — in plants that had no true roots.</p>
<p>That sequence matters. The partnership predates the organ it is usually described as assisting, which supports the hypothesis that fungal association was part of how plants colonised land at all. Early terrestrial substrates were mineral, nutrient-poor and unweathered, and a photosynthetic organism paired with something capable of extracting minerals from rock is a far more plausible pioneer than either alone.</p>
<p>The genetic machinery supports the same story. The signalling pathway plants use to admit arbuscular fungi is conserved across land plants, and the nitrogen-fixing symbiosis that legumes form with bacteria appears to have been built by co-opting parts of it — a much older fungal partnership repurposed for a newer bacterial one.</p>
<p>Some lineages have abandoned it. The Brassicaceae, which includes cabbages and Arabidopsis, are largely non-mycorrhizal, as are some others, and they compensate with different root strategies. This is worth noting because Arabidopsis is the standard laboratory plant, so the model organism on which much plant molecular biology was built is unusual in precisely this respect.</p>

<h2 id="Networks">The claim that grew too fast</h2>
<p>Because a single fungal individual can connect to more than one plant, roots of different plants — and different species — can be linked through shared mycelium. These are common mycorrhizal networks, and the popular name for them, the wood wide web, comes from a headline on a 1997 <em>Nature</em> paper.</p>
<p>That paper, by Suzanne Simard and colleagues, used isotopic labelling to show carbon moving between Douglas fir and paper birch, with net transfer toward the shaded partner. It is a real and careful result.</p>
<p>What has been built on it in popular writing goes considerably further: that trees deliberately feed their offspring, that mother trees recognise kin and preferentially support them, that networks warn neighbours of insect attack, and that forests function as cooperative superorganisms.</p>
<p>A substantial critical review by Karst, Jones and Hoeksema in 2023 examined the field's own literature and reported that the evidence base is thinner than the confidence of the claims. Their findings were that common networks are less well demonstrated in field conditions than assumed, that evidence for resource transfer benefiting recipient seedlings is mixed and often absent, that no field study supports preferential transfer to kin, and that citation patterns had drifted — papers were increasingly cited for claims stronger than the ones they made.</p>
<p>The critique has been contested in turn, and the argument is live. The defensible position at present is narrow and still interesting: fungal connections between plants exist, materials can move through them, the direction and quantity are variable and often small, and whether the plants involved benefit is not established. The transfers observed may reflect the fungus's own interests rather than any plant-to-plant altruism, since the fungus is a third party with its own strategy — a point that gets lost when the network is described as infrastructure the trees are using.</p>

<h2 id="Cheating">Plants that have stopped photosynthesising</h2>
<p>The most direct evidence that these networks move carbon comes from plants that exploit them and give nothing back.</p>
<p>Mycoheterotrophic plants have abandoned photosynthesis entirely. They have no chlorophyll, are frequently white, pink or brown, and obtain all their carbon from fungi. The ghost pipe, <em>Monotropa uniflora</em>, is the familiar example, and several hundred species across multiple families have independently taken the same route.</p>
<p>Since the fungi supplying them are simultaneously partnered with photosynthetic trees, the carbon originates in the tree, travels into the fungus, and ends up in a plant that returns nothing. That is a demonstrated pathway from one plant to another through a fungus, and its existence is what makes broader network transfer plausible in principle.</p>
<p>Many orchids do the same thing temporarily. Orchid seeds are minute and carry almost no reserves, and germination in the wild depends on infection by an appropriate fungus that supplies the seedling until it can photosynthesise. Some orchid species never become independent. This dependence is why orchids proved so difficult to propagate before the fungal requirement was understood, and why some remain nearly impossible to cultivate.</p>

<h2 id="Agriculture">What this means for growing food</h2>
<p>Modern agriculture disrupts the association in several ways at once. Deep tillage physically breaks the hyphal network, which takes time to re-establish. High phosphate fertiliser application suppresses it, because a plant with abundant phosphorus reduces its investment in fungal partners — a sensible economic response that leaves the crop dependent on continued fertilisation.</p>
<p>This matters beyond yield. Phosphate rock is a finite, geographically concentrated resource, and phosphorus runoff is a principal driver of freshwater eutrophication. A system that suppresses the biological route to phosphorus while increasing the mineral input is exactly backwards from a resource standpoint.</p>
<p>Commercial mycorrhizal inoculants are sold widely, and independent assessments have been unflattering: field results are inconsistent, products have been found to contain fewer viable propagules than claimed, and introduced strains frequently fail to establish against the native community already present. Inoculation performs best in genuinely disturbed or sterile substrates — mine restoration, degraded land, some horticultural contexts — and poorly in ordinary agricultural soils that already contain fungi.</p>
<p>The interventions with better support are indirect: reduced tillage, cover cropping to maintain a living host through the year, and moderating phosphate inputs so that the plants retain a reason to invest in the partnership they have had for 400 million years.</p>
`,
};
