import type { RewrittenArticle } from "./types";

export const quantumMechanics: RewrittenArticle = {
  slug: "quantum-mechanics",
  title: "Quantum mechanics: the most accurate theory ever tested, and nobody agrees what it says",
  sourceTitle: "Quantum mechanics",
  dek: "The mathematics is unambiguous and predicts experiments to twelve decimal places. What the mathematics is describing has been argued about for a hundred years.",
  standfirst:
    "There is no controversy about how to use quantum mechanics. Write down the equation, solve it, calculate probabilities, compare with experiment; the agreement is the best in the history of science. The controversy is entirely about what the equation refers to — whether the wave function is a physical thing or a bookkeeping device, and what happens at the moment a measurement is made. A century of experiment has narrowed the options without settling them.",
  readingMinutes: 9,
  html: `
<h2 id="Where_it_came_from">Where it came from</h2>
<p>Quantum mechanics did not begin as a philosophical departure. It began as a fudge to fix a calculation that had gone catastrophically wrong.</p>
<p>Classical physics, applied to the radiation from a hot object, predicted that the energy emitted should rise without limit at short wavelengths — every warm thing should be blasting out infinite ultraviolet. Reality obviously disagreed. Max Planck found in 1900 that the correct curve fell out if you assumed energy was exchanged only in discrete packets proportional to frequency, and he regarded this as a mathematical trick with no physical meaning, which he spent years trying to eliminate.</p>
<p>Einstein took it literally in 1905, arguing that light itself comes in quanta, which explained why shining light on a metal ejects electrons only above a threshold frequency — no matter how intense a dim red beam, it will not do it, while a faint blue one will. Intensity is the number of packets; frequency is the energy of each. This, not relativity, is what his Nobel Prize was for.</p>
<p>Bohr applied quantisation to atoms in 1913 with a model that worked for hydrogen and failed for everything else. The real theory arrived in the mid-1920s in two apparently unrelated forms — Heisenberg's matrix mechanics and Schrödinger's wave equation — which were shortly proved to be the same theory in different clothing.</p>

<h2 id="The_double_slit">The experiment everything else is a footnote to</h2>
<p>Fire particles one at a time at a barrier with two slits and record where each lands on a screen behind.</p>
<p>Each arrival is a single point — a definite particle hitting a definite place. But the pattern that builds up over thousands of arrivals is an interference pattern, with bright and dark bands, of the kind produced by waves passing through both slits and combining. There are places on the screen that particles reach when one slit is open and stop reaching when the second slit is opened, which means opening a second route to a destination can prevent arrival there. No description in terms of a particle travelling through one slit or the other can produce that.</p>
<p>Now place a detector at the slits to see which one each particle goes through. The detector always reports one slit, never both — and the interference pattern vanishes, replaced by two plain bands. Remove the detector and the interference returns.</p>
<p>This has been done with electrons, neutrons, atoms, and molecules of several hundred atoms. It is not an artefact of small numbers or crude apparatus. Richard Feynman called it the only mystery, on the grounds that every other quantum puzzle is this one restated.</p>
<p>The delayed-choice variants make it worse. The decision about whether to detect which-path information can be made after the particle has passed the slits, and the outcome still corresponds to the decision. Nothing travels backward in time — no signal can be sent this way — but no story in which the particle decided what to be on the way through survives either.</p>

<h2 id="What_the_theory_actually_says">What the theory actually says</h2>
<p>A system is described by a wave function, which evolves in time according to the Schrödinger equation. That evolution is smooth, deterministic, and perfectly well behaved: given the wave function now, the equation tells you the wave function later, with no randomness whatsoever.</p>
<p>Randomness enters only when you calculate what you will observe. The Born rule says the probability of a given result is the squared magnitude of the corresponding part of the wave function. And after the measurement, the system behaves as if the wave function had abruptly collapsed to the observed outcome — which is not something the Schrödinger equation does or could do.</p>
<p>So the theory has two rules: a continuous deterministic one for when nobody is looking, and a discontinuous probabilistic one for when somebody is. Nothing in the formalism defines what counts as looking. This is the measurement problem, and it is the whole of the interpretive dispute.</p>
<p>Superposition is often described as a system being in two states at once, which is a poor summary. The wave function is a sum of contributions that can cancel as well as add, and interference — the cancelling — is the physical content. A system in superposition is not secretly in one state; a system secretly in one state produces no interference pattern.</p>
<p>Uncertainty is likewise not about clumsy instruments. Position and momentum are related as a wave and its frequency spectrum are related, and a wave sharply localised in space is necessarily made of many frequencies. A particle cannot have both a definite position and a definite momentum for the same reason a single instantaneous click has no definite pitch.</p>

<h2 id="Entanglement">Entanglement, and the experiment that closed the argument</h2>
<p>Two particles can share a single wave function, such that neither has a definite state of its own but their properties are correlated. Measure one and the other is immediately determined, however far apart they are.</p>
<p>Einstein, Podolsky and Rosen argued in 1935 that this showed the theory was incomplete: surely each particle carried its answer all along, and quantum mechanics simply failed to describe it. Their target was spooky action at a distance, and their proposed remedy was hidden variables — real properties the theory was not tracking.</p>
<p>For thirty years this was philosophy. In 1964 John Bell converted it into an experiment. He showed that any theory in which particles carry predetermined local properties must satisfy a specific inequality relating measurement correlations at different angles — and that quantum mechanics predicts violations of it.</p>
<p>The experiments were done, from Clauser in the 1970s through Aspect in 1982 to the loophole-free versions of 2015, and quantum mechanics wins every time. The 2022 Nobel Prize went to that work. The conclusion is not that information travels faster than light — it does not, and entanglement cannot transmit a message, since each side alone sees only random results and the correlation appears only when the two records are later compared. The conclusion is that the world does not consist of objects carrying definite local properties independent of measurement. One of those assumptions has to go, and the experiments do not say which.</p>

<h2 id="Decoherence">Why the everyday world looks classical</h2>
<p>The obvious objection is that chairs and cats manifestly do not exhibit interference. Decoherence explains why, and it is the most significant conceptual advance since the founding period.</p>
<p>A system in superposition retains interference only while its parts remain unentangled with everything else. But nothing is isolated: air molecules collide with objects, photons scatter off them, thermal radiation leaks out. Each interaction entangles the system a little further with its surroundings, and the interference terms — which is to say the distinctively quantum part — spread irretrievably into the environment.</p>
<p>The timescales are extreme. A dust grain in a vacuum, exposed only to background starlight, decoheres in a tiny fraction of a second. A cat is not a borderline case by many orders of magnitude. This is also why quantum computers require near-absolute-zero temperatures and extreme isolation: they are fighting decoherence continuously, and it is the central engineering obstacle in the field.</p>
<p>Decoherence explains, from within the theory and with no extra rules, why superpositions become unobservable at everyday scales. What it does not do is explain why one outcome occurs rather than another. It converts the measurement problem from why-don't-we-see-superpositions into why-this-result — which is progress, but is not a solution, and is sometimes oversold as one.</p>

<h2 id="Interpretations">The interpretations</h2>
<p>The main positions have all survived a century, which is itself informative.</p>
<p><strong>Copenhagen</strong>, in its various forms, treats the wave function as a tool for calculating probabilities rather than a description of reality, and declines to say what happens between measurements. It is what most physicists were taught and what most of them use, and its critics call it an instruction to stop asking.</p>
<p><strong>Many-worlds</strong> takes the Schrödinger equation as complete and simply deletes collapse. Every outcome occurs, in branches of the wave function that decoherence renders mutually inaccessible. It is the most economical in equations and the most extravagant in ontology, and it has a real technical difficulty in explaining why the Born rule probabilities are what they are when everything happens.</p>
<p><strong>Pilot-wave</strong> theory restores definite particle positions guided by a real wave. It reproduces all predictions and is explicitly non-local — the guiding wave depends instantly on the whole configuration — which is exactly what Bell's theorem says any such theory must be.</p>
<p><strong>Objective collapse</strong> models add a physical mechanism that makes collapse real and more frequent for larger systems. Unlike the others, these make predictions that differ from standard quantum mechanics, and experiments are steadily narrowing their parameter space.</p>
<p>All make identical predictions for every experiment performed to date, apart from the collapse models at the margins. The choice is currently made on grounds of taste, and the honest summary is that a hundred years of the most successful theory in physics has not produced agreement about what it is a theory of.</p>

<h2 id="It_is_not_a_metaphor">A closing caution</h2>
<p>Quantum mechanics is not a licence for vagueness. It is the most precisely tested theory there is: quantum electrodynamics predicts the magnetic moment of the electron to twelve significant figures, matched by measurement.</p>
<p>It is also not optional or exotic. The transistor, the laser, the LED, magnetic resonance imaging, and the flash memory in every device depend on it directly. Roughly a third of the economy of industrialised countries rests on technologies that cannot be designed without it.</p>
<p>What it does not license is the popular extension to consciousness, wishes, or wellness. The observer in quantum mechanics is a measuring apparatus, and a photographic plate does the job perfectly well. Nothing in the theory grants a mind any special role, and the claim that it does is a misreading of a technical term that has been in circulation almost as long as the theory itself.</p>
`,
};
