import type { RewrittenArticle } from "./types";

export const renaissance: RewrittenArticle = {
  slug: "renaissance",
  title: "The Renaissance: an age that invented its own origin story",
  sourceTitle: "Renaissance",
  dek: "A rebirth announced by the people living through it, and questioned by nearly every historian since.",
  standfirst:
    "The Renaissance is the only historical period that named itself in advance. Fourteenth-century Italian writers declared that a thousand years of darkness had ended and that antiquity was returning through them — a piece of self-promotion so effective that it organised European history for the next six hundred years.",
  readingMinutes: 8,
  html: `
<h2 id="The_label_is_an_argument">The label is an argument</h2>
<p>Petrarch, writing in the 1330s, divided history into a luminous classical past, a "dark age" of decline, and a present in which the light might be recovered. That scheme was a polemic, not a description. It cast his own literary programme as civilisational rescue, and it has been quietly shaping curricula ever since.</p>
<p>Historians have spent a century dismantling it. The "dark ages" produced universities, Gothic cathedrals, mechanical clocks, water-powered industry and eyeglasses; the twelfth century had its own vigorous classical revival. Ancient texts were never lost so much as unevenly distributed — much of Aristotle reached Europe through Arabic translation and commentary, and Byzantine scholars had preserved the Greek canon continuously. The Renaissance did not rediscover antiquity. It changed what it wanted from it.</p>
<p>Something nonetheless happened, and the useful version is narrower than the myth: a shift in what educated Europeans believed knowledge was for, spreading from a few Italian cities across two centuries, arriving late and differently everywhere else.</p>

<h2 id="Why_Italy_and_why_then">Why Italy, and why then</h2>
<p>The answer is largely commercial. Northern Italy was the richest, most urbanised region in Europe, its city-states grown fat on the Mediterranean trade between Europe and the East. Florence, Venice, Milan and Genoa were run not by landed aristocrats but by bankers, wool merchants and shipowners — people with money, civic ambition, and a persistent need to launder both into respectability.</p>
<p>Italy also had no unified monarchy, and its cities were in permanent competition. Patronage became a form of warfare conducted through architecture. The Medici, who ran Florence for generations while formally holding almost no office, spent staggering sums on buildings, sculpture and manuscripts because visible magnificence was how power was demonstrated in a republic that officially had no ruler.</p>
<p>Two shocks cleared the ground. The Black Death killed perhaps a third of Europe in the 1340s, which — grimly — raised wages for survivors, concentrated inherited wealth, and shook confidence in the institutions that had failed to explain it. And the Ottoman advance on Constantinople, culminating in 1453, sent Greek-speaking scholars west carrying manuscripts and the ability to read them.</p>

<h2 id="Humanism_was_a_curriculum">Humanism was a curriculum</h2>
<p>The intellectual core of the Renaissance was not a philosophy of human dignity but something more concrete: a proposed change to what students should study. The <em>studia humanitatis</em> meant grammar, rhetoric, poetry, history and moral philosophy, taught from classical sources in the original languages. Against it stood the scholastic curriculum of logic, metaphysics and theology that dominated the universities.</p>
<p>The difference in emphasis mattered enormously. Scholasticism asked how to reason correctly about revealed truth. Humanism asked how to speak and act well in public life — a training for citizens, diplomats and secretaries rather than for theologians. Its practitioners were mostly devout Christians; Erasmus applied the new philological methods to the Greek New Testament and Thomas More died for the papacy. This was not a secular movement, but it did put a technique in circulation that could be turned on anything.</p>
<p>That technique was textual criticism, and its most spectacular result came in 1440, when Lorenzo Valla proved the Donation of Constantine — the document underpinning papal claims to temporal power — a forgery, by demonstrating that its Latin belonged to a later century than it claimed. The idea that a document could be interrogated on internal evidence, and that authority could lose to evidence, is arguably the period's most consequential export.</p>

<h2 id="The_art_everyone_remembers">The art everyone remembers</h2>
<p>Renaissance art is usually described as a turn to realism, which undersells it. It was a turn to <em>construction</em> — the belief that visual appearance obeys rules that can be discovered and applied.</p>
<p>Brunelleschi worked out linear perspective around 1420 as a geometric procedure, giving painters a repeatable method for projecting three dimensions onto two. Alberti wrote it down, and within a generation it was standard equipment. Anatomical dissection, undertaken by artists rather than only physicians, gave the human figure a structure underneath the surface; Leonardo's notebooks contain studies of muscle and bone that were better than the published medical illustrations of his day. Oil paint, refined in the Netherlands and adopted in Italy, allowed slow reworking, translucent glazes and a depth of colour that tempera could not reach.</p>
<p>The subject matter shifted with the technique. Classical mythology returned as legitimate material alongside scripture; portraiture of living, identifiable, non-royal people became a major genre; landscape stopped being a backdrop and became a subject. And the artist's own status changed — from a workshop craftsman under guild regulation to something closer to an intellectual, a shift Michelangelo pursued with famous belligerence.</p>
<p>Brunelleschi's dome over Florence's cathedral remains the emblem of the period for good reason. It was raised without the usual wooden centring, using a double shell and a herringbone brick pattern that let the structure support itself as it rose — a problem the original builders had left unsolved for decades in the confidence that someone would eventually work it out.</p>

<h2 id="Printing_changes_the_arithmetic">Printing changes the arithmetic</h2>
<p>Around 1450 Johannes Gutenberg combined movable metal type, an oil-based ink and a modified press into a system for producing books mechanically. Within fifty years European presses had produced millions of volumes.</p>
<p>The effects compound in ways that are easy to state and hard to overstate. Texts became cheap, so literacy became worth acquiring. Copies became identical, so scholars in different cities could argue about the same page — a precondition for cumulative science that manuscript culture had never provided. Ideas escaped the control of the institutions that had previously controlled copying, which is why Luther's theses reached a continental audience in weeks in 1517 where earlier reform movements had been contained locally. The Reformation was not caused by printing, but it was the first movement to be unsuppressible because of it.</p>

<h2 id="North_of_the_Alps_and_after">North of the Alps, and after</h2>
<p>The northern Renaissance was not a delayed copy. It carried a heavier religious and satirical charge — Erasmus and More writing social criticism, Dürer bringing Italian proportion to German printmaking, Bruegel painting peasants with neither contempt nor sentimentality. Vernacular literature became a serious vehicle: Rabelais, Montaigne's invention of the essay as a form for thinking in public, Cervantes, Shakespeare.</p>
<p>Meanwhile the same period supplied the darker inventory that the celebratory account tends to omit. Renaissance Europe launched the Atlantic slave trade, colonised the Americas with catastrophic consequences for their populations, prosecuted its most intense witch trials, and fought the wars of religion. The Italian wars from 1494 wrecked the very city-states that had produced the movement, and the sack of Rome in 1527 scattered its artists. The same decades produced perspective and the Inquisition's Index of banned books.</p>
<p>What survived is not the self-image but the habits: that texts should be checked against evidence, that the natural world has discoverable rules, that a person's education is a preparation for public life, and that the past is a resource to be argued with rather than an authority to be obeyed. The Renaissance overstated its own novelty considerably. It was right about what it had started.</p>
`,
};
