import type { RewrittenArticle } from "./types";

export const romanEmpire: RewrittenArticle = {
  slug: "roman-empire",
  title: "The Roman Empire: a republic that never admitted it had ended",
  sourceTitle: "Roman Empire",
  dek: "Rome's most successful invention was not the arch or the road but a fiction — that nothing had changed.",
  standfirst:
    "Rome never had a coronation. It had a young man named Octavian who ended a civil war, handed his powers back to the Senate in a carefully staged ceremony, and received in return, piece by piece, everything that mattered. The Republic was not abolished. It was left standing, hollow, as a set of offices an emperor could hold all at once.",
  readingMinutes: 9,
  html: `
<h2 id="The_settlement_that_founded_an_empire">The settlement that founded an empire</h2>
<p>The Republic did not fall to a foreign enemy. It was destroyed by its own success — a century of conquest that made individual generals richer than the state, gave them armies loyal to their paymaster rather than to Rome, and left constitutional machinery designed for a city-state trying to govern the Mediterranean.</p>
<p>By 31 BC, after Caesar's assassination and thirteen more years of civil war, Octavian had won. What he did next was more original than winning. Rather than take a crown — the mistake that had got his adoptive father killed — he announced in 27 BC that he was restoring the Republic. The Senate, entirely aware of what was happening and entirely uninterested in objecting, responded by voting him the honorific <em>Augustus</em> and a bundle of specific, individually unremarkable powers: command of the provinces where the legions were stationed, the authority of a tribune, eventually the office of chief priest. Held separately these were traditional. Held together, permanently, by one man, they were monarchy.</p>
<p>Augustus called himself <em>princeps</em>, first citizen. He kept the Senate meeting, the consuls elected, the old titles in circulation. The genius of the arrangement was that it required nobody to admit anything had changed, which is why it lasted three centuries — and why it never solved the one problem it most needed to.</p>

<h2 id="The_flaw_that_never_closed">The flaw that never closed</h2>
<p>An office that officially does not exist cannot have rules for filling it. Rome never established a legal method of imperial succession. Emperors adopted heirs, named sons, or simply designated a successor and hoped, and every transition was a test of whether the army agreed.</p>
<p>The consequences arrived early and never really left. Four emperors fought over the throne in the single year AD 69; the Praetorian Guard, garrisoned in the capital and well placed to make demands, murdered emperors and elevated replacements with growing confidence. In 193 they auctioned the position outright to the highest bidder, who lasted nine weeks.</p>
<p>The third century turned the flaw into a crisis. Between 235 and 284 more than twenty emperors held power, most for a year or two, almost all dying violently. Simultaneously the currency collapsed under repeated debasement, plague swept the provinces, Persian armies captured an emperor alive, and both the Gallic west and the Palmyrene east broke away under their own rulers. The empire came closer to ending in the 260s than it would again for two hundred years.</p>

<h2 id="What_held_it_together">What held it together</h2>
<p>Rome's durability was administrative, not military. Its army was rarely more than a few hundred thousand men for a population of perhaps sixty million — nowhere near enough to hold territory by force. What it had instead was a genuinely unusual willingness to make conquered people into Romans.</p>
<p>Local elites kept their positions, their gods and their languages, and gained access to Roman citizenship, Roman courts and Roman careers. Auxiliary soldiers earned citizenship for their descendants through service. Provincials rose to the Senate, and eventually to the throne: Trajan and Hadrian came from Spain, Septimius Severus from North Africa, Philip from Arabia. In 212 an edict extended citizenship to nearly every free inhabitant of the empire — partly a tax measure, and still a redefinition of what it meant to be Roman that no other ancient state attempted.</p>
<p>Underneath sat the infrastructure that made governing at that distance possible. Eighty thousand kilometres of engineered road, built for legions and used by everyone. Aqueducts feeding cities of a scale Europe would not see again for a millennium. A single currency, a common legal framework, and a Mediterranean cleared of piracy — which mattered more than any of the rest, because moving grain by sea cost a fraction of moving it by land. Egypt and North Africa fed the city of Rome by ship, and the whole imperial economy rested on that water.</p>

<h2 id="Living_in_it">Living in it</h2>
<p>The <em>pax Romana</em> was real and should not be romanticised. Roughly the first two centuries AD saw an unusual absence of large-scale internal war, and with it a flowering of trade, literacy and urban building. It was also an economy in which perhaps a fifth of the population was enslaved, in which the frontier was pacified by campaigns of considerable brutality, and in which most people were subsistence farmers whose lives were untouched by any of the above.</p>
<p>Roman cities were nonetheless remarkable places. Rome itself held around a million people, supported by a grain dole feeding a substantial share of them, apartment blocks several storeys high, public baths, and entertainment on an industrial scale. Concrete — a Roman development, and effectively lost afterwards until the modern era — made the Pantheon's dome possible; it is still the largest unreinforced concrete dome standing.</p>
<p>The empire's culture was frankly derivative and knew it. Rome imported Greek philosophy, literature, medicine and art wholesale, and Horace's line about captive Greece taking its captor captive was a joke that everyone understood. What Rome contributed was its own: law, above all. The distinction between what a citizen owes the state and what citizens owe each other, the machinery of contract and property and inheritance, the idea that legal principles could be systematised and taught — all of it was codified under Justinian in the sixth century and became the foundation of civil law across most of Europe and Latin America.</p>

<h2 id="The_slow_division">The slow division</h2>
<p>Diocletian, taking power in 284, ended the crisis by conceding that the empire was too large for one ruler. He split administration between east and west, each with a senior and junior emperor, and rebuilt the state around a vastly expanded bureaucracy, a larger army and heavier taxation. The tetrarchy collapsed into civil war as soon as he retired, but the division proved permanent in practice.</p>
<p>Constantine reunified the empire, legalised Christianity, and in 330 founded a new capital at Byzantium — Constantinople — positioned on the wealthier, more urbanised, more defensible eastern trade routes. Both decisions outlasted him by more than a thousand years. The empire was formally partitioned in 395 and never reunited.</p>

<h2 id="What_actually_happened_in_476">What actually happened in 476</h2>
<p>The traditional end date is a poor one. In 476 a Germanic commander named Odoacer deposed a teenage emperor in Ravenna and, rather than replace him, sent the imperial regalia to Constantinople with a note observing that one emperor was sufficient. Nothing that contemporaries would have called the fall of Rome occurred that year. The western administration had been failing for decades, its army increasingly composed of federated Germanic groups whose loyalty was contractual, its tax base shrinking as provinces slipped from control, its emperors puppets of their generals.</p>
<p>The causes remain argued over, and the arguments usually reveal more about the arguer than about Rome. Overextension, plague, climate shifts, currency debasement, the pressure of migrations driven by the Huns, the cost of the bureaucracy, and simple political incompetence all have serious advocates. The most defensible answer is that no single cause is needed: a state under simultaneous fiscal, military and demographic strain does not require an explanation for failing, only for lasting as long as it did.</p>
<p>And the eastern half did not fail. It continued, Greek-speaking and calling itself Roman, for another thousand years, until Constantinople fell to Ottoman cannon in 1453 — a date closer to the invention of printing than to Augustus. Rome's afterlife was longer still: the Holy Roman Empire, the Tsars and the Kaisers all took their titles from Caesar, and the architecture of Western legislatures is still, quite deliberately, an argument about Rome.</p>
`,
};
