import type { RewrittenArticle } from "./types";

export const rosettaStone: RewrittenArticle = {
  slug: "rosetta-stone",
  title: "The Rosetta Stone: one priestly decree, three scripts, two decades to read",
  sourceTitle: "Rosetta Stone",
  dek: "The stone repeats a fairly dull decree in three scripts. Reading it took a British polymath, a French prodigy, a rivalry, and a language still heard in Egyptian churches.",
  standfirst:
    "The Rosetta Stone is so famous that its name has become a word for any key to an unknown code. The stone itself is a broken slab of dark rock carrying a decree issued by Egyptian priests in 196 BC. It did not, on its own, unlock Egyptian hieroglyphs. What it did was give two scholars a fixed point to work from, and the story of how they used it is a story about the right idea taking far longer than it should have.",
  readingMinutes: 8,
  published: "2026-10-06",
  html: `
<h2 id="Discovery">Found in a wall</h2>
<p>In July 1799, during Napoleon Bonaparte's invasion of Egypt, French soldiers rebuilding an old fort near the town of Rashid — Rosetta to Europeans — in the Nile Delta found a slab of dark stone built into a wall. An officer, Pierre-François Bouchard, saw that it was inscribed in three different scripts and reported it. Napoleon's expedition included more than a hundred scholars, and copies of the inscription were soon being made and sent to Europe.</p>
<p>When the French army in Egypt surrendered in 1801, the terms required it to hand over the antiquities it had collected, and the stone was shipped to London. It has been in the British Museum since 1802 and is now its most visited object. Painted on its side are the words "Captured in Egypt by the British Army in 1801".</p>

<h2 id="Stone">What it says</h2>
<p>The stone is a fragment of a larger slab of granodiorite, a little over a metre tall and weighing about three-quarters of a tonne. Its top and one corner are missing. The text is a decree issued in 196 BC by a council of priests meeting at Memphis, on the anniversary of the coronation of King Ptolemy V, then about thirteen years old. It lists the king's good deeds — tax remissions, gifts to temples, an amnesty, the defeat of rebels — and in return confirms honours to be paid to him in every temple in Egypt.</p>
<p>The decree ends by ordering that it be inscribed on stone in "sacred, native and Greek characters" and set up in temples throughout the country. That is why the stone is useful. The same text appears three times: in hieroglyphs, the sacred script; in Demotic, the everyday cursive script used for Egyptian at the time; and in Greek, the language of the ruling Ptolemaic dynasty, which scholars could read perfectly well. Only fourteen lines of the hieroglyphic text survive, all incomplete, against thirty-two of Demotic and fifty-four of Greek.</p>

<h2 id="Problem">Why hieroglyphs had been unreadable</h2>
<p>The last known hieroglyphic inscription was carved at the temple of Philae in AD 394. Within a few generations nobody could read the script, and what survived was a misleading idea about it. A late antique writer named Horapollo produced a book explaining hieroglyphs as symbols, each standing for an idea through some allegory: a vulture for a mother, for instance. Some of his meanings were genuine, but the book convinced readers for more than a thousand years that hieroglyphs were a mystical picture-language rather than a way of writing down speech. In the seventeenth century the Jesuit scholar Athanasius Kircher published long, confident and almost entirely imaginary translations based on that assumption.</p>
<p>Kircher did, however, help keep alive one important idea: that Coptic, the language of Egypt's Christians, was the last stage of ancient Egyptian. Coptic was written in an alphabet based on Greek, and although it had stopped being an everyday spoken language centuries earlier, it survived in the liturgy of the Coptic Church, where it is still used. Anyone who knew it knew, in effect, the language of the pharaohs, if only they could connect it to the script.</p>

<h2 id="Young">Thomas Young's first steps</h2>
<p>The first progress came from the Demotic text. In 1802 the French orientalist Silvestre de Sacy and the Swedish diplomat Johan Åkerblad identified proper names such as Ptolemy in it and worked out the sound values of some of its signs. Then, from 1814, the English physician and physicist Thomas Young — already known for showing that light behaves as a wave — took up the problem.</p>
<p>Young made real discoveries. He saw that Demotic and hieroglyphs were related, Demotic signs being simplified forms of hieroglyphs. He confirmed that the oval rings in the hieroglyphic text, called cartouches, enclosed royal names, and he correctly worked out the sound values of several signs in the name of Ptolemy. He published his results in 1819 in an article on Egypt in a supplement to the <em>Encyclopaedia Britannica</em>. But he believed that hieroglyphs were used to spell sounds only for foreign names like Ptolemy, which was Greek. Egyptian words, he thought, were written symbolically. Horapollo's idea still had a grip.</p>

<h2 id="Champollion">Champollion's breakthrough</h2>
<p>Jean-François Champollion, a scholar from Figeac in southern France, had been obsessed with Egypt since childhood and had learned Coptic, along with many other languages, as a young man. In 1822 he compared the cartouche of Ptolemy with another, on an obelisk from Philae whose base carried a Greek inscription naming Cleopatra. The signs for p, o and l appeared in both names exactly where the sounds required. The t of each name was written with a different sign, which told him that the script could spell one sound in more than one way. From names like these he built up a list of phonetic signs.</p>
<p>The decisive step came when he applied them to cartouches copied from much older temples, from long before Greek rule. One began with a circle, the sign for the sun, which in Coptic is <em>re</em>, and ended with two signs he already knew as <em>s</em>: Ramesses. Another began with an ibis, the bird of the god Thoth: Thutmose. These were native Egyptian names, written with a mixture of signs standing for words and signs standing for sounds. The script recorded the Egyptian language, and the language was the ancestor of Coptic.</p>
<p>According to a family story, he ran to his brother's office, announced that he had it, and collapsed. He set out the phonetic signs in a public letter in September 1822 and the full system in 1824: hieroglyphic writing combined sound signs, word signs and silent signs called determinatives that showed what category a word belonged to. That is still the basis of how it is read.</p>

<h2 id="Credit">The quarrel over credit</h2>
<p>Young felt that his own contribution had been brushed aside, and the dispute took on a national edge, British supporters championing Young and French ones Champollion. The fair judgement is that Young made the first correct identifications, and that Champollion, because he knew Coptic and was willing to abandon the old assumption completely, understood how the whole system worked. Champollion finally visited Egypt in 1828 and 1829, reading inscriptions on the spot, and died in 1832 at the age of forty-one.</p>
<p>Other copies of the same decree have since been found, and a different bilingual decree discovered in 1866 confirmed Champollion's readings. The Rosetta Stone itself has become a symbol well beyond Egyptology — a European space mission to a comet in the 2000s was named after it, and its lander after Philae. It is also the subject of a long-running argument about whether it should be returned to Egypt, where many regard it as having been taken in a war that was not Egypt's own. British law currently bars the museum from giving it up.</p>
`,
};
