import type { RewrittenArticle } from "./types";

export const skyscrapers: RewrittenArticle = {
  slug: "skyscrapers",
  title: "Skyscrapers: the limit is wind and lifts, not the weight of the building",
  sourceTitle: "Skyscraper",
  dek: "A tall building can carry its own mass easily. What it struggles with is being pushed sideways, and finding a way to move people up without filling the floors with lift shafts.",
  standfirst:
    "The intuitive constraint on a tall building — that the lower floors will be crushed — is not the real one. Steel and concrete carry vertical load efficiently, and gravity has never been the binding limit. Height is limited by lateral force, because wind load grows faster than height and a slender building will sway uncomfortably long before it is in danger, and by vertical transport, because past a certain height the lifts needed to serve the upper floors consume the floor area that made them worth building.",
  readingMinutes: 8,
  html: `
<h2 id="Two_inventions">The two inventions that were required</h2>
<p>The tall building needed a way to get people up and a way to stop the walls having to hold the building up.</p>
<p>Elisha Otis did not invent the lift, which is ancient. He invented the safety brake, demonstrated at the New York Crystal Palace exhibition in 1854 by having the hoisting rope cut while he stood on the platform. Spring-loaded pawls engaged the guide rails and the platform stopped. The invention was not mechanical convenience but the public credibility of being carried above ground by a rope.</p>
<p>The second was the structural frame. In a masonry building the walls carry the load, and the load accumulates downward, so the walls at the base of a tall masonry building must be enormously thick. The Monadnock Building in Chicago, completed in 1891 at sixteen storeys, has walls roughly 1.8 metres thick at the base — a demonstration of the method's limit, since those walls occupy rentable ground-floor space at the most valuable point in the building.</p>
<p>The metal frame moves the load into a skeleton of columns and beams, and the wall becomes a curtain hung on it, carrying only itself and the wind. The Home Insurance Building in Chicago of 1885 is conventionally credited as the first, and the attribution is disputed in detail, as most firsts of this kind are. What is not disputed is that within a decade the frame was standard and the exterior wall had stopped being structural.</p>
<p>Chicago's role owes something to a fire. The 1871 fire cleared the centre of a rapidly growing city with expensive land, concentrating capital, demand and a generation of engineers in one place at the moment the technique became available.</p>

<h2 id="Wind">Why sideways is the problem</h2>
<p>A tall building is a vertical cantilever, fixed at the ground and free at the top, and wind load on it produces a bending moment at the base that grows roughly with the square of the height — the force increases with the exposed area, and the lever arm increases too.</p>
<p>The governing criterion is usually not strength but comfort. Occupants notice sway, and they notice acceleration rather than displacement; a building can move a substantial distance slowly without complaint and a small distance quickly with a great deal of it. Design targets are expressed in accelerations that people will tolerate in a windstorm of a given return period, and they are strict, because people in a swaying building become nauseated and frightened well before anything structural is at risk.</p>
<p>The other lateral force is seismic, and it differs from wind in an important way: wind pushes on the surface, whereas an earthquake moves the ground and the building's own mass resists moving. Wind design rewards low surface area; seismic design rewards low mass and ductility. A building optimised for one is not automatically good for the other.</p>
<p>Two broad strategies address wind. Stiffen the structure — the tube systems developed by Fazlur Rahman Khan from the 1960s treat the entire perimeter as a hollow cantilever rather than relying on interior bracing, which is enormously more efficient in material and made the John Hancock Center and the Sears Tower possible. Khan's bundled tube for the latter groups nine tubes that terminate at different heights, which both reduces material and produces the setback profile.</p>
<p>Or confuse the wind. The dominant dynamic load on a tall building is often not steady pressure but vortex shedding — alternating vortices peeling off each side, pushing the building crosswise at a regular frequency, which is dangerous if that frequency approaches the building's own. The countermeasure is to vary the cross-section with height so the shedding frequency never organises: the Burj Khalifa's setbacks spiral around the tower for this reason, and Shanghai Tower's twist does the same, with reported reductions in wind load of a fifth or more. The openings through the upper part of some towers serve the same purpose.</p>

<h2 id="Dampers">Adding mass to reduce movement</h2>
<p>Where stiffness is insufficient or uneconomic, the movement is damped instead.</p>
<p>A tuned mass damper is a large weight mounted near the top of the building on springs or pendulum cables, tuned to the building's natural frequency and coupled through a damping medium. When the building sways one way the mass lags behind, and the force it exerts through the connection opposes the motion. It does not make the building stronger; it converts sway into heat.</p>
<p>Taipei 101's is the well-known example, a steel sphere of around 660 tonnes hung as a pendulum and left visible to visitors. Others use fluid instead: a tuned liquid damper is a tank of water whose sloshing period matches the building's, which is cheap and requires the tank to be exactly the right shape.</p>
<p>The Citicorp Center in New York used one of the first, and its story is the standard case study in engineering ethics. The building was completed in 1977 on four columns placed at the midpoints of its sides rather than the corners, to straddle a church. In 1978, after a student's query prompted him to recheck, the engineer William LeMessurier found that a change made during construction — bolted rather than welded joints — combined with quartering winds striking the corners, which his original calculations had not covered, left the building vulnerable to a storm of a probability far higher than acceptable. Its tuned mass damper depended on electrical power, which a storm could remove. Emergency welding was carried out at night over several months while the building remained occupied, a hurricane approached and was tracked, and the matter stayed out of the press partly because of a newspaper strike. It became public in 1995.</p>

<h2 id="Lifts">The floor area problem</h2>
<p>Every lift needs a shaft, and a shaft passes through every floor below the one it serves whether or not it stops there. Add floors and you add lifts, and the shafts eat the building from the inside.</p>
<p>Past a certain height, an additional storey generates less rentable area than the transport it requires consumes. That is the real economic ceiling, and it was reached in principle long before the structural one.</p>
<p>The solutions are all about not running every lift the whole way. Sky lobbies, introduced at the World Trade Center, divide the building into vertical zones: express lifts run to a transfer floor, from which local lifts serve the zone, so multiple local shafts occupy the same footprint in different zones. Double-decker cars serve two floors per stop. Destination dispatch, where passengers enter a floor number in the lobby and are allocated a car, groups passengers by destination and substantially reduces stops.</p>
<p>Rope weight sets a hard limit on a single hoist: a conventional steel-roped lift cannot economically exceed roughly half a kilometre because the rope's own mass dominates. Carbon-fibre belts, introduced in the 2010s, roughly double the practical single run, which is why some recent towers have lifts that go much further without transfer.</p>
<p>Supertall towers face a further diminishing return. As buildings become very slender the upper floors shrink, structure and services take a larger share, and the topmost portion of many record-height towers is unoccupiable — a spire or a vanity structure counted in the official height. The Council on Tall Buildings and Urban Habitat maintains criteria for this, distinguishing height to architectural top from height to the highest occupied floor, and the gap in some towers exceeds a hundred metres.</p>

<h2 id="Why">What they are actually for</h2>
<p>The standard justification is land value: where a site is expensive, building upward multiplies the return on it.</p>
<p>The economics are less automatic than that. Construction cost per square metre rises with height — more structure, more lifts, more complex logistics, longer schedules — so the additional floors must earn a premium to justify themselves. Studies of tall building economics generally find a height beyond which the marginal floor loses money, and that height is well below the tallest buildings actually built.</p>
<p>Which means the tallest towers are usually not straightforward property investments. They are built for prestige, for national or corporate signalling, or as the anchor of a larger development whose surrounding land value they raise. The recurring observation that record-breaking towers are commissioned near the top of a credit cycle, and completed after it turns, is anecdotally striking and statistically weak, but it points at something real: the buildings that break records are the ones whose sponsors were not primarily counting the rent.</p>
<p>The genuinely useful case for height is different and less glamorous. Moderate density — buildings of five to fifteen storeys, built continuously — delivers most of the transport, energy and land-use benefits of urban concentration at far lower cost per unit than supertall construction. The tallest towers are impressive engineering and, as a means of housing people efficiently, are among the less efficient options available.</p>
`,
};
