import type { RewrittenArticle } from "./types";

export const spores: RewrittenArticle = {
  slug: "spores",
  title: "Spores: launched by the trillion, and a few of them have rewritten whole landscapes",
  sourceTitle: "Spore",
  dek: "A single large fungus releases billions of spores a day. The strategy is to make dispersal so cheap that vanishingly small odds still work.",
  standfirst:
    "A spore is a single cell built to survive transit and to start a new organism on arrival, and the organisms that use them do so in numbers that make individual survival irrelevant. The arithmetic is severe: almost every spore lands somewhere useless and dies. What makes the strategy work is that the cost per spore is negligible, and the consequences when one does land well have included the loss of entire tree species from continents and a famine that emptied a country.",
  readingMinutes: 7,
  html: `
<h2 id="Numbers">The scale of the gamble</h2>
<p>A mature bracket fungus or a large mushroom releases spores continuously for days or weeks, at rates measured in the billions per day. A single giant puffball is estimated to contain spores numbering in the trillions.</p>
<p>Practically none of them succeed. The spore must land on a suitable substrate, at a suitable moisture level, without being eaten, at a time when it can germinate, and in most species without a compatible mating partner nothing further happens either. The probability for any individual spore is effectively zero, and the strategy is viable because producing one costs almost nothing.</p>
<p>This is a different reproductive logic from the one animals use, and it has a name — an enormous number of minimally provisioned propagules, against a small number of heavily provisioned ones. Ferns, mosses, fungi and many microorganisms all sit at the extreme end of it.</p>
<p>Fungal spores are also durable in a way that gametes are not. Many survive desiccation, temperature extremes and years of dormancy, waiting for conditions. That combination — cheap, numerous, tough and patient — is what makes fungal colonisation of new material so reliably fast.</p>

<h2 id="Launch">Getting off the ground</h2>
<p>Releasing a spore into still air near a surface achieves nothing, because the boundary layer of stationary air next to any object will simply hold it there. Getting through that layer has produced some remarkable mechanisms.</p>
<p>The basidiomycete mushrooms — the familiar gilled ones — use a mechanism called ballistospory that was only properly explained in recent decades. A droplet of fluid condenses at the base of the spore, suddenly merges with a film on the spore's surface, and the abrupt shift in the centre of mass flings the spore away from the gill. The launch accelerations are enormous and the distance is tiny, perhaps a tenth of a millimetre — just far enough to clear the gill surface and drop into the free air below the cap.</p>
<p>This explains the geometry of a mushroom. The gills must hang vertically for the spore to fall clear, which is why mushrooms are so precise about orientation and why a knocked-over mushroom reorients its cap and gills as it continues to grow.</p>
<p>Other groups use pressure. Some ascomycetes build up turgor and fire spores from an ascus at accelerations among the highest known in biology. The fungus <em>Pilobolus</em>, which grows on herbivore dung, aims a pressurised sporangium at the light and fires it several metres — far enough to clear the ring of grass that animals avoid grazing near dung, so the spores land on clean grass, are eaten, pass through the animal and arrive in fresh dung. The entire mechanism exists to solve one specific geometric problem.</p>
<p>Puffballs take the opposite approach and rely on external energy, releasing a cloud when struck by a raindrop. Stinkhorns dispense with air altogether, producing a foul-smelling spore slime that flies carry away.</p>

<h2 id="Air">The atmosphere is full of them</h2>
<p>The air spora — the population of biological particles suspended in the atmosphere — is a genuine and constantly present component of air. Spore concentrations outdoors routinely exceed pollen concentrations by a large margin, seasonally and geographically variable.</p>
<p>They travel. Viable fungal spores have been collected at high altitude and far out over oceans, and long-distance transport events are documented, including transatlantic movement of plant pathogen spores in dust plumes. There is good evidence that some spores act as ice nucleation particles, and biological aerosols contribute to cloud formation, which places fungi in the weather system.</p>
<p>For humans the immediate consequence is allergy. <em>Alternaria</em> and <em>Cladosporium</em> spores are major outdoor aeroallergens, and sensitisation to <em>Alternaria</em> in particular is associated with severe asthma; thunderstorm asthma events, in which a storm ruptures airborne particles into smaller respirable fragments, involve both pollen and fungal spores.</p>
<p>Occupational exposure produces a distinct disease. Repeated inhalation of large quantities of spores from mouldy hay, grain or compost causes hypersensitivity pneumonitis — farmer's lung — which is an immune reaction to the spores rather than an infection, and which becomes irreversible if exposure continues.</p>

<h2 id="Pathogens">When one spore lands well</h2>
<p>The consequences of successful fungal dispersal are among the largest biological changes of the last two centuries, because the pathogens were moved between continents by people.</p>
<p><strong>Potato blight.</strong> <em>Phytophthora infestans</em> is an oomycete rather than a true fungus, which is a real taxonomic distinction and made no difference to Ireland. Arriving in Europe in the 1840s, it destroyed a crop grown as a genetically narrow monoculture and central to subsistence. Roughly a million people died and a million more emigrated, and Ireland's population has never returned to its pre-famine level. Its spores spread by wind and rain in cool, damp conditions — precisely Irish summer weather.</p>
<p><strong>Chestnut blight.</strong> Introduced to North America around 1904 on imported nursery stock, it killed an estimated three to four billion American chestnuts within a few decades. The species had been a dominant canopy tree across the eastern forests and a major food source for wildlife and people. It survives as root sprouts that are killed back before maturity, making it functionally extinct as a forest tree while remaining alive as a species.</p>
<p><strong>Dutch elm disease</strong>, spread by bark beetles carrying spores, removed elms from British and North American landscapes across the twentieth century in two waves, the second caused by a more aggressive strain. <strong>Ash dieback</strong> is repeating the pattern in Europe now.</p>
<p><strong>Wheat rusts</strong> remain a live threat to food supply. The Ug99 stem rust lineage, identified in Uganda in 1998, overcame widely deployed resistance genes and spread across Africa and into the Middle East, prompting an international breeding effort. Rust spores travel on wind over continental distances, which makes containment impossible and resistance breeding the only defence.</p>

<h2 id="Manipulation">The spores that steer their carrier</h2>
<p>A small group of fungi have solved dispersal by taking control of an animal's behaviour, and the results are well enough documented to be uncomfortable.</p>
<p><em>Ophiocordyceps unilateralis</em> infects carpenter ants in tropical forests. An infected ant leaves its colony, climbs vegetation to a characteristic height, and clamps its mandibles onto a leaf vein — the death grip — where it dies. A stalk then grows from its head and releases spores onto the foraging trails below.</p>
<p>The precision is what is striking. Infected ants converge on a consistent height and orientation, corresponding to conditions favourable for fungal growth, and fossil evidence of the same characteristic bite damage on leaves has been dated to around 48 million years ago. Analysis has found that the fungus does not invade the brain but surrounds and manipulates the muscles directly, which is a stranger mechanism than the obvious one.</p>
<p><em>Massospora</em> infects cicadas, replaces part of the abdomen with a spore mass, and induces hypersexual behaviour that spreads the infection through mating attempts; the fungus produces compounds including an amphetamine. <em>Entomophthora muscae</em> makes houseflies climb, adopt a raised posture and die in a position that scatters spores widely, and manipulates other flies into mating with the corpse.</p>
<p>These are the ancestral inspiration for a familiar fictional scenario, and the reason it stays fictional is straightforward: these fungi are exquisitely specialised to single insect hosts, and they cannot function at mammalian body temperature. Endothermy is generally regarded as a substantial defence against fungal infection, which is one hypothesis for why mammals have relatively few fungal pathogens compared with insects and plants — and why a warming climate, selecting for fungi tolerant of higher temperatures, is watched with some care.</p>
`,
};
