import type { RewrittenArticle } from "./types";

export const theLiver: RewrittenArticle = {
  slug: "the-liver",
  title: "The liver: it grows back, and it decides how much of your medicine you actually get",
  sourceTitle: "Liver",
  dek: "Everything absorbed from the gut goes through the liver before reaching the rest of the body. Some drugs lose most of their dose there, which is why the tablet is bigger than the injection.",
  standfirst:
    "The liver occupies a position no other organ has: the entire blood supply from the intestines passes through it before entering the general circulation. That arrangement makes it the body's chemical processing plant and its customs post, and it explains two facts that otherwise look unrelated — why oral drug doses differ so much from injected ones, and why liver damage produces symptoms in the brain, the blood and the skin at once.",
  readingMinutes: 7,
  html: `
<h2 id="Portal">The plumbing that explains everything else</h2>
<p>Most organs receive arterial blood and return it to the heart. The liver receives two supplies: an artery, and the portal vein, which carries blood that has already passed through the stomach, intestines, pancreas and spleen. Roughly three-quarters of the liver's blood arrives by this second route, oxygen-poor and loaded with whatever has just been absorbed.</p>
<p>This means nothing eaten reaches the rest of the body without inspection. Nutrients are taken up, stored or converted; toxins absorbed from gut contents are dealt with; bacteria that cross the intestinal wall meet a dense population of resident immune cells before reaching anywhere that matters.</p>
<p>The tissue is arranged to exploit this. Blood percolates through sinusoids — leaky capillaries lined with fenestrated cells — past sheets of hepatocytes one or two cells thick, so essentially every liver cell is in direct contact with the incoming blood, with no barrier of the kind that separates blood from tissue elsewhere. The liver is built to maximise exposure rather than to control it.</p>
<p>Cells at different points along the flow do different work, because oxygen and nutrient concentration fall as blood travels. Those near the incoming vessels handle oxidative metabolism and gluconeogenesis; those near the outflow handle drug metabolism and glycolysis. This zonation is why particular toxins damage particular rings of tissue and why the pattern of injury on a biopsy is diagnostic.</p>

<h2 id="First_pass">First pass, and why doses differ</h2>
<p>A drug swallowed is absorbed into the portal vein and passes through the liver before reaching the circulation. Whatever the liver metabolises on that first transit never reaches the target.</p>
<p>The effect ranges from negligible to nearly total. Some drugs lose the overwhelming majority of an oral dose this way, which is why the tablet strength is many times the intravenous one, and why a few drugs cannot be given orally at all. Glyceryl trinitrate is placed under the tongue precisely to bypass the portal system, since swallowing it would destroy it. Suppositories partially avoid it too, because the lower rectum drains to the general circulation.</p>
<p>The metabolism is done chiefly by the cytochrome P450 enzymes, a family whose members handle overlapping ranges of substrates. Two facts about them account for a large share of clinical pharmacology.</p>
<p>They vary between people. Genetic variation in these enzymes means individuals metabolise the same drug at very different rates — poor metabolisers accumulate it, ultrarapid metabolisers clear it before it works, and for a few drugs this determines whether a standard dose is therapeutic, useless or dangerous.</p>
<p>And they are inhibited and induced by other substances. One drug can block the enzyme that clears another, raising its concentration into toxicity; another can induce more enzyme, lowering a second drug below effect — which is the mechanism by which St John's wort undermines several important medicines. Grapefruit juice is the standard example of inhibition, and it works because a component blocks an enzyme in the gut wall and liver that would otherwise limit absorption of certain drugs.</p>
<p>The general logic of the chemistry is worth stating: the liver's job is to make lipid-soluble compounds water-soluble so the kidney can excrete them. It does this in two phases, first adding a reactive group, then attaching a bulky water-soluble molecule. Phase one frequently produces an intermediate more reactive than the original, which is why some drugs are toxic only through their metabolites — and why some drugs are given as inactive precursors and switched on by the liver deliberately.</p>

<h2 id="Regeneration">The organ that grows back</h2>
<p>The liver is the only internal human organ with substantial regenerative capacity. Remove a large fraction and the remainder grows until the original mass is restored, over weeks.</p>
<p>This is not regeneration in the sense of regrowing a lost lobe with its original shape. The remaining tissue enlarges by cell division until total mass and function are restored, leaving the anatomy altered. That is sufficient for the clinical purposes it is used for: living donor transplantation, in which part of a healthy person's liver is removed and both the donor's remnant and the graft grow to adequate size, and major cancer surgery, which can remove a substantial portion of the organ with the expectation of recovery.</p>
<p>The trigger appears to be functional demand rather than injury — the remaining tissue senses that it is doing too much work per cell, through portal blood flow and bile acid signalling among other routes — and division stops when the required mass is reached, which is the harder and less understood half of the mechanism.</p>
<p>The capacity has a limit, and the limit is the crux of chronic liver disease. Repeated injury over years produces fibrosis, scar tissue laid down by activated stellate cells, and eventually cirrhosis, in which the architecture is replaced by nodules surrounded by scar. Regeneration continues but the structure is wrong: blood cannot flow through the scarred tissue properly, and the hepatocytes have lost their relationship to the sinusoids. Early fibrosis is reversible if the cause is removed; established cirrhosis largely is not.</p>

<h2 id="Failure">What fails when the liver fails</h2>
<p>Because the liver does so many unrelated jobs, its failure presents as a collection of apparently unconnected problems.</p>
<p>It makes most plasma proteins, so failure causes low albumin, and low albumin allows fluid to leave the circulation — producing the swelling and the abdominal fluid that characterise advanced disease. It makes almost all the clotting factors, so failure causes bleeding, and the prothrombin time is one of the better real-time measures of how much synthetic capacity remains.</p>
<p>It clears bilirubin, the breakdown product of haemoglobin, by conjugating it for excretion in bile. Failure at any point in that path causes jaundice, and the pattern of which form of bilirubin accumulates distinguishes a problem inside the liver from a blocked bile duct.</p>
<p>It converts ammonia from protein metabolism into urea. When it cannot, ammonia and related compounds reach the brain and cause hepatic encephalopathy — confusion, altered sleep, a characteristic tremor, and eventually coma. A person can become disoriented because of an organ in the abdomen, which is not intuitive unless the portal circulation is kept in mind.</p>
<p>Cirrhosis adds a mechanical problem. Scarred tissue obstructs portal flow, pressure rises behind it, and blood finds alternative routes to the heart through small veins that were never meant to carry it — most dangerously at the lower oesophagus, where the resulting varices can rupture and bleed catastrophically.</p>
<p>The common causes are alcohol, viral hepatitis, and increasingly metabolic dysfunction associated with obesity and insulin resistance, now the fastest-growing cause in many countries. Paracetamol deserves its own mention as the leading cause of acute liver failure in several: at normal doses a minor reactive metabolite is neutralised by glutathione, and in overdose glutathione is exhausted and the metabolite destroys the tissue. The antidote works by replenishing glutathione, and it works well if given early — which is the recurring theme of liver medicine, since an organ this good at repairing itself mostly needs the injury to stop.</p>
`,
};
