import type { RewrittenArticle } from "./types";

export const theNervousSystem: RewrittenArticle = {
  slug: "the-nervous-system",
  title: "The nervous system: the signal is slow, leaky and chemical at every junction",
  sourceTitle: "Nervous system",
  dek: "Nerve impulses travel at a fraction of the speed of electricity in a wire, and at every gap the message stops and is retransmitted by squirting molecules across.",
  standfirst:
    "Describing nerves as electrical wiring is misleading in almost every respect. The signal is a travelling collapse of a chemical gradient, it moves at speeds comparable to a car rather than to electricity, it is regenerated at intervals because it would otherwise fade, and at each junction between cells it is converted into a puff of molecules and back again. The apparent inefficiency buys the one thing a wire cannot offer: every junction is a place where the signal can be modified.",
  readingMinutes: 8,
  html: `
<h2 id="The_impulse">What an impulse actually is</h2>
<p>A neuron at rest maintains an imbalance of ions across its membrane, with the inside negative relative to the outside, held there by pumps that spend a substantial fraction of the body's entire energy budget doing it.</p>
<p>An action potential is the local, brief collapse of that imbalance. Voltage-gated sodium channels open, sodium rushes in, the membrane potential swings positive, the channels inactivate, potassium leaves, and the resting state is restored. The whole event lasts about a millisecond and involves the movement of a tiny fraction of the available ions — the gradient is barely dented by a single spike.</p>
<p>The spike does not travel like a current in a wire. It regenerates: the depolarisation at one point brings the adjacent patch of membrane to threshold, which fires in turn. This is why the signal does not weaken over distance the way a passive electrical signal in a leaky cable would, and it is why conduction is slow — each segment must go through the full cycle.</p>
<p>Speeds range from under a metre per second in the thinnest unmyelinated fibres to well over a hundred in the largest myelinated ones. Even the fastest is around a millionth of the speed of an electrical signal in copper. Reaction times follow directly: the delay between a stimulus and a response is dominated by conduction and synaptic transmission time, and it is why a person stepping on something sharp withdraws the foot through a spinal reflex before the brain is informed.</p>
<p>The signal is also all-or-nothing, which means intensity cannot be encoded in amplitude. It is encoded in rate and in which fibres are firing — a bright light produces faster spikes, not bigger ones.</p>

<h2 id="Myelin">The insulation trick</h2>
<p>Conduction speed in a bare axon rises with diameter, and only with the square root of it, which is a poor return. The squid giant axon is about a millimetre across and conducts at perhaps twenty-five metres a second; scaling that approach up to a human nervous system would require a spinal cord of impossible size.</p>
<p>Vertebrates solved it differently. Myelin, a wrapping of many layers of cell membrane laid down by specialised glial cells, insulates the axon along most of its length and forces the current to jump between the gaps in the sheath, where the sodium channels are clustered. The impulse regenerates only at those nodes, skipping the insulated stretches, which raises speed by an order of magnitude at a fraction of the diameter and a fraction of the energy.</p>
<p>The dependence on this arrangement is the reason demyelinating disease is so disabling. In multiple sclerosis the immune system attacks myelin in the central nervous system, and conduction slows, becomes unreliable, or fails entirely — with symptoms determined by which tracts are affected rather than by any single characteristic deficit.</p>
<p>Myelination in humans is incomplete at birth and continues for a long time, with the frontal regions among the last to finish, well into the third decade. That timeline is invoked frequently and loosely in discussions of adolescent behaviour, and what it actually supports is narrower: the physical substrate of long-range coordination is still being installed for years after a person is otherwise physically adult.</p>

<h2 id="Synapse">The gap, and why it is there</h2>
<p>At the end of an axon the signal stops. Voltage-gated calcium channels open, vesicles fuse with the membrane, and neurotransmitter molecules diffuse across a gap of a few tens of nanometres to bind receptors on the next cell.</p>
<p>This is slower than a direct electrical connection — such connections exist, as gap junctions, and are used where speed matters more than anything else — and it introduces a delay of well under a millisecond at every junction. Since a signal may cross many synapses on its way anywhere, the delays add up.</p>
<p>What is bought is control. At a chemical synapse the signal can be amplified or attenuated; it can be inhibitory rather than excitatory, depending only on which receptor is present; the strength of the connection can be changed by use, which is the physical basis of learning; and the whole junction is open to modulation by other cells and by circulating substances.</p>
<p>It is also the point at which the system can be interfered with, which is why essentially every drug that acts on the nervous system acts at a synapse. Anaesthetics, antidepressants, opioids, stimulants, nerve agents, nicotine, caffeine and alcohol all work by altering transmission at a junction rather than by affecting conduction along an axon. The local anaesthetics are the exception that proves the rule: they block sodium channels directly, and they must be injected at the site because a systemic dose would stop the heart.</p>
<p>A neuron typically receives thousands of synaptic inputs, some excitatory, some inhibitory, and it fires only if their sum at the initial segment crosses threshold. Every cell is therefore performing a continuous weighted vote, and inhibition accounts for a large share of the traffic — much of what a nervous system does is prevent things from happening.</p>

<h2 id="Divisions">The parts that run without asking</h2>
<p>The conventional division into central and peripheral is anatomical. The functionally interesting division is between what is under voluntary control and what is not.</p>
<p>The autonomic system regulates the viscera, and its two branches are usually described as opposites — sympathetic for exertion, parasympathetic for rest — which is serviceable and slightly wrong, since the two are not simple antagonists and many organs receive only one. The vagus nerve alone accounts for a large share of parasympathetic outflow, reaching the heart, lungs and most of the digestive tract, and the majority of its fibres are afferent, carrying information up from the organs rather than commands down to them. The traffic between body and brain runs mostly in the direction that receives least attention.</p>
<p>The gut has a nervous system of its own. The enteric system contains a number of neurons comparable to the spinal cord's, is organised in its own networks in the intestinal wall, and coordinates the movements and secretions of digestion autonomously — an isolated segment of intestine will still propagate a peristaltic wave. It is connected to the brain and does not require it, which is the sense in which the popular phrase about a second brain is defensible.</p>

<h2 id="Repair">Why some nerves recover and others do not</h2>
<p>A cut peripheral nerve can regrow. The axon segment beyond the injury degenerates, the supporting Schwann cells survive and form a guiding channel, and the axon regrows along it at roughly a millimetre a day — slow enough that a serious injury takes months to a year, and imperfect enough that the fibres frequently reach the wrong destinations, which is why recovered sensation is often misplaced.</p>
<p>A cut axon in the brain or spinal cord does not regrow, and the reason is not that the neuron cannot. Transplant experiments established decades ago that central neurons will grow into peripheral nerve tissue if given the chance. The obstacle is the environment: central myelin contains proteins that actively inhibit axon growth, and the scar formed after injury presents further inhibitory molecules.</p>
<p>Why the central nervous system should actively prevent its own repair is a genuine question, and the usual answer is that a mature circuit whose connections were laid down developmentally may be better served by stability than by axons wandering into new and possibly wrong positions. Whatever the reason, it is the basic fact behind the permanence of spinal cord injury, and the several strategies aimed at it — blocking the inhibitory signals, bridging the gap, transplanting cells, and bypassing the injury electronically — all address it directly.</p>
`,
};
