import type { RewrittenArticle } from "./types";

export const theEye: RewrittenArticle = {
  slug: "the-eye",
  title: "The eye: wired backwards, with a hole in the middle, and it works anyway",
  sourceTitle: "Eye",
  dek: "Light in the vertebrate retina passes through the nerves and blood vessels before reaching the cells that detect it, and the wiring exits through a gap in the sensor.",
  standfirst:
    "The vertebrate eye is regularly offered as the model of exquisite design, and its central arrangement is one no engineer would choose: the photoreceptors face away from the light, so every photon crosses a layer of neurons and capillaries first, and the nerve fibres those receptors feed have to pass back through the retina to leave, producing a blind spot. Octopuses have the same camera eye built the sensible way round, which shows the arrangement is not a physical necessity. It is a historical accident that the rest of the system compensates for.",
  readingMinutes: 7,
  html: `
<h2 id="Inverted">The retina is inside out</h2>
<p>In a vertebrate retina the light-sensitive outer segments of the rods and cones point away from the incoming light, toward the back of the eye. Light must therefore pass through the ganglion cells, the bipolar cells and the retinal blood supply before it reaches anything that can detect it.</p>
<p>The nerve fibres carrying the signal collect on the inner surface and must then get out, which they do by passing through a hole in the retina — the optic disc. There are no photoreceptors there, so each eye has a blind spot of appreciable size a little to the nasal side of the fovea.</p>
<p>Cephalopod eyes are superficially similar camera eyes with a lens, an iris and a retina, and they are built the other way round: receptors facing the light, nerves leaving from behind, no blind spot. The two are a standard example of convergent evolution, arriving at the same optical solution from different starting points, and the comparison is what makes the vertebrate arrangement clearly contingent rather than required.</p>
<p>The reason is developmental. The vertebrate retina forms as an outgrowth of the brain, and its layers end up in the order that outgrowth produces. Once established, the arrangement cannot be reversed by any small change, because every intermediate stage would have to remain a working eye.</p>
<p>The compensations are extensive and effective. The fovea, where acuity is highest, has the overlying layers pushed aside to form a pit, so light reaches the cones there almost directly. Müller cells, which span the retina, act as living optical fibres that funnel light through the intervening tissue to the receptors. And the blind spot is filled in by the visual system, using information from the other eye and from the surrounding image, so convincingly that it took until 1660 for anyone to notice it — Edme Mariotte, who found it by experiment and reported it as a curiosity.</p>

<h2 id="Receptors">Rods, cones, and the third kind</h2>
<p>Rods are extremely sensitive — a dark-adapted rod responds to a single photon — and there are on the order of a hundred million of them, concentrated away from the centre. They saturate in daylight and are useless for colour, since there is only one type and a single receptor cannot distinguish wavelength from intensity.</p>
<p>Cones are far less sensitive, number a few million, and cluster densely at the fovea. They come in three types in most humans, and they are what daylight vision is made of.</p>
<p>The consequences of that distribution are things people notice without explanation. Peripheral vision has poor detail and poor colour but excellent motion sensitivity. Faint stars are easier to see slightly off to one side, because looking directly at them puts their light on the cone-rich fovea where the rods are scarce. And dark adaptation takes about half an hour, because it depends on regenerating the visual pigment in the rods.</p>
<p>A third class of photoreceptor was identified only in the 1990s: intrinsically photosensitive retinal ganglion cells containing melanopsin, which respond slowly to short-wavelength light and project not to the visual cortex but to the circadian and pupillary systems. They contribute little or nothing to seeing and are how light sets the body clock, which is why some people who are cortically blind still entrain normally.</p>

<h2 id="Focus">Getting the image sharp, and losing the ability</h2>
<p>Most of the eye's focusing power is not in the lens at all. It is at the cornea, where light passes from air into tissue and the change in refractive index is large. The lens supplies a smaller share, and its value is that it is adjustable.</p>
<p>Accommodation works by a mechanism that reads backwards. The lens is elastic and would relax into a fatter, more powerful shape; it is held stretched flat by tension in the zonular fibres. To focus close, the ciliary muscle contracts, which <em>releases</em> that tension and lets the lens round up. The muscle works to look at something near and rests to look at the distance.</p>
<p>The lens stiffens progressively through life, and by the mid-forties it can no longer round up enough for reading distance. Presbyopia is universal, occurs on a schedule, and is a property of the material rather than a disease. It is the reason reading glasses exist and the reason spectacles mattered so much to the skilled trades.</p>
<p>Refractive errors are separate and are mostly about the shape of the eyeball rather than the lens. Myopia results from an eye that is too long for its optics, so distant images focus in front of the retina. Its prevalence has risen sharply over recent decades, particularly in parts of East Asia, and the best-supported environmental factor is not close work as such but time spent outdoors in childhood — bright light appears to regulate axial growth, plausibly through retinal dopamine, and trials adding outdoor time have reduced incidence.</p>

<h2 id="Processing">The retina computes before anything leaves it</h2>
<p>The optic nerve carries about a million fibres from something over a hundred million receptors, which is a compression of roughly a hundred to one. What travels to the brain is not an image.</p>
<p>The retina extracts differences. Its output cells have centre-surround receptive fields: a cell is excited by light in a small central region and inhibited by light in the ring around it, so it reports local contrast and is nearly silent under uniform illumination. Different ganglion cell types report motion in particular directions, or edges, or changes over time.</p>
<p>This is why so many classic visual effects are retinal rather than cognitive. Mach bands, the illusory light and dark stripes at the boundary between two shades, fall directly out of lateral inhibition. Afterimages follow from receptor adaptation.</p>
<p>Discarding absolute brightness is also what makes vision work across the enormous range of natural light levels. The illumination between a moonlit night and a bright noon differs by many orders of magnitude, and no sensor could encode that range directly. Reporting ratios rather than absolute values sidesteps the problem, and it is the reason a sheet of paper looks white indoors and outdoors despite reflecting vastly different amounts of light.</p>

<h2 id="Evolution">How it was assembled</h2>
<p>The complex eye was Darwin's own stated difficulty, and he addressed it directly: the question is not whether a complete eye could arise at once, but whether a graded series of intermediates each conferred advantage.</p>
<p>The series is well populated by living organisms. A patch of photosensitive cells detects light and dark, which is enough to know night from day and to detect a shadow overhead. Cupping the patch gives crude directionality, since the walls shade some receptors. Deepening the cup narrows the aperture until it forms a pinhole, which produces a genuine image, dim but real — the nautilus has exactly this, an open pinhole eye with no lens. Covering the aperture protects it, and any transparent covering with a refractive gradient improves brightness, giving a lens.</p>
<p>Nilsson and Pelger's modelling in 1994 estimated the number of generations needed for such a sequence under conservative assumptions about the size of each improvement, and arrived at a figure small on geological timescales — of the order of a few hundred thousand generations.</p>
<p>The genetic evidence adds a further point. Eyes across the animal kingdom, however different in construction, share deep control genes, and opsins — the light-sensitive proteins — belong to one ancient family. Eyes have been built in many independent forms, and they were built with the same toolkit.</p>
`,
};
