import type { RewrittenArticle } from "./types";

export const titanic: RewrittenArticle = {
  slug: "titanic",
  title: "Titanic: the ship that sank within the rules",
  sourceTitle: "Titanic",
  dek: "The Titanic carried more lifeboats than British law required. That fact, more than the iceberg, is why its loss rewrote the regulation of the sea.",
  standfirst:
    "The Titanic is remembered as a story about arrogance: a ship called unsinkable, driven too fast through ice. Some of that is true. But the inquiries that followed found something more uncomfortable. Almost everything that killed more than fifteen hundred people on the night of 14 April 1912 was legal, customary, or both — and the response was not to punish anyone but to change the rules for every ship afloat.",
  readingMinutes: 8,
  published: "2026-10-06",
  html: `
<h2 id="Two_and_a_half_hours">A collision, then two and a half hours</h2>
<p>The Titanic left Southampton on 10 April 1912 on its maiden voyage, called at Cherbourg and at Queenstown in Ireland, and set out across the North Atlantic for New York. Built by Harland and Wolff in Belfast for the White Star Line, it was, with its near-identical sister the Olympic, the largest ship in the world.</p>
<p>During 14 April the ship's wireless operators received a series of ice warnings from other vessels. Not all of them reached the bridge. The ship held its speed of about 22 knots into the night, which was then normal practice on the route: liners kept to schedule and relied on lookouts to spot ice in time. At about 11.40 pm, ship's time, the lookouts saw an iceberg dead ahead. The ship turned, but not far enough, and the berg scraped along the starboard side below the waterline.</p>
<p>There was no great gash. The impact buckled plates and sprang seams along roughly ninety metres of the hull, enough to let the sea into the forward compartments. The Titanic had sixteen watertight compartments and could stay afloat with any two, or the first four, flooded. Five or six were open. Because the transverse bulkheads did not extend to the top of the hull, water filled each compartment, pulled the bow down, and spilled over into the next. Thomas Andrews, the shipyard's managing designer, who was aboard, told Captain Edward Smith that the ship would sink within an hour or two. It went down at about 2.20 am.</p>

<h2 id="Lifeboats">Legal, and fatally short</h2>
<p>There were about 2,200 people on board and lifeboat places for 1,178. That shortfall did not break the law. British Board of Trade rules, last revised in 1894, scaled the number of lifeboats a ship had to carry by its tonnage — but the table stopped at ships of 10,000 tons and over, which needed sixteen boats. The Titanic was more than four times that size, and it carried twenty: sixteen in davits and four collapsibles. It exceeded the requirement.</p>
<p>The rule reflected a sincere belief about what lifeboats were for. On busy shipping lanes, with wireless now fitted to large ships, a sinking liner was expected to stay afloat long enough for others to come alongside; lifeboats would ferry people across, making several trips. Nobody planned for a ship that sank in under three hours in a sea with no other vessel close enough to help.</p>
<p>Even the places that existed were not filled. The first boats lowered left with far fewer people than they could hold, partly because the officers were unsure the davits would bear a full load, and partly because many passengers, standing on a brightly lit deck that seemed perfectly steady, did not want to climb into a small boat on a freezing sea. "Women and children first" was applied differently on each side of the ship: on the port side the second officer, Charles Lightoller, took it to mean women and children only; on the starboard side men were let into boats when no women were waiting.</p>
<p>More than 1,500 people died, most of them from cold in water close to freezing. About 710 survived. Class mattered: roughly six in ten first-class passengers lived, against about a quarter of those in third class, many of whom were berthed far from the boat deck and found their way up too late.</p>

<h2 id="Radio">The ship that heard nothing</h2>
<p>Wireless at sea was then a commercial service. The Titanic's two operators, Jack Phillips and Harold Bride, were employees of the Marconi company, and much of their working day was spent sending passengers' paid messages. Late on 14 April the Leyland liner Californian, stopped for the night in an ice field a few hours' steaming away at most, signalled that it was surrounded by ice. Phillips, working through a backlog of traffic for the relay station at Cape Race, cut it off. The Californian's only operator switched off his set and went to bed shortly before the collision.</p>
<p>When the Titanic began calling for help, the nearest ship to hear it was the Cunard liner Carpathia, about fifty-eight nautical miles away. It raced north through the ice and reached the lifeboats at around 4 am. Officers on the Californian, meanwhile, saw rockets in the night and reported them to their captain, who did not wake his wireless operator. The British inquiry concluded that the Californian could have reached the Titanic before it sank and saved many if not all of those lost — a finding its captain disputed for the rest of his life.</p>

<h2 id="New_rules">What changed</h2>
<p>Two inquiries reported in 1912: one by a United States Senate subcommittee under William Alden Smith, the other by the British Wreck Commissioner, Lord Mersey. Neither found criminal fault. Mersey judged the speed excessive but noted that it was what every master on the route did. The lesson both drew was that the system, not any one person, had failed.</p>
<p>The first International Convention for the Safety of Life at Sea, signed in London in January 1914, set out the principle that has governed passenger shipping since: lifeboat places for everyone aboard, regular boat drills, and a continuous radio watch on passenger ships. The First World War delayed its entry into force, but its provisions were adopted by national law, and later versions of the convention — the current one dates from 1974 — remain the basis of maritime safety.</p>
<p>The United States had already acted on radio. Within months of the sinking it required large passenger ships to carry two operators and keep a radio watch around the clock, and its Radio Act of 1912 gave distress calls priority over all other traffic. And from 1914 a new International Ice Patrol, run by the US Coast Guard and paid for by the nations whose ships use the route, began tracking icebergs drifting into the North Atlantic lanes. It still does.</p>

<h2 id="Wreck">Found, and still argued over</h2>
<p>The wreck was located on 1 September 1985 by a joint French-American expedition led by Jean-Louis Michel and Robert Ballard, about 3,800 metres down. It lay in two main pieces some six hundred metres apart. That settled an argument: survivors who said the ship broke in two before sinking had been right, though both official inquiries had concluded that it went down intact. Ballard later revealed that the US Navy had paid for the search on condition that he first used the time to survey two lost nuclear submarines.</p>
<p>The wreck reopened questions about the materials. Investigators Jennifer Hooper McCarty and Tim Foecke argued that wrought-iron rivets used in the bow and stern, some containing a high proportion of slag, may have failed more easily than the steel rivets used elsewhere. Others think the steel plate, brittle in cold water, mattered more, or that the debate is beside the point: no ship of the day would have survived that collision with those bulkheads.</p>
<p>The wreck is slowly being consumed by iron-eating bacteria, one species of which was named <em>Halomonas titanicae</em> after it. Since the centenary of the sinking in 2012 it has been protected by UNESCO's convention on underwater cultural heritage. Visiting it remains dangerous: in June 2023 the privately built submersible Titan imploded on a dive to the site, killing all five people on board.</p>

<h2 id="Unsinkable">The word "unsinkable"</h2>
<p>Before the sinking, the claim was hedged. The trade journal <em>The Shipbuilder</em> described the Olympic and Titanic design as "practically unsinkable", a judgement about the watertight compartments rather than a boast. The unqualified version spread mainly afterwards, when it made the story into a parable. The less satisfying truth is that the people responsible for the Titanic did what the rules and the custom of their trade required, and that this turned out to be nowhere near enough.</p>
`,
};
