import type { RewrittenArticle } from "./types";

export const viruses: RewrittenArticle = {
  slug: "viruses",
  title: "Viruses: instructions with a delivery system, arguably not alive",
  sourceTitle: "Virus",
  dek: "No metabolism, no growth, no reproduction of their own — and yet they are the most numerous biological entities on the planet by a wide margin.",
  standfirst:
    "A virus does nothing at all outside a cell. It does not eat, respire, grow, or move under its own power; a purified virus can be crystallised like a salt and stored on a shelf. Everything we associate with being alive happens only when it gets inside something that is alive, and borrows that thing's machinery to make copies of itself. Whether that counts as living is a question biology has never satisfactorily closed.",
  readingMinutes: 8,
  html: `
<h2 id="Discovered_by_subtraction">Discovered by subtraction</h2>
<p>Viruses were found before anyone could see one, by a process of elimination. Dmitri Ivanovsky in 1892 and Martinus Beijerinck in 1898 showed that the agent causing tobacco mosaic disease passed through porcelain filters fine enough to hold back every known bacterium, and that the filtrate was still infectious. Beijerinck called it a <em>contagium vivum fluidum</em> — a living contagious fluid — which was wrong about the fluid part but correct that something new was involved.</p>
<p>For four decades a virus was defined by what it was not: not visible, not culturable on its own, not stopped by a filter. Only with the electron microscope in the 1930s did anyone actually look at one, and the first images settled a long argument by showing objects with precise, repeating geometric structure rather than the formless slime the word "fluid" had suggested.</p>
<p>Tobacco mosaic virus was crystallised in 1935. A crystal is what you get from a pure chemical compound, and the demonstration that an infectious agent could be crystallised and then reconstituted, still infectious, is what made the alive-or-not question genuinely hard rather than merely semantic.</p>

<h2 id="What_one_is_made_of">What one is made of</h2>
<p>The minimal virus is a piece of nucleic acid wrapped in a protein coat. That is the whole organism, if organism is the word.</p>
<p>The genome may be DNA or RNA, double-stranded or single, and this is one of the few places in biology where the basic informational chemistry varies — everything cellular uses double-stranded DNA without exception. Genome sizes run from a few thousand bases coding for a handful of proteins up to over two million bases in the giant viruses, which overlap the size range of small bacteria and were originally misfiled as such.</p>
<p>The coat, the capsid, is built from many copies of a small number of protein types, which is a consequence of having almost no genome to spend. A container has to be built from repeated subunits if the instructions for it must fit in a few genes, and repeated subunits assembling into a closed shell produce either a helix or an icosahedron. This is why virus structure is so monotonously geometric: it is the only architecture the information budget allows.</p>
<p>Some viruses add an envelope — a stolen patch of the host cell's own membrane, taken on the way out and studded with viral proteins. Enveloped viruses are more fragile outside a host, which is why soap works so well on them: detergent dissolves lipid membranes directly.</p>

<h2 id="The_cycle">The cycle</h2>
<p>Infection begins with a lock-and-key match between a viral surface protein and a specific molecule on the host cell. This single fact determines almost everything about a virus's behaviour — which species it can infect, which tissues within that species, and how easily it might jump between hosts. A virus that binds a receptor found only on the surface of certain immune cells will cause a disease of the immune system, and one that binds a receptor lining the airway will cause a respiratory disease. Host range is receptor compatibility, not preference.</p>
<p>Once inside, the virus does something no other parasite does: it disassembles itself. The capsid is shed, the genome is released, and for a period there is no virus present anywhere in the cell as a physical object — only its instructions, being executed by the host's ribosomes and enzymes. This eclipse phase is a genuinely strange feature, and it is why the individual-organism framing sits badly on viruses.</p>
<p>The host machinery then produces viral proteins and copies of the genome, which self-assemble into new particles. Release is either by bursting the cell or by budding through its membrane, and the yields are enormous — hundreds to many thousands of new particles from one infected cell.</p>
<p>Not all infections proceed immediately. Many viruses can integrate their genome into the host's chromosome and sit there indefinitely, replicated passively every time the cell divides, until some signal triggers reactivation. Chickenpox retreating into nerve cells and re-emerging decades later as shingles is the familiar example.</p>

<h2 id="Why_RNA_viruses_are_the_problem">Why RNA viruses are the problem</h2>
<p>Nearly every emerging infectious disease of the last century has been caused by an RNA virus, and the reason is a specific mechanical detail.</p>
<p>The enzymes that copy DNA proofread: they detect a mismatched base, back up, remove it, and try again. The enzymes that copy RNA genomes largely do not. The resulting error rate is roughly a hundred thousand to a million times higher, which means an RNA virus population is not a set of identical copies but a swarm of related variants, no two quite the same.</p>
<p>That mutation rate has direct consequences. It is why influenza vaccines must be reformulated annually while the measles vaccine has worked unchanged for decades. It is why HIV develops resistance to any single drug within weeks, and why treatment uses three at once — the probability of a variant resistant to all three arising simultaneously is far smaller than for any one. And it is why RNA viruses cross species barriers so readily: a swarm of variants is a swarm of experiments, and occasionally one of them binds a receptor in a new host.</p>
<p>There is a ceiling. Beyond a certain error rate, the genome accumulates so much damage that the population collapses — error catastrophe — and at least one antiviral drug works by pushing the mutation rate over that edge deliberately.</p>

<h2 id="Bacteriophages">The viruses that eat bacteria</h2>
<p>The most abundant biological entities on Earth are bacteriophages — viruses that infect bacteria. Estimates put the count around ten to the thirty-first, which exceeds every other kind of organism combined by orders of magnitude. There are on the order of ten million of them in a millilitre of seawater, and they kill something like a fifth to a third of ocean bacteria every day, which makes them a major force in global nutrient cycling rather than a curiosity.</p>
<p>Phages were used therapeutically in the Soviet Union and Georgia throughout the antibiotic era, largely dismissed in the West, and are being reconsidered now that antibiotic resistance has made the alternatives scarce. Their appeal is precision — a phage typically attacks a single bacterial species, leaving the rest of the microbiome intact — and their difficulty is the same thing, since treatment requires identifying the pathogen and matching a phage to it rather than administering something broad.</p>
<p>Phage biology also gave molecular biology most of its tools. The Hershey–Chase experiment that identified DNA as genetic material used phages. Restriction enzymes, the scissors of genetic engineering, are bacterial defences against phages. CRISPR is a bacterial immune system that stores fragments of phage DNA as a memory of past infections. The gene-editing revolution is, in its entirety, borrowed weaponry from a war between bacteria and their viruses.</p>

<h2 id="Inside_your_own_genome">Inside your own genome</h2>
<p>Retroviruses copy their RNA genome back into DNA and insert it into the host chromosome. When this happens in an ordinary body cell, the change dies with that cell. When it happens in a sperm or egg cell, the insertion is inherited.</p>
<p>Roughly eight per cent of the human genome consists of the remains of ancient retroviral insertions — a larger fraction than the protein-coding genes, which occupy about two per cent. Most are inert wreckage, disabled by mutation over millions of years.</p>
<p>Some are not. The protein that allows placental cells to fuse into the layer separating maternal and fetal blood is encoded by a captured retroviral gene, one whose original job was fusing a viral envelope with a cell membrane. Placental mammals — a group that includes us — depend for reproduction on a gene stolen from an infection. Independent captures of similar genes have happened in several mammalian lineages, which suggests it was not a fluke so much as an available solution.</p>

<h2 id="Alive_or_not">Alive or not</h2>
<p>The standard criteria for life — metabolism, growth, response to stimuli, reproduction — are all failed by a virus outside a cell and all arguably met by the infected cell as a system.</p>
<p>The honest position is that the category was built by generalising from cellular life and that viruses fall outside it, which is a fact about the category rather than about viruses. They evolve, they are subject to selection, they have ancestry and descent, and they participate in the biosphere at enormous scale. Whether a word coined before anyone knew they existed happens to include them is not a question with an empirical answer.</p>
<p>Where they came from is a better question and remains open. They may be escaped fragments of cellular genomes that acquired the ability to move between cells; they may be degenerate cells that shed everything not needed for parasitism; or they may predate cells entirely, as relics of a stage before life was cellular. The giant viruses, with genomes larger than some bacteria and genes for machinery no virus should need, are the main evidence that the third possibility has not been ruled out.</p>
`,
};
